#!/usr/bin/env python3
"""Original B0 attack timing writes, wrapper, and script-VM dispatch."""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute
RANGES=((0x9CE00,4),(0x9D1A0,4),(0x9D2F0,4),(0x9D300,16),
        (0x91120,4),(0x91360,4),(0x120F80,64),(0x140000,0x300),
        (0x145000,0x280),(0x150000,0x1100))
CASES=[(e,i,a,b) for e in range(3) for i in (0,1,255,256,0xFFFFFFFF)
       for a,b in ((0,0),(0x20000,0x20000),(0xFFFFFFFF,0x80000000))]

def fixture(exe,c):
 r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
 for a,n in RANGES:r[a:a+n]=bytes(n)
 def sw(a,v):struct.pack_into('<I',r,a,v&0xFFFFFFFF)
 sw(0x91120,0x800172FC);sw(0x91360,0x800198C4)
 sw(0x9D2F0,0x80145000);sw(0x145000,0x80150000)
 for i in range(0,0x1100,4):sw(0x150000+i,0xAB123456+i)
 e,index,a,b=c
 for i,v in enumerate((index,a,b)):sw(0x140000+i*4,0x80140020+i*4);sw(0x140020+i*4,v)
 if e==2:
  sw(0x9D300,0x80140100);sw(0x140100,0x80140200);sw(0x140110,1)
  for i,v in enumerate((0x60B0,0,index,a,b,0x20,0)):sw(0x140200+i*4,v)
 return r

def fingerprint(r):
 h=14695981039346656037
 for a,n in RANGES:
  for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
 return h

def main():
 exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
 assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
 common=None;patches=[];cases=[]
 for k,c in enumerate(CASES):
  r=fixture(exe,c);initial={a+i:struct.unpack_from('<I',r,a+i)[0] for a,n in RANGES for i in range(0,n,4)}
  if common is None:common={a:v for a,v in initial.items() if v}
  first=len(patches);patches.extend((a,v) for a,v in initial.items() if v!=common.get(a,0))
  args=((0x80145000,*c[1:]),(0x80140000,),())[c[0]]
  regs=execute(r,(0x8002FAD8,0x800198C4,0x80017018)[c[0]],args)
  if c[0]==1:assert regs[2]==1
  cases.append((c[0],first,len(patches),args,fingerprint(r)))
  if '--dump' in sys.argv:(ROOT/f'local/live/attack-timing-oracle-{k}.bin').write_bytes(r)
  print(k,c,hex(cases[-1][-1]),flush=True)
 out=['/* Generated by pe_attack_timing_oracle.py; original MIPS execution. */']
 for name,rows in (('ranges',RANGES),('common',sorted(common.items())),('patches',patches)):
  out.append(f'static const uint32_t SEW20_{name}[][2]={{')
  out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
 out.append('static const struct { unsigned entry,first,end; uint32_t args[4]; uint64_t hash; } SEW20_cases[]={')
 for e,a,b,args,h in cases:
  params=','.join(f'0x{x:08X}u' for x in args) or '0'
  out.append(f'    {{{e},{a},{b},{{{params}}},UINT64_C(0x{h:016X})}},')
 out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_attack_timing_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',len(cases),'original attack timing cases')
if __name__=='__main__':main()
