#!/usr/bin/env python3
"""Original 1A4AC arithmetic, with no attachment and no sound-table entries."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute


def main():
    ex = (ROOT / 'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(ex).hexdigest() == '452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    seed = bytearray(0x200000)
    seed[0x10000:0x10000 + len(ex) - 0x800] = ex[0x800:]
    struct.pack_into('<I', seed, 0x9D254, 0)
    seed[0xB0CE9] = 0
    rows = []
    for cap in (0, 1, 8, 59, 255):
        for target in (0, cap, cap + 1, 65535):
            for current in (0, 65535, 0x10000, cap << 16, (cap << 16) | 65535, 0x7FFFFFFF, 0x80000000, 0xFFFFFFFF):
                for speed in (0, 1, 0x10000, 0x30000, 0xFFFF0000, 0xFFFD0000, 0x7FFFFFFF):
                    for flags in (8, 0x208, 0x308):
                        r = bytearray(seed)
                        struct.pack_into('<H', r, 0x150012, target)
                        r[0x15000F] = cap
                        struct.pack_into('<III', r, 0x150014, current, 0x12345678, speed)
                        struct.pack_into('<I', r, 0x150098, flags)
                        execute(r, 0x8001A4AC, (0x80150000,))
                        frame, previous = struct.unpack_from('<II', r, 0x150014)
                        outflags = struct.unpack_from('<I', r, 0x150098)[0]
                        rows.append((cap, target, current, speed, flags, frame, previous, outflags))
    out = ['/* Generated by pe_animation_tick_oracle.py --write-header. */',
           'static const struct { uint32_t cap,target,current,speed,flags,frame,previous,outflags; } animation_tick_cases[]={']
    out += ['{' + ','.join(f'0x{x:X}u' for x in row) + '},' for row in rows]
    out.append('};')
    header = '\n'.join(out) + '\n'
    path = ROOT / 'pc_port/tests/retail_animation_tick_cases.h'
    if '--write-header' in sys.argv:
        path.write_text(header)
    else:
        assert path.read_text() == header
    print(f'PASS {len(rows)} original animation ticks; original 6A318 executes with no eligible sound records')


if __name__ == '__main__':
    main()
