#!/usr/bin/env python3
"""Complete original 29810 battle initialization, synthetic RAM and no mocks."""
import hashlib
import itertools
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute

RANGES=((0x9CE30,0x58),(0x9D1A0,0x168),(0xA7FF0,40),(0xB0CD8,0x200),
        (0xB8A90,28),(0xBCEA8,224),(0x120000,0x1000))


def cases():
    return itertools.product(range(4), (0,0xFFFFFFFF,0xC08000F1), (0,1), (0,3,8))


def fixture(exe, encounter, flags, active, weapon):
    r=bytearray(0x200000)
    r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    for a,n in RANGES:r[a:a+n]=bytes(n)
    def sw(a,v):struct.pack_into('<I',r,a&0x1FFFFF,v&0xFFFFFFFF)
    def sh(a,v):struct.pack_into('<H',r,a&0x1FFFFF,v&65535)
    def sb(a,v):r[a&0x1FFFFF]=v&255
    actor,record,obj,clip,source=0x80120000,0x80120400,0x80120500,0x80120600,0x80120700
    sw(0x9D254,actor);sw(0x9D278,record);sw(0x9D20C,actor)
    sw(actor,record);sw(actor+0x238,source);sw(source+0x18,650)
    sw(actor+0x98,0x200);sw(actor+0x14,0x123456);sw(actor+0x18,0xABCDEF)
    sw(record+0x68,obj);sh(obj+6,weapon);sw(0xB0E98+16,clip);sb(clip+2,6)
    sh(record+0xC,45);sh(record+0x1C,40);sh(record+0x10,9000)
    sh(record+0x22,100);sw(record+0x8,0x50000);sw(record+0x28,0x40000)
    sw(record+0x4C,flags)
    for off in (0x56,0x5E,0x66):sb(record+off,0xA5)
    sw(0x9D1A0,0x4102);sb(0x9D244,active);sw(0x9D2E8,0xFFFFFFFF)
    sw(0x9D298,0xA5A5A5A5);sw(0x9D29C,0x5A5A5A5A)
    sb(0x9CE3C,2);sb(0x9D1D4,1);sb(0x9D1DC,3);sb(0x9D2D8,4);sb(0x9D1F0,1)
    for i in range(4):sb(0xBCEA8+i*56,1);sw(0xBCEB4+i*56,0xFFFFFFFF)
    return r


def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h


def main():
    exe=(ROOT/'build/extracted/disc1/SLUS_006.62').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    common=None;patches=[];rows=[]
    for c in cases():
        r=fixture(exe,*c)
        initial={a+i:struct.unpack_from('<I',r,a+i)[0] for a,n in RANGES for i in range(0,n,4)}
        if common is None:common={a:v for a,v in initial.items() if v}
        first=len(patches);patches.extend((a,v) for a,v in initial.items() if v!=common.get(a,0))
        execute(r,0x80029810,(c[0],),instruction_budget=900000)
        rows.append((first,len(patches),c[0],fingerprint(r)))
    out=['/* Generated by pe_battle_entry_oracle.py; original instructions on synthetic state. */']
    for name,values in (('ranges',RANGES),('common',sorted(common.items())),('patches',patches)):
        out.append(f'static const uint32_t BENTRY_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in values);out.append('};')
    out.append('static const struct { unsigned first,end,encounter; uint64_t hash; } BENTRY_cases[]={')
    out.extend(f'    {{{a},{b},{c},UINT64_C(0x{h:016X})}},' for a,b,c,h in rows);out.append('};')
    content='\n'.join(out)+'\n';path=ROOT/'pc_port/tests/retail_battle_entry_cases.h'
    if '--write-header' in sys.argv:path.write_text(content)
    if '--check' in sys.argv:assert path.read_text()==content,'battle entry header drift'
    print('PASS:',len(rows),'complete original battle entry graphs')


if __name__=='__main__':main()
