#!/usr/bin/env python3
"""Original74F44+74E28 at debug0; dispatch is an explicit provider boundary."""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute
exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
out=['/* Generated by pe_clear_sdk_oracle.py --write-header. */',
     'static const uint32_t DAY1_clear_sdk_colors[][4]={']
for red,green,blue in ((0,0,0),(255,0,0),(0,255,0),(0,0,255),(18,52,86),
                       (256,511,257),(0xFFFFFFFF,0x80000080,0x12345678)):
 r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
 struct.pack_into('<2I',r,0x140000,0x00F00000,0x00010040);r[0x9574E]=0
 regs=execute(r,0x80074F44,(0x80140000,red,green,blue),stop_at=(0x80076C34,))
 assert regs[4:7]==[0x80076434,0x80140000,8]
 color=regs[7]
 # Dispatcher returns zero; original wrapper forwards it without more calls.
 ret=regs[31];regs[2]=0;execute(r,ret,initial_regs=dict(enumerate(regs)))
 assert struct.unpack_from('<2I',r,0x140000)==(0x00F00000,0x00010040)
 out.append(' {'+','.join(f'0x{v:X}u' for v in (red,green,blue,color))+'},')
out.append('};')
if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_clear_sdk_cases.h').write_text('\n'.join(out)+'\n')
print('PASS: 7 original ClearImage SDK argument/return cases; dispatcher provider returns0')
