#!/usr/bin/env python3
"""Original 76434 packet construction with explicit GPU provider contracts.

GPUSTAT is a supplied hardware value; 76BE0 returns documented v2 GPU
info3/4/5 values, and 76B98 is the packet-submission boundary. Neither
RECT clamping nor packet construction is substituted. Native tests also
execute the real linked-list worker and inspect resulting VRAM.
"""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute
RECTS=((0,0,320,240),(0,240,320,240),(1,7,320,3),(64,10,64,2),
       (63,10,64,2),(0,0,63,1),(0,0,65,1),(0,0,0,1),
       (0,0,-1,1),(0,0,320,-1),(0,0,1024,512),(1008,511,128,2),
       (-1,-1,1,1),(0,0,32767,32767),(0,0,-32768,-32768))
LIMITS=((1024,512),(0,0),(64,64),(0x8000,0xFFFF))
PROFILES=((0,0,0,0,0),(0x123456,0x321,0x12345,0xABCDE,0x3FE801),
          (0x80FEDCBA,0x7FF,0xFFFFFF,0xFFFFFF,0xFFFFFF))
def main():
 exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
 assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
 out=['/* Generated by pe_clear_image_oracle.py --write-header. */',
 'static const struct { uint32_t xy,wh,limit,color,mode,area[3],rect_out,packet[14]; } DAY1_clear_cases[]={']
 n=0
 for x,y,w,h in RECTS:
  for lw,lh in LIMITS:
   for color,mode,tl,br,offset in PROFILES:
    r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    r[0xA3300:0xA3338]=bytes([0xA5])*56
    def sw(a,v):struct.pack_into('<I',r,a&0x1FFFFF,v&0xFFFFFFFF)
    xy=(x&65535)|((y&65535)<<16);wh=(w&65535)|((h&65535)<<16);limit=lw|(lh<<16)
    sw(0x140000,xy);sw(0x140004,wh);sw(0x95750,limit)
    sw(0x95854,0x80140010);sw(0x140010,0x14802000|mode)
    before=bytes(r);calls=[];info={3:tl&0xFFFFF,4:br&0xFFFFF,5:offset&0x3FFFFF}
    regs=execute(r,0x80076434,(0x80140000,color),stop_at=(0x80076BE0,0x80076B98))
    while regs[31]:
     ret=regs[31];fn=0x80000000|((struct.unpack_from('<I',r,(ret-8)&0x1FFFFF)[0]&0x3FFFFFF)<<2)
     if fn==0x80076BE0:calls.append(regs[4]);regs[2]=info[regs[4]]
     else:assert fn==0x80076B98 and regs[4]==0x800A3300;calls.append('submit');regs[2]=0
     regs=execute(r,ret,initial_regs=dict(enumerate(regs)),stop_at=(0x80076BE0,0x80076B98))
    assert calls in (['submit'],[3,4,5,'submit']) and regs[2]==0
    check=bytearray(r[:0x1F0000]);check[0xA3300:0xA3338]=before[0xA3300:0xA3338];check[0x140004:0x140008]=before[0x140004:0x140008]
    assert check==before[:0x1F0000]
    values=(xy,wh,limit,color,mode)
    fmt=lambda values:','.join(f'0x{v:X}u' for v in values)
    out.append(' {'+fmt(values)+',{'+fmt((tl,br,offset))+'},'+fmt(struct.unpack_from('<I',r,0x140004))+',{'+fmt(struct.unpack_from('<14I',r,0xA3300))+'}},')
    n+=1
 out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_clear_image_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',n,'original ClearImage worker packet cases; GPU providers explicitly modeled')
if __name__=='__main__':main()
