#!/usr/bin/env python3
"""Execute complete retail defeat, result initialization and status reset."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute

# entry, phase, fade, animation frame, command, special kind, fade step,
# fade busy, other enemy, drops, battle flags, reset mode
CASES=[(0,p,af,f,c,k,t,b,other,drop,0x1800,0) for p,af,f,c,k,t,b,other,drop in (
    (0,0,0,0,0,0,0,0,0),(0,1,0,0,0,0,0,0,0),
    (1,1,0,0,0,0,0,0,0),(1,1,8,0,0,0,0,0,0),(1,1,0,1,0,0,0,0,0),
    (1,1,0,0,2,0,0,0,0),*( (2,1,8,0,0,t,0,0,0) for t in (0,1,7,8,15) ),
    (3,1,8,0,0,0,1,0,0),(3,0,8,0,0,0,1,0,0),
    (3,1,8,0,0,0,0,0,0),(3,1,8,0,0,0,0,1,0),
    (3,1,8,0,0,0,0,0,1),(3,1,8,0,0,0,0,0,2),
    (3,1,8,0,0,0,0,0,3),(4,1,8,0,0,0,0,0,0))]
CASES += [(entry,0,0,0,0,0,0,0,0,0,flags,mode) for entry,flags,mode in (
    (1,0x100,0),(1,0x1900,1),(1,0x100,257),(2,0,0),(2,0x1800,0))]
RANGES=((0x140000,0x7000),(0xA5D58,7*220),(0xA7FF0,40),(0xB00E8,0xD4),
        (0xB6920,0x38),(0xBCEA8,224),(0xB8628,72),(0xBCD80,32),
        (0x9D1A0,4),(0x9D1D0,8),(0x9CE3C,1),(0x9D21C,2),(0x9D234,1),
        (0x9D244,1),(0x9D268,4),(0x9D28C,4),(0x9D298,12),(0x9D304,4),
        (0x9D2E8,4),(0x9D2F4,4),(0xB0CD8,4))

def fixture(exe,c):
    r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    def sw(a,v):struct.pack_into('<I',r,a,v&0xFFFFFFFF)
    def sh(a,v):struct.pack_into('<H',r,a,v&65535)
    for a,n in RANGES:r[a:a+n]=bytes(n)
    entry,phase,fade,frame,cmd,kind,step,busy,other,drop,flags,mode=c
    sw(0x9D254,0x80140000);sw(0x9D278,0x80144000);sw(0x9D20C,0x80141000)
    sw(0x140000,0x80144000);sw(0x140004,0x80142800 if other else 0)
    sw(0x141000,0x800A5D5C);sw(0x141004,0x80142000);sw(0x142004,0x80140000)
    sw(0x14218C,0x80141000);sw(0x142800,0x80144100);sw(0xA5D58,0x80141000)
    b=0xA5D5C;r[b+0xAC]=phase;r[b+0xAF]=fade;r[b+0xAD]=step;r[b+5]=kind
    r[b+0xAE]=1;r[b+0x91]=8;sw(b+8,0xFF);sh(b+14,20)
    sh(b+0x98,100);sh(b+0x9A,3);sh(b+0x9C,10)
    sh(b+0xA0,200 if drop else 0);sh(b+0xA2,-1 if drop==2 else 3);r[b+0x9E]=5 if drop else 0
    if drop==3:
        for i in range(10):sh(0xA7FF0+i*4,50+i)
    r[0x14100E]=cmd;sh(0x141016,frame);r[0x141252]=busy;sw(0x141068,0x10000)
    for a,p in ((0x1411B4,0x146000),(0x1421B4,0x146100)):
        sw(a,0x80145000);sh(a+0xBA,1);sw(a+0x54,0x80000000+p);r[p+7]=0x3C
    sh(0x145008,1)
    sw(0x9D1A0,flags);r[0x9D2A0]=1 if phase==0 else 0
    sw(0x9D2E8,0xFFFF);sw(0x9D298,0xFFFFFFFF);sw(0x9D29C,0xFFFFFFFF)
    sh(0x14400C,45);sh(0x14401C,40);sw(0x14404C,0xFFFFFFFF)
    sw(0x140068,0xFFFFFFFF);sw(0x140098,0x100)
    sw(0xB0E98+20*4,0x80145080);r[0x145082]=8
    sw(0xB0E08,0);sw(0xB0E64,0)
    sw(0xBCFA4,0x80148000);sw(0xBCFA8,0x80148100);sw(0x148100,256)
    for i in range(3):sh(0x148000+i*8,4096)
    sw(0x14801C,1024);sh(0xB0DD0,100);sh(0xB0DD2,1000)
    return r

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    out=['/* Generated by pe_defeat_oracle.py --write-header. */','static const int ATK18_defeat_cases[][12]={']
    out+=['    {'+','.join(map(str,c))+'},' for c in CASES]
    out+=['};','static const uint64_t ATK18_defeat_expected[]={']
    for i,c in enumerate(CASES):
        r=fixture(exe,c);execute(r,(0x80028E94,0x800293F4,0x8002F300)[c[0]],(c[11] if c[0]==1 else 0x80141000,))
        out.append(f'    UINT64_C(0x{fingerprint(r):016X}),');print(i,hex(fingerprint(r)))
    out+=['};']
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_defeat_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(CASES)} original defeat / victory / status reset cases')

if __name__=='__main__':main()
