#!/usr/bin/env python3
"""Independent original-instruction damage, status and reaction fixtures."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute

# Entry (0=damage, 1=reaction), player flags, defense, hit/impact flags,
# weapon flags, resistance, special actor, restore animation, knockback,
# heading, RNG seed, PE charge, weapon power, player level.
BASE=(0,0,5,0x10000,1,0,0,1,0,0,1,1,35,50)
CASES=[]
def add(**kw):
    names=('entry','pf','defense','hit','wf','resist','special','restore','knock','heading','seed','charge','power','level')
    c=list(BASE)
    for key,v in kw.items(): c[names.index(key)]=v
    CASES.append(tuple(c))
for hit in (0x8000,0x10000,0x18000,0x20000):
    for defense in (5,200): add(hit=hit,defense=defense)
for impact in (0,0x40000,0x80000,0xC0000): add(hit=impact|0x18000,wf=0x1F01)
for flag,shift in ((0x400,0),(0x800,2),(0x1000,4),(0x100,14),(0x200,16)):
    for resistance in range(4):
        for seed in (1,10): add(wf=flag|1,resist=resistance<<shift,seed=seed)
for resistance in (0x18000,0x24000,0x14000,0x28000): add(wf=0x301,resist=resistance)
for charge in (0,1,2,10,127,-128): add(pf=0x80000,charge=charge)
add(pf=0x100000); add(pf=0x100000,power=-100)
for knock in range(5): add(knock=knock,heading=knock*1000)
for special,hit in ((1,0x10000),(0,0x10002),(0,0x1000E)):
    add(special=special,hit=hit); add(entry=1,special=special,hit=hit)
for heading in (0,1024,2048,3072): add(entry=1,heading=heading,knock=2)
add(special=1,wf=0x1001,resist=0x20)
add(restore=0); add(entry=1,pf=0x80000,hit=0x2010000)
RANGES=((0x140000,0x6000),)

def fixture(exe,c):
    r=bytearray(0x200000); r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    def sw(a,v): struct.pack_into('<I',r,a,v&0xFFFFFFFF)
    def sh(a,v): struct.pack_into('<H',r,a,v&65535)
    r[0x140000:0x146000]=bytes(0x6000)
    entry,pf,defense,hit,wf,resist,special,restore,knock,heading,seed,charge,power,level=c
    sw(0x9D254,0x80140000); sw(0x9D278,0x80144000); sw(0x9D20C,0)
    sw(0x140028,100<<16); sw(0x140030,200<<16); sh(0x14003A,heading)
    sw(0x141000,0x80143000); r[0x14100C:0x141010]=bytes((2,0,6,7))
    sw(0x141028,0); sw(0x141030,1000<<16); sh(0x14103A,heading)
    sw(0x141098,0x200); sw(0x141014,0x20000); sw(0x141018,0x30000); sw(0x14101C,0x8000)
    sw(0x143000,hit|(0x100000 if knock else 0)); sw(0x143010,1000)
    r[0x143005:0x143007]=bytes((special,2)); sh(0x14308C,defense)
    r[0x1430BC]=restore; r[0x1430A4]=knock; sh(0x1430A6,10); sw(0x1430CC,resist)
    sw(0x14404C,pf); sh(0x144004,7); sh(0x14400A,8); sh(0x14402A,20)
    sh(0x14401E,level); sw(0x144068,0x80144100); sh(0x144100,power)
    sh(0x144106,1); sw(0x144110,wf); r[0x9D2B0]=charge&255
    for i in range(3):
        sw(0xB0E98+2*192+i*4,0x80145000+i*8); r[0x145002+i*8]=8
    for i in range(1025): sh(0x9A6EC+i*2,i//2); sh(0x9589C+i*2,i*4)
    return r

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]: h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    out=['/* Generated by pe_damage_oracle.py --write-header. */','static const int ATK17_damage_cases[][14]={']
    out+=['    {'+','.join(map(str,c))+'},' for c in CASES]
    out+=['};','static const uint64_t ATK17_damage_expected[]={']
    for i,c in enumerate(CASES):
        r=fixture(exe,c); execute(r,0x80028C48 if c[0] else 0x80028574,(0x80141000,),bios_seed=c[10])
        out.append(f'    UINT64_C(0x{fingerprint(r):016X}),'); print(i,hex(fingerprint(r)),struct.unpack_from('<i',r,0x143010)[0])
    out+=['};']
    if '--write-header' in sys.argv:
        (ROOT/'pc_port/tests/retail_damage_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(CASES)} original damage / hit reaction cases')

if __name__=='__main__': main()
