#!/usr/bin/env python3
"""Complete original 2FAF8 enemy clip transitions and 2F7D8 allocation."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_scripted_exit_oracle import fixture as exit_fixture,RANGES,fingerprint,words

CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for cmd in range(18):
    for frame in (0,1,2):case(cmd=cmd,frame=frame)
for code in (0,1,2,3,4,5,6,259):case(code=code)
for state in (1,3,4):case(state=state)
for kind in (0,1,2,3,4):case(cmd=6,frame=1,kind=kind,parent=1)
case(cmd=7,frame=1,flags=0x40000000)
case(cmd=7,frame=0,flags=0x2000,kind=0)
case(cmd=7,frame=0,trigger=3)
case(cmd=6,frame=1,sound=1)
case(cmd=6,frame=2,sound=1,parent=1,kind=4)
case(battle=0);case(no_body=1)
for slot in (0,1,6,7):case(1,slot=slot)
case(1,actor_flags=0x2000)

def fixture(exe,c):
    r,s=exit_fixture(exe,{'phase':2})
    def put(a,b):r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    put(0x109B0,exe[0x109B0-0x10000+0x800:0x109B0-0x10000+0x800+216])
    b=0xA5D5C
    sw(b,c.get('flags',0));sb(b+5,c.get('kind',0));sb(b+6,2)
    sw(b+0x18,0x80000000+b+0x1C);sh(b+0xB2,0x234)
    sw(0x9D1A0,c.get('battle',2));sw(0x14118C,0x80142000 if c.get('parent') else 0)
    sw(0x141098,c.get('actor_flags',0))
    if c.get('no_body'):sw(0x141000,0)
    for i in range(6):
        rec=b+0x1C+i*16
        sb(rec,c.get('state',0));sb(rec+2,6);sb(rec+3,7)
        sw(rec+4,0x18000);sw(rec+8,0x28000);sb(rec+14,c.get('trigger',1));sb(rec+15,5)
    for a in (0x141000,0x142000):
        sb(a+14,c.get('cmd',2));sb(a+15,7)
        current,previous=((6,5),(9,7),(0,7))[c.get('frame',0)]
        sw(a+20,current<<16);sw(a+24,previous<<16)
        sh(a+0x268,-300);sh(a+0x26A,400);sh(a+0x26C,-200)
    for cmd in range(48):
        sw(0xB0E98+cmd*4,0x80145080+cmd*4);sb(0x145082+cmd*4,8)
    sw(0xBCFA4,0x80147400);sw(0xBCFA8,0x80147500);sw(0x147500,256)
    for i in range(3):sh(0x147400+i*8,4096)
    sw(0x14741C,1024);sh(0xBCF94,160);sh(0xBCF96,112)
    sh(0xB0DD0,100);sh(0xB0DD2,1000);sb(0xB0DCE,20);sb(0xB0DCF,120)
    sw(0xB0E64,0x80175000 if c.get('sound') else 0)
    sw(0x175004,0x40);sw(0x17506C,(1<<22)|0x80)
    sw(0x175084,0x100);sh(0x17508A,0x234)
    if c['entry']==1:
        for i in range(7):sw(0xA5D58+i*220,1 if i<c.get('slot',0) else 0)
    return r,s

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,seed=fixture(exe,CASES[0]);base=words(seed)
    common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for i,c in enumerate(CASES):
        r,s=fixture(exe,c);start=len(patches)
        patches.extend((j*4,v) for j,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,0x8002F7D8 if c['entry'] else 0x8002FAF8,(0x80141000,c.get('code',0)))
        cases.append((c['entry'],c.get('code',0),start,len(patches),regs[2],fingerprint(r)))
        print(i,c,hex(regs[2]),hex(fingerprint(r)),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/enemy-clip-oracle-{i}.bin').write_bytes(r)
    out=['/* Generated by pe_enemy_clip_oracle.py --write-header. */']
    for name,rows in (('common',common),('patches',patches)):
        out.append(f'static const uint32_t ATK21_clip_{name}[][2]={{')
        out += [f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows];out.append('};')
    out.append('static const struct { unsigned entry,code,first,end; uint32_t result; uint64_t hash; } ATK21_clip_cases[]={')
    out += [f'    {{{e},{c},{a},{b},0x{v:08X}u,UINT64_C(0x{h:016X})}},' for e,c,a,b,v,h in cases]
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_enemy_clip_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} complete original enemy clip and allocation call graphs')

if __name__=='__main__':main()
