#!/usr/bin/env python3
"""Run original script-98 / actor effect cleanup, including both slot pools."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute

# Script/direct, requested kind, actor instance, slot state, code, missing table.
CASES = [(1,k,i,s,code,missing) for k,i,s,code,missing in (
    (0,0,1,2,0),(2,0,1,0x75,0),(2,1,1,4,0),(9,0,1,2,0),
    (2,0,0,0x72,0),(2,0,6,0x72,0),(2,0,1,0x72,0),
    (2,0,1,0xC0,0),(2,0,1,2,1),(2,0,1,2,2),
    (2,0,2,2,0),(2,0,3,4,0),(2,0,4,0x75,0),(2,0,5,0x72,0))]
CASES += [(0,k,0,s,c,0) for k,s,c in ((0,1,2),(1,1,2),(1,6,0x72),(1,1,0xFF))]
RANGES=((0x150000,11*0xA0C),(0x160000,11*0x10C),(0xE10A0,28),(0xB0CD8,4))

def fixture(exe,c):
    r=bytearray(0x200000); r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    def sw(a,v): struct.pack_into('<I',r,a,v&0xFFFFFFFF)
    for a,n in RANGES: r[a:a+n]=bytes((i*37+19)&255 for i in range(n))
    script,kind,instance,state,code,missing=c
    sw(0x942E4,0x80150000); sw(0x942E8,0x80160000); sw(0x942E0,0x80170000)
    r[0x170000:0x170200]=bytes(0x200)
    for v,callback in ((2,0x800C9C00),(4,0x800CD960),(0x55,0x800D4850)):
        sw(0x170000+v*4,0 if missing==1 else 0x80171000+v*24)
        sw(0x171000+v*24+20,0 if missing==2 else callback)
    sw(0x9D254,0x80140000); sw(0x9D20C,0x80141000)
    for j in range(3):
        a=0x141000+j*0x400
        sw(a+4,0x80000000+a+0x400 if j<2 else 0)
        r[a+12:a+14]=bytes((2,1 if j==2 else 0)); sw(a+0x98,0x10 if j==0 else 0)
    sw(0x142000,0x80142010); sw(0x142004,0x80142014)
    sw(0x142010,kind); sw(0x142014,instance)
    for j in range(22):
        a=0x150000+j*0xA0C if j<11 else 0x160000+(j-11)*0x10C
        r[a]=state; r[a+1]=code
        sw(a+8,(0x80140000,0x80141000,0x80141400,0x80141800)[j%4])
    return r

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]: h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    out=['/* Generated by pe_effect_cleanup_oracle.py --write-header. */',
         'static const int ATK16_cleanup_cases[][6]={']
    out+=['    {'+','.join(map(str,c))+'},' for c in CASES]
    out+=['};','static const uint64_t ATK16_cleanup_expected[]={']
    results=[]
    for i,c in enumerate(CASES):
        r=fixture(exe,c)
        regs=execute(r,0x8001930C if c[0] else 0x8006FE14,
                     (0x80142000 if c[0] else 0x80141400 if c[1] else 0,))
        out.append(f'    UINT64_C(0x{fingerprint(r):016X}),')
        results.append(regs[2]); print(i,hex(fingerprint(r)),hex(regs[2]))
    out+=['};','static const uint32_t ATK16_cleanup_returns[]={',
          ','.join(f'0x{v:08X}u' for v in results),'};']
    if '--write-header' in sys.argv:
        (ROOT/'pc_port/tests/retail_cleanup_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(CASES)} complete original cleanup call graphs')

if __name__=='__main__': main()
