#!/usr/bin/env python3
"""Execute complete original enemy tick, damage popups and script restoration."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_enemy_clip_oracle import fixture as clip_fixture
from pe_scripted_exit_oracle import RANGES as EXIT_RANGES,words

RANGES=EXIT_RANGES+((0xB01C0,2800),)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for at in (0,8999,9000,65535):
    for flags in (0,1,2,0xE,0x800,0x1802):case(at=at,flags=flags)
case(at=0,flags=2,task=1);case(at=0,flags=0x800,task=1)
case(at=9000,actor_flags=0x1000)
for flags in (0x10,0x3B0,0x3D0,0x400,0x6000):case(flags=flags)
case(battle=0x102,flags=0x3D0)
for flags in (0x12000,0x1A000):
    for kind in (0,1,2,4):case(flags=flags,kind=kind)
for kind in (0,1,2,4):
    for color in (255,136):case(flags=0x4000,kind=kind,color=color)
case(flags=0x400E,kind=2);case(flags=0x400E,kind=4)
case(flags=0x4000,frame=1,restore=2,task=1)
case(flags=0x4000,frame=1,restore=2,pf=0x80000)
case(flags=0x5800,frame=1,restore=2)
for angle in (0,1024,2048,3072):case(flags=0x4000,knock=3,angle=angle)
case(hp=120,previous=100);case(hp=40,previous=30)
for kind in (0,1,2,3,4):
    for other in (0,1):case(hp=0,previous=1,kind=kind,other=other)
case(hp=0,battle=0x102)
for bank in range(2):
    for tint in range(5):
        for value in (-1,0,6,12345):case(1,bank=bank,tint=tint,value=value)
case(1,value=-22,mode=0);case(1,row=9,value=32767,timer=1);case(1,row=3,value=345,timer=0)
case(2,task=1)

def fixture(exe,c):
    r,s=clip_fixture(exe,{'entry':0,'cmd':2,'frame':0})
    def put(a,b):r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    b=0xA5D5C
    sw(b,c.get('flags',0));sb(b+5,c.get('kind',0));sw(b+16,c.get('hp',40));sw(b+20,c.get('previous',40))
    sw(b+0x88,100);sh(b+12,c.get('at',50));sh(b+0x8E,50);sh(b+0x96,3)
    sh(b+0x8C,5);sb(b+0xBC,c.get('restore',0));sb(b+0xBD,6);sb(b+0xBE,1)
    sw(b+0xC0,0x40000);sw(b+0xC4,0x30000);sw(b+0xC8,0x8000)
    sb(b+0xA4,c.get('knock',0));sb(b+0xA5,2);sh(b+0xA6,10);sh(b+0xA8,c.get('angle',0))
    sb(b+0xAF,0);sb(0x9CE68,c.get('color',255))
    sw(0x9D1A0,c.get('battle',2));sw(0x141098,c.get('actor_flags',0))
    sw(0x14118C,0x80142000);sb(0xA5E3D,3 if c.get('other') else 4)
    sw(0xA5E48,50 if c.get('other') else 0);sw(0xA5E4C,0)
    sh(0x141218,160);sh(0x14121A,112);sh(0x14103A,-300)
    if c.get('frame'):sh(0x14101A,7)
    for off in (0x68,0x6C,0x70):sw(0x141000+off,0x10000)
    sw(0x14404C,c.get('pf',0));sh(0x14401E,50);sh(0x147000,35);sw(0x147010,1)
    sw(0x144008,80<<16);sh(0x144004,7);sh(0x14400A,8);sh(0x14402A,20)
    for i in range(1025):sh(0x9A6EC+i*2,i//2);sh(0x9589C+i*2,i*4)
    for bank in range(2):
        sw(0xB0E38+bank*4,0x80146800+bank*256)
        sw(0x14681C+bank*256,0x00FFFFFF)
    put(0xB01C0,bytes((i*37+19)&255 for i in range(2800)))
    sw(0x9CDDC,c.get('bank',0));sw(0x9D230,c.get('row',0))
    if c['entry']==1:
        sh(b+0xD0,c.get('value',6));sh(b+0xD2,160);sh(b+0xD4,112)
        sb(b+0xD6,c.get('timer',30));sb(b+0xD7,c.get('tint',0))
    if c.get('task'):
        for i in range(3):
            a=0x143000+i*0x80;sw(0x1410A0+i*4,0x80000000+a)
            sw(a,0x80180000);sw(a+4,0x80180100);sh(a+8,0xFFFF);sw(a+0x24,0x80000000+a+0x40)
            sw(a+0x40,0x80180200);sh(a+0x48,0xAAAA)
    return r,s

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,seed=fixture(exe,CASES[0]);base=words(seed)
    common=[(i*4,v) for i,v in enumerate(base) if v];patches=[];cases=[]
    for i,c in enumerate(CASES):
        r,s=fixture(exe,c);start=len(patches)
        patches.extend((j*4,v) for j,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        execute(r,(0x80027D14,0x80032B0C,0x80036254)[c['entry']],
                (c.get('mode',1),0x800A5E2C) if c['entry']==1 else (0x80141000,))
        cases.append((c['entry'],c.get('mode',1),start,len(patches),fingerprint(r)))
        print(i,c,hex(fingerprint(r)),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/enemy-tick-oracle-{i}.bin').write_bytes(r)
    out=['/* Generated by pe_enemy_tick_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t ATK22_tick_{name}[][2]={{')
        out += [f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows];out.append('};')
    out.append('static const struct { unsigned entry,mode,first,end; uint64_t hash; } ATK22_tick_cases[]={')
    out += [f'    {{{e},{m},{a},{b},UINT64_C(0x{h:016X})}},' for e,m,a,b,h in cases];out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_enemy_tick_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} complete original enemy tick / damage popup / task restore cases')

if __name__=='__main__':main()
