#!/usr/bin/env python3
"""Original 9B1D0 fixed-depth model packet emitter, all eight streams."""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_m0000i_leaves_oracle import load_overlay
from pe_transition_loader_oracle import fnv
STRIDES=(28,36,36,48,40,48,48,60)
VERTEX=(4,4,12,16,16,16,24,28)
RANGES=((0,1024),(0x140000,0x8000),(0x19C9C0,4),(0x1EA5E4,4))
def fixture(base,seed,mask,mode):
 r=bytearray(base)
 def nextval():
  nonlocal seed
  seed^=(seed<<13)&0xffffffff;seed^=seed>>17;seed^=(seed<<5)&0xffffffff
  return seed
 def sw(a,v):struct.pack_into('<I',r,a,v&0xffffffff)
 for a,n in RANGES:
  for i in range(0,n,4):sw(a+i,nextval())
 ctrl={0:4096,2:4096,4:4096,5:nextval()%201-100,6:nextval()%201-100,7:nextval()%3000+1000,24:160<<16,25:120<<16,26:1000,27:-4194,28:0x1400000,29:341,30:256}
 sw(0x140000,0x40);sw(0x140004,0x40)
 for kind in range(8):
  count=(1+nextval()%3) if mask>>kind&1 else 0
  struct.pack_into('<H',r,0x140040+kind*2,count)
  sw(0x140050+kind*4,0xc0+kind*0x200)
  for i in range(3):
   p=0x140100+kind*0x200+i*STRIDES[kind]+VERTEX[kind]
   order=nextval()%4
   coords=((-200,-200),(200,-200),(-200,200),(200,200))
   if order==1:coords=(coords[0],coords[2],coords[1],coords[3])
   if order==2:coords=((0,0),)*4
   if order==3:coords=tuple(((nextval()%65536)-32768,(nextval()%65536)-32768) for _ in range(4))
   for j in range(4 if kind in (1,3,5,7) else 3):
    struct.pack_into('<4h',r,p+j*8,*coords[j],(nextval()%4096)-1024,0)
 packet=0x80145000
 if mode in (1,2):packet=0x80140100+((mask.bit_length()-1) if mask else 0)*0x200+(4 if mode==1 else 16)
 ot=0x80146000
 index=(seed>>8)&255
 if mode==3:ot=packet-index*4
 if mode==4:ot=0x80140100-index*4
 sw(0x19C9C0,0x80147000);sw(0x147000,packet);sw(0x147004,ot);sw(0x1EA5E4,index)
 return r,ctrl

def main():
 ex,o,b=load_overlay();base=bytearray(0x200000);base[0x10000:0x10000+len(ex)-0x800]=ex[0x800:];base[b&0x1fffff:(b&0x1fffff)+len(o)]=o
 digest=hashlib.sha256(o[0x8019B1D0-b:0x8019BD78-b]).hexdigest()
 assert digest=='2c946ccd523fdfd5dbcc32a802e0545f54e8f1e8f18d0a656a47f04b3f11f658'
 out=['/* Generated by pe_fixed_model_oracle.py from original overlay. */','static const struct { uint32_t seed,mask,mode,state[16]; uint64_t hash; } DAY1_fixed_model_cases[]={']
 count=0;visited=set()
 for mode in range(5):
  for mask in range(256):
   seed=(49+mode*65537+mask*101)&0xffffffff;r,ctrl=fixture(base,seed,mask,mode)
   state={};execute(r,0x8019B1D0,(0x80149999,0x80140000,mask&1),initial_cop_control=ctrl,strict_gte_flags=True,final_gte=state,instruction_budget=500000,visited_pcs=visited)
   d=state['data'];vs=d[7:15]+d[16:20]+d[24:28]
   h=fnv(b''.join(r[a:a+n] for a,n in RANGES))
   out.append(f' {{{seed},{mask},{mode},'+'{'+','.join(f'0x{x&0xffffffff:X}u' for x in vs)+'}'+f',UINT64_C(0x{h:016X})'+'},');count+=1
 out.append('};')
 header='\n'.join(out)+'\n'
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_fixed_model_cases.h').write_text(header)
 else:assert (ROOT/'pc_port/tests/retail_fixed_model_cases.h').read_text()==header
 accepted=(0x8019B2F4,0x8019B418,0x8019B53C,0x8019B674,0x8019B7D8,0x8019B934,0x8019BAAC,0x8019BC1C)
 assert all(pc in visited for pc in accepted), 'missing accepted stream coverage'
 print(f'PASS: {count} original fixed-depth model cases; 256 stream masks x5 alias modes; all8 accepted paths executed; SHA256 {digest}')
if __name__=='__main__':main()
