#!/usr/bin/env python3
"""Original 35558 overlay-bit-200 graph, including callbacks and cleanup."""
import hashlib
import itertools
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute

RANGES=((0x9CDFC,4),(0x9D1A0,0x16C),(0xB0CD8,0x400),
        (0x120000,0x240),(0x121000,0x58))


def fixture(exe,flags,present,retired):
    r=bytearray(0x200000)
    r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    for a,n in RANGES:r[a:a+n]=bytes(n)
    def sw(a,v):struct.pack_into('<I',r,a&0x1FFFFF,v&0xFFFFFFFF)
    actor,task=0x80120000,0x80121000
    sw(0x9D1A0,flags);sw(0xB0CD8,0x40000200);sw(0x9D2E8,0x105)
    sw(0x9D28C,7);sw(0x9D244,1)
    if present:
        sw(0x9D20C,actor);sw(actor+0x190,0x80035E04)
        sw(actor+0x98,0x12840022)
        for i in range(3):
            for off,v in ((0x28,0x12345678),(0x58,111),(0x68,222),
                          (0x78,-50),(0x88,17),(0x38,0x43210000)):
                sw(actor+off+i*4,v+i)
        if retired:
            sw(actor+0xA8,task);sw(task+8,16);sw(0x9CDFC,task+0x2C)
    return r


def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h


def main():
    exe=(ROOT/'build/extracted/disc1/SLUS_006.62').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    common=None;patches=[];rows=[]
    for c in itertools.product((0,2,4,6,0x100,0x102,0x104,0x106),(0,1),(0,1)):
        r=fixture(exe,*c)
        initial={a+i:struct.unpack_from('<I',r,a+i)[0] for a,n in RANGES for i in range(0,n,4)}
        if common is None:common={a:v for a,v in initial.items() if v}
        first=len(patches);patches.extend((a,v) for a,v in initial.items() if v!=common.get(a,0))
        visited=set();execute(r,0x80035558,(),instruction_budget=100000,visited_pcs=visited)
        assert 0x80035C04 in visited and 0x800355E8 not in visited and 0x800356F0 not in visited
        rows.append((first,len(patches),fingerprint(r)))
    out=['/* Generated by pe_frame_gate_oracle.py; synthetic state, original instructions. */']
    for name,values in (('ranges',RANGES),('common',sorted(common.items())),('patches',patches)):
        out.append(f'static const uint32_t FGATE_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in values);out.append('};')
    out.append('static const struct { unsigned first,end; uint64_t hash; } FGATE_cases[]={')
    out.extend(f'    {{{a},{b},UINT64_C(0x{h:016X})}},' for a,b,h in rows);out.append('};')
    content='\n'.join(out)+'\n';path=ROOT/'pc_port/tests/retail_frame_gate_cases.h'
    if '--write-header' in sys.argv:path.write_text(content)
    if '--check' in sys.argv:assert path.read_text()==content,'frame gate header drift'
    print('PASS:',len(rows),'complete original frame gate graphs')


if __name__=='__main__':main()
