#!/usr/bin/env python3
"""Run original floor collision on synthetic meshes and cached wall contacts.

Checks guest RAM effects of the complete 1AE40 graph, including recursive
edge search, triangle crossing and sliding. No code/callee mocks. This is
not an assertion about final GTE state or complete route fidelity.
"""
import hashlib
import itertools
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute

RANGES = ((0, 8), (0x9CE08, 0x28), (0x9D1D8, 4), (0x9D1FC, 4),
          (0x9D254, 4), (0x9D2E8, 4), (0x9DFB0, 0x50),
          (0x120000, 0x240), (0x130000, 0x500))


def fixture(exe, dim, wall, old, new, radius=65, npc=0):
    ram = bytearray(0x200000)
    ram[0x10000:0x10000+len(exe)-0x800] = exe[0x800:]
    for a, n in RANGES:
        ram[a:a+n] = bytes(n)

    def sw(a, v):
        struct.pack_into('<I', ram, a & 0x1FFFFF, v & 0xFFFFFFFF)

    def sh(a, v):
        struct.pack_into('<H', ram, a & 0x1FFFFF, v & 0xFFFF)

    sw(4, -17*65536)  # Visible plane constant if crossing returns physical zero.
    mesh, verts, tris, edges, plane, actor = (
        0x80130000, 0x80130100, 0x80130200, 0x80130300, 0x80130400, 0x80120000)
    sw(0x9D1FC, mesh)
    for off, value in ((0, 4), (2, 1), (4, 2), (6, 1), (8, 1)):
        sh(mesh+off, value)
    sw(mesh+24, verts); sw(mesh+28, tris)
    sw(0x9CE14, edges); sw(0x9D1D8, plane if dim else 0)
    sw(0x9CE08, mesh+40); sw(mesh+40, mesh+48)
    sw(0x9D254, 0 if npc else actor)
    sh(actor+0x224, radius); sh(actor+0x26, 4096)
    sw(actor+0x1A4, tris if old[0] >= old[1] else tris+(28 if dim else 22))
    sw(actor+0x98, 0x80000)
    sw(plane+4, 65536)
    for off, point in ((0x40, old), (0x28, new)):
        sw(actor+off, point[0]*65536+0xABCD)
        sw(actor+off+8, point[1]*65536+0x1234)
    coords = ((0, 0), (1000, 0), (1000, 1000), (0, 1000))
    ids = ((0, 1, 2), (0, 2, 3))
    eids = ((0, 1, 2), (3, 0, 4))
    tangent = ((46340, 46340), (65536, 0), (0, 65536), (0, 65536), (-65536, 0))
    for i, (x, z) in enumerate(coords):
        sh(verts+i*(6 if dim else 4), x)
        sh(verts+i*(6 if dim else 4)+(4 if dim else 2), z)
    for i, j in itertools.product(range(2), range(3)):
        t = tris+i*(28 if dim else 22)+(8 if dim else 2)
        sh(t+j*2, ids[i][j]); sh(t+6+j*2, eids[i][j])
        sh(t+12+j*2, 1-i if eids[i][j] == 0 else 0xFFFF)
    for i, (tx, tz) in enumerate(tangent):
        sw(edges+i*12, 92681900 if i == 0 else 65536000)
        sw(edges+i*12+4, tx); sw(edges+i*12+8, tz)
    if wall >= 0:
        endpoints = ((2, 0), (0, 1), (1, 2), (3, 0), (2, 3))[wall]
        p, q = (coords[i] for i in endpoints)
        for i, value in enumerate((*p, *q)):
            sh(0x9CE0C+i*2, value)
        sh(0x9CE18, wall)
        for addr, value in ((0x9CE1C, max(p[0], q[0])), (0x9CE20, min(p[0], q[0])),
                            (0x9CE24, max(p[1], q[1])), (0x9CE28, min(p[1], q[1]))):
            sw(addr, value)
        sw(0x9D2E8, 0x108)
    else:
        sw(0x9D2E8, 0x100)
    return ram


def cases():
    # Contacts, movement away, sign changes, corners, seams, and extent gates.
    moves = (((930, 300), (950, 315)), ((930, 300), (925, 315)),
             ((930, 930), (950, 950)), ((70, 300), (50, 315)),
             ((70, 70), (50, 50)), ((300, 70), (315, 50)),
             ((300, 930), (315, 950)), ((550, 450), (480, 520)),
             ((550, 450), (560, 460)), ((990, 300), (1010, 315)),
             ((300, 300), (300, 300)), ((500, 500), (400, 600)))
    for dim, wall, move in itertools.product((0, 1), range(-1, 5), moves):
        yield dim, wall, *move, 65, 0
    for dim, radius, npc, move in itertools.product((0, 1), (0, 1, 130), (0, 1), moves):
        yield dim, -1, *move, radius, npc


def fingerprint(ram):
    h = 14695981039346656037
    for a, n in RANGES:
        for b in ram[a:a+n]:
            h = ((h ^ b)*1099511628211) & 0xFFFFFFFFFFFFFFFF
    return h


def main():
    exe = (ROOT/'build/extracted/disc1/SLUS_006.62').read_bytes()
    assert hashlib.sha1(exe).hexdigest() == '452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    common, patches, rows = None, [], []
    for case in cases():
        ram = fixture(exe, *case)
        initial = {a+i: struct.unpack_from('<I', ram, a+i)[0]
                   for a, n in RANGES for i in range(0, n, 4)}
        if common is None:
            common = {a: v for a, v in initial.items() if v}
        first = len(patches)
        patches.extend((a, v) for a, v in initial.items() if v != common.get(a, 0))
        execute(ram, 0x8001AE40, (0x80120000,), instruction_budget=900000)
        rows.append((first, len(patches), fingerprint(ram)))
    out = ['/* Generated by pe_floor_collision_oracle.py; synthetic mesh, original instructions. */']
    for name, values in (('ranges', RANGES), ('common', sorted(common.items())), ('patches', patches)):
        out.append(f'static const uint32_t COL2_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a, b in values)
        out.append('};')
    out.append('static const struct { unsigned first,end; uint64_t hash; } COL2_cases[]={')
    out.extend(f'    {{{a},{b},UINT64_C(0x{h:016X})}},' for a, b, h in rows)
    out.append('};')
    content = '\n'.join(out)+'\n'
    path = ROOT/'pc_port/tests/retail_floor_collision_cases.h'
    if '--write-header' in sys.argv:
        path.write_text(content)
    if '--check' in sys.argv:
        assert path.read_text() == content, 'floor oracle header drift'
    print('PASS:', len(rows), 'original floor collision graphs')


if __name__ == '__main__':
    main()
