#!/usr/bin/env python3
"""Original formatter memory/output and explicit BIOS boundary comparisons."""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_formatter_contract import FORMATS,VALUES
from pe_transition_loader_oracle import fnv
EXTRA=('', '%', 'A%%B', '%-+#08.4hd', '%#p', '%00012u', '%*.*x', '%hhn', '%hhhu', '%20c', '%-20c', '%-8#.2s', '%8.2#s', '%020.12o', '%.530d', '%4294967296d', '%s', '%.0s', '%.4s', '%*s')
RANGES=((0x140000,0x3000),(0x1FEA00,0x800))
def main():
 ex=(ROOT/'build/disc1.candidate.exe').read_bytes();assert hashlib.sha1(ex).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
 assert hashlib.sha256(ex[0x71A84-0xF800:0x72308-0xF800]).hexdigest()=='3eaf80663eeaeaa09560a87c5468b74afad3fa6ea1177d7a81b6f15eae4331e4'
 common=[]
 for start,size in ((0x1161C,40),(0x11644,180),(0x94528,12)):
  for off in range(start,start+size,4):common.append((off,struct.unpack_from('<I',ex,off-0xF800)[0]))
 out=['/* Original formatter with explicit frame. Generated by pe_formatter_frame_oracle.py. */','static const uint32_t DAY1_formatter_frame_common[][2]={']
 out += [f'{{0x{a:X}u,0x{b:X}u}},' for a,b in common];out+=['};','static const uint32_t DAY1_formatter_frame_ranges[][2]={{0x140000,0x3000},{0x1FEA00,0x800}};','static const struct {const char *format;uint32_t args[3],destination,stack,defaults[3],result,target,boundary[3];uint64_t hash;} DAY1_formatter_frame_cases[]={']
 seen=set();n=0
 variants=('[%020d]', 'A%n:%u', '%#8s', '%-#8s', '%u', '%d', '%#08x', '%*.*x')
 jobs=[(fmt,value,0) for fmt in FORMATS+EXTRA for value in VALUES]
 jobs += [(fmt,value,i+1) for i,fmt in enumerate(variants) for value in VALUES]
 for fmt,value,variant in jobs:
  r=bytearray(0x200000);r[0x10000:0x10000+len(ex)-0x800]=ex[0x800:]
  for start,size in RANGES:r[start:start+size]=bytes(size)
  stack=0x801FEE00 if variant==7 else 0x801FF040 if variant==8 else 0x801FF000
  destination=stack-0x250+0x1E0 if variant==1 else 0x80142001 if variant==3 else 0x80142002 if variant==4 else 0x80141000
  defaults=[0,12,3] if variant==5 else [0x2000,12,3] if variant==6 else [0,0,0]
  for i,v in enumerate(defaults):struct.pack_into('<I',r,0x94528+i*4,v)
  encoded=fmt.encode()+b'\0';r[0x140000:0x140000+len(encoded)]=encoded
  r[0x142000:0x142008]=b'\x03abcXYZ\0'
  args=[value,0x30,0x41]
  if fmt in ('%*d','%.*u'):args=[(-8 if value&1 else 8)&0xFFFFFFFF,value,0]
  if fmt=='%*.*x':args=[(-12 if value&1 else 12)&0xFFFFFFFF,8,value]
  if 's' in fmt or 'n' in fmt:args=[0x80142000,0,0]
  if fmt=='%*s':args=[8,0x80142000,0]
  if variant==2:args=[stack+12,value,0]
  struct.pack_into('<I',r,(stack+16)&0x1FFFFF,args[2])
  initial={16+i:0x13570000+i*0x1111 for i in range(8)}
  initial[29]=stack
  regs=execute(r,0x80071A84,(destination,0x80140000,args[0],args[1]),initial_regs=initial,stop_at=(0x80072314,0x80072324),visited_pcs=seen)
  target=0
  if regs[31]:
   ins=struct.unpack_from('<I',r,(regs[31]-8)&0x1FFFFF)[0];target=0x80000000|((ins&0x3FFFFFF)<<2)
   assert target in (0x80072314,0x80072324)
  else:assert r[(destination+regs[2])&0x1FFFFF]==0
  boundary=[regs[4],0,regs[6] if target==0x80072324 else 0]
  h=14695981039346656037
  for start,size in RANGES:h=fnv(r[start:start+size],h)
  a=','.join(f'0x{v:X}u' for v in args);b=','.join(f'0x{v:X}u' for v in boundary)
  d=','.join(f'0x{v:X}u' for v in defaults)
  out.append(f'{{"{fmt}",{{{a}}},0x{destination:X}u,0x{stack:X}u,{{{d}}},0x{regs[2]:X}u,0x{target:X}u,{{{b}}},UINT64_C(0x{h:016X})}},');n+=1
 assert {0x800721A8,0x800721BC,0x800722D0,0x80072334}<=seen
 out.append('};');header='\n'.join(out)+'\n';p=ROOT/'pc_port/tests/retail_formatter_frame_cases.h'
 if '--write-header' in sys.argv:p.write_text(header)
 else:assert p.read_text()==header
 print(f'PASS {n} original formatter frame executions, including explicit string BIOS stops')
if __name__=='__main__':main()
