#!/usr/bin/env python3
"""Original 80078E04/80078E94 (SetRotMatrix / SetTransMatrix) then RTPT."""
import hashlib
import struct
import sys

from pe_battle_hud_oracle import ROOT, execute

RANGES = ((0x140000, 0x20), (0x141000, 0x10), (0x141020, 0x18))
SHA_EXE = "452fb033f2eaa4b18aa20a5bca60b8125af3a37b"


def fingerprint(r):
    h = 14695981039346656037
    for a, n in RANGES:
        for b in r[a:a + n]:
            h = ((h ^ b) * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return h


def main():
    exe = (ROOT / "build/disc1.candidate.exe").read_bytes()
    assert hashlib.sha1(exe).hexdigest() == SHA_EXE
    cases = []
    patches = []
    matrices = (
        (0x1000, 0, 0, 0, 0x1000, 0, 0, 0, 0x1000, 0, 0, 200),
        (0x1000, 0x80, 0, 0, 0x1000, 0, 0, 0, 0x1000, 10, -20, 400),
        (-0x1000, 0, 0, 0, 0x1000, 0, 0, 0, 0x1000, 0, 0, 80),
    )
    common = None
    for cells in matrices:
        r = bytearray(0x200000)
        r[0x10000:0x10000 + len(exe) - 0x800] = exe[0x800:]

        def sw(a, v):
            struct.pack_into("<I", r, a & 0x1FFFFF, v & 0xFFFFFFFF)

        for i, cell in enumerate(cells[:9]):
            struct.pack_into("<h", r, 0x140000 + i * 2, cell)
        for i, cell in enumerate(cells[9:]):
            sw(0x140014 + i * 4, cell)
        struct.pack_into("<hhh", r, 0x141020, 80, 0, 40)
        struct.pack_into("<hhh", r, 0x141028, 0, 20, 40)
        struct.pack_into("<hhh", r, 0x141030, -40, 0, 40)
        seed = {a + i: struct.unpack_from("<I", r, a + i)[0]
                for a, n in RANGES for i in range(0, n, 4) if struct.unpack_from("<I", r, a + i)[0]}
        if common is None:
            common = dict(seed)
        first = len(patches)
        patches.extend((a, v) for a, v in seed.items() if v != common.get(a, 0))
        execute(r, 0x80079024, (0x3E8,))
        execute(r, 0x80079004, (0, 0))
        execute(r, 0x80078E04, (0x80140000,))
        execute(r, 0x80078E94, (0x80140000,))
        regs = execute(
            r, 0x80079274,
            (0x80141020, 0x80141028, 0x80141030,
             0x80141000, 0x80141004, 0x80141008,
             0x8014100C, 0x80141010),
        )
        cases.append((first, len(patches), fingerprint(r), regs[2] & 0xFFFFFFFF))
        print(cells, hex(cases[-1][2]), hex(cases[-1][3]), flush=True)
    out = ["/* Generated by pe_gte_rt_leaves_oracle.py; original EXE execution. */"]
    for name, rows in (("ranges", RANGES), ("common", sorted(common.items())),
                       ("patches", patches)):
        out.append(f"static const uint32_t DAY1_gte_rt_{name}[][2]={{")
        out.extend(f"    {{0x{a:X}u,0x{b:X}u}}," for a, b in rows)
        out.append("};")
    out.append("static const struct { unsigned first,end; uint32_t ret; uint64_t hash; } DAY1_gte_rt_cases[]={")
    out.extend(f"    {{{a},{b},0x{ret:X}u,UINT64_C(0x{h:016X})}},"
               for a, b, h, ret in cases)
    out.append("};")
    if "--write-header" in sys.argv:
        (ROOT / "pc_port/tests/retail_gte_rt_leaves_cases.h").write_text("\n".join(out) + "\n")
    print("PASS:", len(cases), "original GTE RT leaf cases")


if __name__ == "__main__":
    main()
