#!/usr/bin/env python3
"""Original game-over phase 3 fade-start state, excluding presentation packets."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_defeat_oracle import fixture as defeat_fixture
from pe_scripted_exit_oracle import words
RANGES=((0x9CE70,8),(0x140000,0x7000),(0xB0CEC,0xC0))
ENTRIES=(0x8002B29C,)
CASES=[dict(entry=0,timer=t,busy=b,flags=f) for t in (0,1,25,26,80,255)
       for b in (0,1) for f in (0,0x100)]

def fixture(exe,c):
    r=defeat_fixture(exe,(0,0,0,0,0,0,0,0,0,0,0x1800,0))
    def sw(a,v):struct.pack_into('<I',r,a,v&0xFFFFFFFF)
    def sh(a,v):struct.pack_into('<H',r,a,v&65535)
    r[0x9CE74]=3;r[0x9CE70]=c['timer']
    r[0x140252]=c['busy'];r[0xB0D8A]=c['busy']
    sh(0x140250,c['flags']);sh(0xB0D88,c['flags'])
    # Original entry also submits the existing game-over packet. That
    # presentation is outside this bounded fade-state comparison.
    sw(0xB0E38,0x80170000);sw(0x9CDDC,0)
    return r,bytearray(r),()

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args)
        result=regs[2];h=fingerprint(r)
        cases.append((c['entry'],first,len(patches),args,result,h))
        print(k,c,hex(result),hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/gameover-fade-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_gameover_fade_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t INV17_gameover_fade_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2],result; uint64_t hash; } INV17_gameover_fade_cases[]={')
    for e,a,b,args,result,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{result:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_gameover_fade_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original game-over fade-state cases')

if __name__=='__main__':main()
