#!/usr/bin/env python3
"""Original hit judgement / shot dispatch and scripted camera regression cases.

Run with --write-header to regenerate the checked-in native expectations.
The expected state is produced by executing original instructions, including
the BIOS RNG contract. No native game implementation is called here.
"""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute

# dispatch, weapon kind, target x/z, range, weapon flags, player flags,
# target flags, inherited hit, seed, frame before call, heading
HITS=[]
for distance in (0,500,501,800,801,1000,1001,1200,1201,1500,1501,1800,1801):
    for seed in (1,10): HITS.append((0,1,0,distance,1000,0x12,0,0,0,seed,0,2048))
HITS += [(0,8,0,d,1000,0x20012,0,0,0,seed,0,2048) for d in (100,1000,1001) for seed in (1,10)]
HITS += [(0,6,0,1900,1000,0x12,0,0,p,1,0,2048) for p in (1,2,3,4)]
HITS += [(0,1,0,100,1000,0x12,0x100000,0,0,1,0,2048),
         (0,1,0,100,1000,0x12,0,0x4000,0,1,0,2048),
         (0,1,0,300,1000,0x12,0x10,0,0,10,0,2048)]
HITS += [(1,k,x,z,1000,shape,flags,af,0,seed,frame,head) for k,x,z,shape,flags,af,seed,frame,head in (
    (1,0,500,0x12,0,0,1,0,2048),(1,0,500,0x12,0,0,1,1,2048),
    (1,0,1000,0x12,0,0,10,1,2048),(1,0,1800,0x12,0,0,1,1,2048),
    (1,0,1900,0x12,0,0,1,1,2048),(1,0,500,0x12,0,0x4000,1,1,2048),
    (1,0,500,0x12,0x100000,0,1,1,2048),(6,0,500,0x12,0,0,1,1,2048),
    (6,0,500,0x12,0,0,10,1,2048),(8,0,500,0x12,0,0,1,1,2048),
    (1,100,400,0x92,0,0,1,1,2048),(1,-100,-400,0x92,0,0,1,1,0),
    (1,400,100,0x92,0,0,1,1,3072),(1,-400,100,0x92,0,0,1,1,1024))]
# flags, step, duration, start x/y, destination x/y, width, height
CAMERAS=((0x79,1,1,160,400,160,112,320,224),
         (0x71,1,4,160,400,200,112,640,512),
         (0x72,2,4,160,400,200,112,640,512),
         (0x72,4,4,160,400,200,112,640,512),
         (0x7A,2,4,400,112,-200,400,320,224),
         (0x7B,4,4,400,112,-200,400,320,224),
         (0x74,2,4,160,400,160,112,320,224),
         (0x31,1,4,160,400,160,112,320,224),
         (0x73,3,4,-100,-300,159,111,321,225),
         (0x7A,3,4,-100,-300,159,111,321,225))
HIT_RANGES=((0x140000,0x4800),(0x9CE54,2),(0x9D274,1),(0x9D294,1))
CAMERA_RANGES=((0xBCF88,0x1C),)

def memory(exe):
    r=bytearray(0x200000); r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    def sw(a,v): struct.pack_into('<I',r,a,v&0xFFFFFFFF)
    def sh(a,v): struct.pack_into('<H',r,a,v&65535)
    return r,sw,sh

def hit_fixture(exe,c):
    r,sw,sh=memory(exe)
    for a,n in HIT_RANGES: r[a:a+n]=bytes(n)
    dispatch,kind,x,z,range_,shape,flags,af,previous,seed,frame,heading=c
    sw(0x9D254,0x80140000); sw(0x9D278,0x80144000); sw(0x9D20C,0x80141000)
    sh(0x14003A,heading); sw(0x141000,0x80143000); sw(0x141004,0x80142000)
    sw(0x142000,0x80143100); sw(0x143010,100); sw(0x143110,100)
    sh(0x141268,x); sh(0x14126C,z); sh(0x142268,300); sh(0x14226C,300)
    sw(0x141098,af); sw(0x143000,0x800FC010); sw(0x143100,0x800FC010)
    sh(0x141218,70); sh(0x14121A,50); sh(0x142218,90); sh(0x14221A,60)
    sw(0x144068,0x80144100); sw(0x14404C,flags)
    sh(0x144102,range_); sh(0x144106,kind); sw(0x144108,2)
    sw(0x14410C,0x300006); sw(0x144110,shape)
    sw(0xBE830,0x80141000); r[0x9D1D4]=0; r[0x9D274]=frame; r[0x9D294]=1
    sw(0xB0E08,0)
    sw(0xBCFA4,0x80146000); sw(0xBCFA8,0x80146100); sw(0x146100,256)
    for i in range(3): sh(0x146000+i*8,4096)
    sw(0x14601C,1024); sh(0xBCF94,160); sh(0xBCF96,112)
    sh(0xB0DD0,100); sh(0xB0DD2,1000); r[0xB0DCE:0xB0DD0]=bytes((20,120))
    # Shared input angle table; endpoints and indexing remain original.
    for i in range(1025): sh(0x9A6EC+i*2,i//2)
    return r

def camera_fixture(exe,c):
    r,sw,sh=memory(exe)
    for a,n in CAMERA_RANGES: r[a:a+n]=bytes(n)
    flags,step,duration,sx,sy,dx,dy,w,h=c
    sw(0xBCF88,flags); sh(0xBCFA0,step); sh(0xBCFA2,duration)
    for a,v in ((0xBCF8C,sx),(0xBCF8E,sy),(0xBCF98,sx),(0xBCF9A,sy),(0xBCF9C,dx),(0xBCF9E,dy)): sh(a,v)
    sw(0xB1624,0x80150000); sw(0x15001C,0x100); r[0xBCFFD]=0
    sh(0x150128,w); sh(0x15012A,h)
    for i in range(1025): sh(0x9589C+i*2,i*4)
    return r

def fingerprint(r,ranges):
    h=14695981039346656037
    for a,n in ranges:
        for b in r[a:a+n]: h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    output=['/* Generated by tools/pe_hit_camera_oracle.py --write-header. */']
    for name,cases,fixture,ranges in (('ATK15_hit',HITS,hit_fixture,HIT_RANGES),('STG8_camera',CAMERAS,camera_fixture,CAMERA_RANGES)):
        hashes=[]
        for k,c in enumerate(cases):
            r=fixture(exe,c)
            if name=='ATK15_hit': execute(r,0x800236E8 if c[0] else 0x80021278,(0x80141000,0x8009CE54,c[8]),bios_seed=c[9])
            else: execute(r,0x80066268)
            hashes.append(fingerprint(r,ranges))
            print(name,k,hex(hashes[-1]))
        output += [f'static const int {name}_cases[][{len(cases[0])}]={{']
        output += ['    {'+','.join(str(v) for v in c)+'},' for c in cases]
        output += ['};',f'static const uint64_t {name}_expected[]={{']
        output += [f'    UINT64_C(0x{h:016X}),' for h in hashes]
        output += ['};']
    if '--write-header' in sys.argv:
        (ROOT/'pc_port/tests/retail_hit_camera_cases.h').write_text('\n'.join(output)+'\n')
    print(f'PASS: {len(HITS)} hit/shot cases and {len(CAMERAS)} camera cases')

if __name__=='__main__': main()
