#!/usr/bin/env python3
"""Original BE180 hit-origin/child initialization and weapon-VM dispatch.

Executes full original callees including enabled sound FIFO producers. Texture
cache hits are covered here; CEDA8 transfer coverage lives in pistol tests.
"""
import hashlib,itertools,struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_weapon_tick_oracle import fixture as weapon_fixture,RANGES as WEAPON_RANGES
from pe_scripted_exit_oracle import words
RANGES=WEAPON_RANGES+((0xE27F0,24),(0xB0CE8,4),(0xB0E14,4),(0xF34E4,4),
 (0x9CDF0,4),(0x9D2F4,4),(0x9D268,4),(0x9D2B0,16),(0xB8628,0x480),(0xBCD80,24),
 (0x173000,0x100))
ENTRIES=(0x800CD980,0x800CDA5C,0x800CDC24,0x800C2758)
def cases():
 for e,seed in itertools.product((1,2),(0,1,2,3,10,65535,0x7FFFFFFF,0x80000000,0xFFFFFFFF)):
  for pos in ((0,0,0),(-32768,32767,-1),(100,-200,50)):
   yield dict(entry=e,seed=seed,pos=pos)
 for e,index,more,audio in itertools.product((0,3),(0,1,7),(False,True),(0,1,2)):
  yield dict(entry=e,index=index,more=more,audio=audio,seed=37+index)
def fixture(exe,c):
 program=[0x10000,0x10001,0x10002,0x20001,0xFFFFFFFF]
 r,s,_=weapon_fixture(exe,dict(entry=0,program=program))
 def put(a,b):r[a:a+len(b)]=b;s[a:a+len(b)]=b
 def w(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
 def h(a,v):put(a,struct.pack('<H',v&65535))
 for a,n in RANGES[len(WEAPON_RANGES):]:put(a,bytes(n))
 put(0x150200,bytes((i*17+3)&255 for i in range(0x200)))
 index=c.get('index',0)
 w(0x150048,index);w(0x15004C,0x76543210);w(0x150058,0x80173000)
 for i in range(3):
  w(0x171100+i*4,ENTRIES[i]);h(0x171180+i*2,(0,112,16)[i])
  h(0xE27F0+i*2,c.get('pos',(100,-200,50))[i]);h(0x140268+i*2,(-32768,32767,index)[i])
 w(0x173000+index*4,0x80140000);w(0x173004+index*4,0x80143000 if c.get('more') else 0)
 w(0xB0CE8,c.get('audio',0));w(0xB0E14,0x80173080)
 w(0x173080,0x4F414B41 if c.get('audio')==2 else 0)
 w(0x9CDF0,0x5FF if index==7 else 0x405)
 return r,s

def fingerprint(r):
 h=14695981039346656037
 for a,n in RANGES:
  for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
 return h

def main():
 exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
 assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
 base=None;patches=[];rows=[]
 for k,c in enumerate(cases()):
  r,s=fixture(exe,c);initial=words(s)
  if base is None:base=initial
  first=len(patches);patches.extend((i*4,v) for i,(v,b) in enumerate(zip(initial,base)) if v!=b)
  args=(0x80150000,0x80171100,0x80171180) if c['entry']==3 else (0x80150000,0x80150080,0x80150200)
  before=bytes(r)
  regs=execute(r,ENTRIES[c['entry']],args,bios_seed=c['seed'])
  for a,(old,new) in enumerate(zip(before[:0x1F0000],r[:0x1F0000])):
   if old!=new:assert any(start<=a<start+size for start,size in RANGES),('uncompared original write',k,hex(a))
  if c['entry']==3:
   assert r[0x150012]==3 and r[0x150081]==1 and r[0x150087]==1 and r[0x15008D]==1,('children not created',k)
  if c.get('audio')==2:assert struct.unpack_from('<I',r,0x9D2F4)[0]==1,('sound not enqueued',k)
  rows.append((c['entry'],c['seed'],first,len(patches),regs[2] if c['entry']==3 else 0,fingerprint(r)))
  print(k,c,hex(rows[-1][-1]),flush=True)
  if '--dump' in sys.argv:(ROOT/f'local/live/hit-init-original-{k}.bin').write_bytes(r)
 out=['/* Generated by pe_hit_init_oracle.py --write-header. */']
 for name,data in (('ranges',RANGES),('common',[(i*4,v) for i,v in enumerate(base) if v]),('patches',patches)):
  out.append(f'static const uint32_t DAY1_hit_init_{name}[][2]={{')
  out.extend(f' {{0x{a:X}u,0x{v:X}u}},' for a,v in data);out.append('};')
 out.append('static const struct { unsigned entry,seed,first,end,result; uint64_t hash; } DAY1_hit_init_cases[]={')
 out.extend(' {'+','.join(str(v)+'u' for v in row[:-1])+f',UINT64_C(0x{row[-1]:016X})'+'},' for row in rows)
 out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_hit_init_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',len(rows),'complete original hit initialization cases')
if __name__=='__main__':main()
