#!/usr/bin/env python3
"""Original BE50C hit-draw callbacks and the shared C3B04 sprite renderer.

Executes the complete original call graphs, including 79244/79E14/78C34,
page/blend setup and GetClut. Texture-cache hits only; no invented formulas.
"""
import hashlib,itertools,struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_pistol_effect_oracle import fixture as pistol_fixture,RANGES as PISTOL_RANGES
from pe_scripted_exit_oracle import words

RANGES=PISTOL_RANGES+((0,0x400),(0xE224C,4),(0xE2770,0x80),(0xF33E8,0x40),
 (0xB0E38,8),(0xB0E58,8),(0x9CDD8,8),(0xBCFA4,8),(0xE284C,4))
ENTRIES=(0x800C3B04,0x800CDD0C,0x800CDE90)

def cases():
    for bank,bright,angle,pos in itertools.product((0,1),(0x80,0x40,0x7F,1),
                                                   (0,-0x200,0x400),(0,1)):
        yield dict(entry=0,bank=bank,bright=bright,angle=angle,pos=pos)
    for uv,rgb,scale in itertools.product((0,0x35,0xF1),(0x204080,0x7F7F7F),(0x20C,0x400)):
        yield dict(entry=0,uv=uv,rgb=rgb,scale=scale,bright=0x80)
    for age,off,part in itertools.product((1,20,127),(0,50,-30),(0,1,7)):
        yield dict(entry=1,age=age,off=off,part=part,bank=part&1)
    for age,pos in itertools.product((4,64,120),((0,0,0),(100,-50,25),(-200,80,-10))):
        yield dict(entry=2,age=age,xyz=pos,bank=0)

def fixture(exe,c):
    r,s,_=pistol_fixture(exe,dict(entry=0,bank=c.get('bank',0),
                                  translation=c.get('xyz',(200,-300,500))))
    def put(a,b):r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    for a,n in RANGES[len(PISTOL_RANGES):]:put(a,bytes((i*13+9)&255 for i in range(n)))
    put(0x966EC,exe[0x966EC-0x10000+0x800:0x966EC-0x10000+0x800+0x4000])
    sw(0xBCFA4,0x80140000);sw(0xBCFA8,0x80140020);sw(0x140020,256)
    sw(0x9CDDC,c.get('bank',0));sw(0x9CDD8,0)
    sw(0xB0E58,0x80160000);sw(0xB0E5C,0x80162000)
    sw(0xB0E38,0x80164000);sw(0xB0E3C,0x80168000)
    for a in range(0x164000,0x16C000,4):sw(a,0xCCFFFFFF)
    for a in range(0x160000,0x164000,4):sw(a,0)
    pos=((100,-80,40),(0,0,200))[c.get('pos',0)]
    style=0x150000
    sh(style+0,pos[0]);sh(style+2,pos[1]);sh(style+4,pos[2])
    sw(style+0x10,c.get('scale',0x20C));sw(style+0x14,c.get('scale',0x20C))
    sh(style+0xC,c.get('angle',0));sh(style+0x26,c.get('bias',0))
    sh(style+0x28,c.get('bright',0x80))
    sb(style+0x24,c.get('uv',0x12));sb(style+0x25,c.get('uv',0x12))
    rgb=c.get('rgb',0x204060)
    sb(style+0x20,rgb&255);sb(style+0x21,(rgb>>8)&255);sb(style+0x22,(rgb>>16)&255)
    for base in (0xE2770,0xE27B0,0xF33E8):
        put(base,bytes(r[style:style+0x30]))
    data=0x151000
    put(data,bytes((i*19+5)&255 for i in range(0x80)))
    for i,v in enumerate(c.get('xyz',(80,-40,20))):sh(data+4+i*2,v)
    sh(data+10,c.get('off',10));sh(data+12,c.get('off',-6));sh(data+14,4)
    sb(data+1,c.get('age',20));sb(data+3,c.get('part',1))
    for i in range(8):
        sh(data+16+i*2,pos[0]+i*3);sh(data+32+i*2,pos[1]-i);sh(data+48+i*2,pos[2]+i*2)
    args=((0x80150000,), (0x80150000,0x80150080,0x80151000),
          (0x80150000,0x80150080,0x80151000))[c['entry']]
    return r,s,args

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    base=None;patches=[];rows=[]
    for k,c in enumerate(cases()):
        r,s,args=fixture(exe,c);initial=words(s)
        if base is None:base=initial
        first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(initial,base)) if v!=b)
        before=bytes(r)
        execute(r,ENTRIES[c['entry']],args,initial_cop_control={24:160<<16,25:112<<16,26:256,29:0x155})
        for a,(old,new) in enumerate(zip(before[:0x1F0000],r[:0x1F0000])):
            if old!=new:assert any(start<=a<start+size for start,size in RANGES),('uncompared original write',k,hex(a))
        rows.append((c['entry'],first,len(patches),args,fingerprint(r)))
        print(k,c,hex(rows[-1][-1]),flush=True)
        if '--dump' in sys.argv:(ROOT/f'local/live/hit-draw-original-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_hit_draw_oracle.py --write-header. */']
    for name,data in (('ranges',RANGES),('common',[(i*4,v) for i,v in enumerate(base) if v]),('patches',patches)):
        out.append(f'static const uint32_t DAY1_hit_draw_{name}[][2]={{')
        out.extend(f' {{0x{a:X}u,0x{v:X}u}},' for a,v in data);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[3]; uint64_t hash; } DAY1_hit_draw_cases[]={')
    for e,a,b,args,h in rows:
        params=','.join(f'0x{x:08X}u' for x in list(args)+[0]*(3-len(args)))
        out.append(f' {{{e}u,{a}u,{b}u,{{{params}}},UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_hit_draw_cases.h').write_text('\n'.join(out)+'\n')
    print('PASS:',len(rows),'complete original hit-draw cases')
if __name__=='__main__':main()
