#!/usr/bin/env python3
"""Original inventory command history rollback and battle selection undo."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_inventory_ammo_oracle import fixture as ammo_fixture,RANGES as AMMO_RANGES
from pe_inventory_use_oracle import fixture as use_fixture
from pe_scripted_exit_oracle import words

RANGES=AMMO_RANGES+((0xBE830,360),)
ENTRIES=(0x800533D4,0x8005112C,0x8005112C,0x8005112C,0x80026CF0)
RESULT_ENTRIES={0}
CASES=[]
def case(entry=1,**kw):CASES.append(dict(entry=entry,**kw))
for record in (0,0x800C0EAC,0x800C0ECC,0x800C0FEC,0xC0EAC,0x80123456):
    for count in (-1,0,1,10):
        for bank in (0,1):case(0,record=record,count=count,bank=bank)
for position in (0,36,144):
    for kind in (0,1,2,3,4,5,0xFFFFFFFF):case(position=position,kind=kind)
for slot in (-1,0,1,2,9):
    for item in (6,256,512):case(kind=0,slot=slot,item=item)
for kind in (2,3):
    for record in (0,0x800C0EAC,0x800C0FEC,0x80123456):case(kind=kind,record=record,bank=1)
for first,second,extra in ((0,0,0),(0x800A1AB0,0x800A1AC0,0),(0x800C0EAC,0x800C0EAC,0x800C0EAC)):
    case(kind=4,refs=(first,second,extra))
for reserve in ((0,0),(30,0),(0,30)):
    for changed in (0,1,2,3):case(2,reserve=reserve,changed=changed)
for item in (6,10,13):
    for occupied in (0,1):case(3,item=item,occupied=occupied)
for command in (-1,0,1,2,9,387,393,407,408,409):
    for count in (1,3):
        for saved in (0,1):case(4,command=command,commands=count,saved=saved)
for command in (1,2,9):
    for shape in (0,0x40,0xC0):case(4,command=command,commands=3,shape=shape,shots=1)

def fixture(exe,c):
    if c['entry']==3:r,s,_=use_fixture(exe,dict(entry=1,item=c.get('item',6),battle=1))
    else:r,s,_=ammo_fixture(exe,dict(c,entry=3))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    def word(a):return struct.unpack_from('<I',r,a&0x1FFFFF)[0]
    entry=0x800A1AA0+c.get('position',36)-36
    sw(0x9D014,entry+36);sw(entry,c.get('kind',0));sw(entry+4,c.get('item',6))
    sw(entry+8,c.get('slot',2))
    if c.get('kind') in (2,3):sw(entry+4,c.get('record',0x800C0EAC))
    if c.get('kind')==4:
        for i,p in enumerate(c.get('refs',(0x800C0EAC,0x800A1E64,0))):sw(entry+4+i*4,p)
        for offset,value in ((20,5),(28,7),(32,11)):sw(entry+offset,value)
    if c['entry']==0:sw(0x9D050,c.get('count',10))
    if c['entry']==2:
        sw(0x9D014,0x800A1AA0);execute(r,0x80057094)
    if c['entry']==3:
        sw(0x9D014,0x800A1AA0);execute(r,0x80057834,(2,))
        if c.get('occupied'):sh(0xC0E4C,10)
    if c['entry']==4:
        count=c.get('commands',3);sb(0x9CE3C,count);sb(0x9D2D8,2);sb(0x9D1DC,c.get('shots',3))
        sb(0x9CE60,c.get('saved',0));sb(0x9D2B0,3);sw(0x15D110,3|c.get('shape',0))
        for i in range(45):
            sw(0xBE830+i*8,0x80141000+i*64);sh(0xBE834+i*8,c.get('command',9))
            sh(0xBE836+i*8,3 if i>=count-2 else 1)
    args=(c.get('record',0x800C0EAC),) if c['entry']==0 else ()
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args,instruction_budget=900000)
        result=regs[2] if c['entry'] in RESULT_ENTRIES else 0;h=fingerprint(r)
        cases.append((c['entry'],first,len(patches),args,result,h))
        print(k,c,hex(result),hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/inventory-undo-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_inventory_undo_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t INV12_inventory_undo_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2],result; uint64_t hash; } INV12_inventory_undo_cases[]={')
    for e,a,b,args,result,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{result:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_inventory_undo_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original inventory record lookup, history and command undo cases')

if __name__=='__main__':main()
