#!/usr/bin/env python3
"""Original main Items/Escape routing and field menu entry/exit frames.

PE/equipment/status/config/upgrade pages retain separate native boundaries.
The field block ends at its original return to the normal world frame.
"""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_inventory_use_oracle import fixture as use_fixture,RANGES as USE_RANGES
from pe_scripted_exit_oracle import words

RANGES=USE_RANGES+((0x91694,12),(0xBCDC8,0xC0),(0xB0E50,8))
ENTRIES=(0x80043DA4,0x8005E30C,0x80062FEC,0x800355F8)
RESULT_ENTRIES={0}
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for battle in (0,1):
    for enabled in (0,1,0x1F,0x1FF):
        for index in (-1,0,9):case(battle=battle,enabled=enabled,index=index)
for enabled,index in ((16,0),(31,4)):
    for unavailable in (0,1):case(battle=1,enabled=enabled,index=index,unavailable=unavailable)
for event in (0,2,32,64,66,0x10000,0x10040):
    for battle in (0,1):case(event=event,battle=battle)
for event_type,event in ((4,32),(1,64),(1,2),(1,0x4000)):
    for battle in (0,1):case(1,event_type=event_type,event=event,battle=battle)
for bank in (0,1):case(2,bank=bank)
for missing in (0,1,2):
    for pressed in (0,128):case(3,missing=missing,pressed=pressed)
for flags in (0,4,0x2000,0x2004):
    for overlay in (0,0x400,0x1000,0x2000,0x9000):case(3,flags=flags,overlay=overlay,pressed=128)
for event_type,event in ((4,32),(1,64),(1,2),(1,0x4000)):
    case(3,existing=1,event_type=event_type,event=event)
for bank in (0,1):case(3,bank=bank,pressed=128)

def fixture(exe,c):
    r,s,_=use_fixture(exe,dict(entry=0,battle=c.get('battle',0),bank=c.get('bank',0)))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def word(a):return struct.unpack_from('<I',r,a&0x1FFFFF)[0]
    def find(kind,id):
        p=word(0x9D154)
        while p:
            if word(p+32)==kind and word(p+36)==id:return p
            p=word(p)
        raise AssertionError((kind,id))
    execute(r,0x80062F9C)
    sw(0x9CEF0,c.get('enabled',0x1FF));sw(0x9D1A0,c.get('flags',c.get('battle',0)*2))
    sw(0x9D028,c.get('battle',0));sw(0xB0CD8,c.get('overlay',0));sw(0x9D1F4,c.get('pressed',0))
    sw(0x9CDAC,c.get('scroll_value',300));sw(0x9CE3C,c.get('unavailable',0))
    sw(0x9D120,0);sw(0x9D0E8,0);sw(0x9D0EC,0);sw(0x9D26C,0)
    window=0
    if c['entry']!=3 or c.get('existing'):
        execute(r,0x800438EC);window=find(1,0);node=find(2,0)
        sw(node+68,0);sw(node+72,c.get('index',0))
        if c['entry']==2:execute(r,0x80043DA4,(window,0x10000))
    if c.get('missing')==1:sw(0x9D254,0)
    if c.get('missing')==2:sw(0x15C000,0)
    if c['entry']==1 or c.get('existing'):
        q=0x80140500;sw(q,0);sw(q+4,c.get('event_type',4));sw(q+8,c.get('event',32))
        sw(0x9D0E0,q);sw(0x9D0E4,q);sw(0x9D0EC,1)
    sw(0x9D100,0x80160000)
    args=(window,c.get('event',0x10000)) if c['entry']==0 else ()
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def run(r,c,args):
    if c['entry']==3:
        word=lambda a:struct.unpack_from('<I',r,a&0x1FFFFF)[0]
        return execute(r,0x800355F8,stop_at=(0x800356D0,),
            initial_regs={3:word(0x9D1A0),4:word(0xB0CD8),16:0x800B0CD8},instruction_budget=900000)
    return execute(r,ENTRIES[c['entry']],args,instruction_budget=900000)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=run(r,c,args)
        result=regs[2] if c['entry'] in RESULT_ENTRIES else 0;h=fingerprint(r)
        cases.append((c['entry'],first,len(patches),args,result,h))
        print(k,c,hex(result),hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/inventory-entry-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_inventory_entry_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t INV11_inventory_entry_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2],result; uint64_t hash; } INV11_inventory_entry_cases[]={')
    for e,a,b,args,result,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{result:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_inventory_entry_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original main Items/Escape routing and field menu frames cases')

if __name__=='__main__':main()
