#!/usr/bin/env python3
"""Original inventory entry, command/stat panel construction and scalar getters."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_name_frame_oracle import fixture as frame_fixture
from pe_scripted_exit_oracle import words

RANGES=((0,128),(0x91694,12),(0x9CDB0,0x600),(0xA1870,0x1A00),
        (0xA76A4,0x50),(0xA8028,0x2C),(0xB0CD8,16),(0xC0DC0,0x1330),
        (0x140000,0x20000),(0x160000,0x4000),(0x170000,0x4000))
ENTRIES=(0x800438EC,0x800439D8,0x8004C594,0x8005C174,
         0x80033A20,0x8005B89C,0x8005257C)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for entry in (0,3):
    for battle in (0,1):
        for enabled in (0,0x3D,0x1FF):
            for existing in (0,1,2,3):case(entry,battle=battle,enabled=enabled,existing=existing)
for stat in (0,200,65535):case(1,stat=stat)
for existing in (0,1,2,3):case(2,existing=existing)
for style in (0,1,255):case(4,style=style)
for battle in (0,1,0xFFFFFFFF):case(5,battle=battle)
for flags in (0,2,4,0xFFFFFFFF):case(6,battle_flags=flags)
for hp in (18,65535):case(3,hp=hp)
for capacity in (0,49,50,255):
    for bonus in (0,2):case(3,capacity=capacity,bonus=bonus)

def fixture(exe,c):
    r,s,_=frame_fixture(exe,dict(entry=10))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    execute(r,0x80062F9C)
    if c.get('existing'):
        execute(r,0x80062D2C,((0,0,19,23)[c['existing']],0,0,int(c['existing']==3)))
    sw(0x9D028,c.get('battle',0));sw(0x9CEF0,c.get('enabled',0x3D))
    sw(0x9D1A0,c.get('battle_flags',0x4002));sb(0x9CE80,c.get('style',3))
    sw(0x9D018,c.get('bonus',0));sb(0xC0E0C,c.get('capacity',10))
    sw(0xC0E10,123456);sw(0x9D254,0)
    sw(0xA8038,0x158000-0xA8028)
    for table in range(7):
        sh(0xC0E28+table*2,c.get('stat',200)+table)
        for j in range(128):sw(0x158000+table*512+j*4,j*10)
    if 'hp' in c:
        sw(0x9D254,0x80148800);sw(0x148800,0x80148880)
        sh(0x14888C,c['hp']);sw(0x1488E8,0)
    args=(c.get('battle',0),) if c['entry']==3 else ()
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args)
        result=regs[2] if c['entry']>=4 else 0
        h=fingerprint(r);cases.append((c['entry'],first,len(patches),args,result,h))
        print(k,c,hex(result),hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/inventory-menu-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_inventory_menu_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t INV2_inventory_menu_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[1],result; uint64_t hash; } INV2_inventory_menu_cases[]={')
    for e,a,b,args,result,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{result:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_inventory_menu_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original inventory menu entry cases')

if __name__=='__main__':main()
