#!/usr/bin/env python3
"""Complete original inventory commands and weapon/armor application."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_inventory_draw_oracle import fixture as draw_fixture
from pe_equipment_oracle import fixture as equipment_fixture
from pe_scripted_exit_oracle import words

RANGES=((0,128),(0x9CD70,0x640),(0xA1870,0x1A00),(0xA76A4,0x50),
        (0xA8028,0x2C),(0xB0CB0,0x130),(0xBCF88,0x28),(0xC0DC0,0x1330),
        (0x140000,0x20000))
ENTRIES=(0x800512AC,0x800218D8,0x80021AF8,0x800209F0,0x800254BC,0x80051244,0x8005D970)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for command in range(-1,14):
    for pending in (0,1):case(command=command,pending=pending,battle=1)
for command in (0,1):
    for value in (0,0xFFFFFFFF,0x7FFFFFFF,0x80000000):case(command=command,value=value)
for command in (2,3):
    for battle in (0,1):
        for missing in (0,1,2,3):case(command=command,battle=battle,missing=missing)
    for ability in (0,1,8,12,13,15,16,20,31,32):case(command=command,ability=ability,battle=1)
for category in (0,1,4,5,7,8,18,19,22,255):case(command=5,category=category)
for command in (2,3,12):case(command=command,no_armor=1,battle=1)
for entry in (1,2):
    for pattern in (0,0x55555555,0xAAAAAAAA,0xFFFFFFFF):
        for overlap in (0,1,2):case(entry,pattern=pattern,overlap=overlap)
for category in range(9):
    for speed in (0,50,65535):case(3,category=category,speed=speed)
for entry in (0,4):
    for category in (0,1,4,5,7,8):case(entry,command=2 if entry==0 else 407,category=category,battle=0)
for command in (406,407,408,409):
    for battle in (0,1):case(4,command=command,battle=battle)
case(5)
for value in (-2147483648,-1,0,299,300,301,2147483647):case(6,value=value)

def fixture(exe,c):
    r,s,_=draw_fixture(exe,dict(entry=0,battle=c.get('battle',0)))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    eq=equipment_fixture(exe,c.get('ability',0))
    for a,n in ((0x923D0,6),(0xA8038,8),(0x150000,0x3000),(0xC0E28,14),(0xC0EAC,64)):
        put(a,eq[a:a+n])
    # Valid selected inventory and persistent weapon/armor records.
    sh(0xC0E48,256);sh(0xC0E4A,257);sb(0xC0E20,0);sb(0xC0E22,255 if c.get('no_armor') else 1)
    sb(0xC0E0C,10);sb(0xC0EB2,c.get('category',1));sb(0xC0ED2,9)
    sw(0x9D048,0x800C0E48);sw(0x9D050,10);sw(0x9D018,0)
    for a in (0x9D04C,0x9D054):sw(a,0)
    sw(0x9D058,0x8009D05C);sw(0x9D064,2)
    sw(0x9D1E0,0x800A76D8);sw(0x9D010,c.get('pending',0));sw(0x9CDAC,c.get('value',0))
    sw(0x15C168,0x8015D100);sw(0x15C16C,0x8015D140);sh(0x15C122,c.get('speed',50))
    for a in (0x15D100,0x15D140,0xA76D8):
        for i in range(6):sw(a+i*4,c.get('pattern',(i*0x234567+0xA5935612)&0xFFFFFFFF))
    sh(0x15D106,c.get('category',1));sh(0xA76DE,c.get('category',1))
    sw(0x15D000,c.get('value',0x800C0EAC))
    # Exercise real projection and an empty, valid field sound package.
    sw(0xB0E08,0x8015C800);sw(0x15C804,0x100);sw(0x15C92C,0)
    sw(0xBCFA4,0x8015C600);sw(0xBCFA8,0x8015C640);sw(0x15C640,256)
    put(0x15C600,bytes(32))
    for i in range(3):sh(0x15C600+i*8,4096)
    sw(0x15C61C,1024);sh(0xBCF94,160);sh(0xBCF96,112)
    sh(0xB0DD0,100);sh(0xB0DD2,1000);sb(0xB0DCE,20);sb(0xB0DCF,120)
    for a,v in ((0x15C02A,-120),(0x15C02E,32),(0x15C032,500)):sh(a,v)
    missing=c.get('missing',0)
    if missing==1:sw(0x9D254,0)
    if missing==2:sw(0x15C000,0)
    if missing==3:sw(0x9D1E0,0)
    if c.get('overlap'):
        sw(0x15C168 if c['entry']==1 else 0x15C16C,0x800A76D8+(c['overlap']-1)*4)
    args=((c.get('command',0),0x8015D000),(),(),(),(c.get('command',407),),(),())[c['entry']]
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        execute(r,ENTRIES[c['entry']],args,instruction_budget=750000)
        h=fingerprint(r);cases.append((c['entry'],first,len(patches),args,h))
        print(k,c,hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/inventory-commit-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_inventory_commit_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t INV4_inventory_commit_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2]; uint64_t hash; } INV4_inventory_commit_cases[]={')
    for e,a,b,args,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_inventory_commit_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original inventory command cases')

if __name__=='__main__':main()
