#!/usr/bin/env python3
"""Complete original medicine animation, command dispatch and escape calls."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute
from pe_recovery_item_oracle import fixture as recovery_fixture, RANGES as RECOVERY_RANGES
from pe_scripted_exit_oracle import words

RANGES = RECOVERY_RANGES + ((0xBE830, 360), (0x190000, 0x4000))
ENTRIES = (0x80022210, 0x80021DE0, 0x800255E4)
CASES = []
def case(entry=0, **kw):
    CASES.append(dict(entry=entry, **kw))

for item in range(6, 18):
    for phase in ('start', 'wait', 'finish'):
        case(item=item, phase=phase)
for next_command in (0, 1, 2, 3, 9, 386, 387, 406, 407, 408, 409, 65535):
    case(phase='finish', next_command=next_command)
for hp in (0, 1, 44, 45, 46, 32760):
    for item in (6, 9, 10):
        case(phase='finish', hp=hp, item=item)
for effect in (0, 1, 2):
    for used in (0, 1, 10, 11):
        case(phase='finish', effect=effect, used=used)
for flags in (1, 4, 16, 64, 128, 4096, 0x1055):
    case(phase='finish', item=17, flags=flags)
for idle in (0, 3, 4):
    case(phase='finish', idle=idle, next_command=9)
for index, count in ((0, 0), (1, 1), (2, 1), (255, 0)):
    case(1, index=index, count=count)
for cmd in range(4):
    case(1, cmd=cmd)
for phase in ('start', 'wait', 'finish'):
    for item in (6, 10, 11, 17):
        case(1, phase=phase, item=item)
for command in (407, 408):
    for index in (0, 1):
        case(1, command=command, index=index, count=3)
for entry in (1, 2):
    for blocked in (0, 1):
        for language in (0, 1):
            case(entry, command=409, blocked=blocked, language=language)
for level in (1, 6, 7, 8, 9, 127, 128, 255):
    for seed in (1, 3, 10):
        case(2, level=level, seed=seed)
for attempts in range(8):
    for hp in (1, 5, 45):
        case(2, attempts=attempts, hp=hp)
for enemy in (0, 1, 7, 10, 127, 128, 255):
    case(2, enemy_level=enemy)
for enemy_hp in (-1, 0, 1):
    for missing in (0, 1):
        case(2, enemy_hp=enemy_hp, missing=missing, blocked=1)
case(2, empty=1)

def fixture(exe, c):
    r, s, _ = recovery_fixture(exe, dict(c, entry=0, battle=0x82, phase=0))
    def put(a, data):
        a &= 0x1FFFFF
        r[a:a+len(data)] = data
        s[a:a+len(data)] = data
    def sw(a, v): put(a, struct.pack('<I', v & 0xFFFFFFFF))
    def sh(a, v): put(a, struct.pack('<H', v & 65535))
    def sb(a, v): put(a, bytes((v & 255,)))
    phase = c.get('phase', 'wait')
    flags = c.get('flags', 0) | (0x200000 if phase == 'start' else 0)
    flags |= c.get('attempts', 0) << 25
    sw(0x14404C, flags); sb(0x144004, c.get('level', 7))
    sb(0x144012, c.get('idle', 4))
    sb(0x14000E, c.get('cmd', 14)); sb(0x14000F, 7)
    sh(0x14001A, 7 if phase == 'finish' else 2)
    sh(0x140016, 2)
    sb(0x9D1D4, c.get('index', 0)); sb(0x9CE3C, c.get('count', 2))
    put(0xBE830, bytes(360))
    sw(0xBE830, 0x80140000); sh(0xBE834, c.get('command', c.get('item', 6)+3))
    sw(0xBE838, 0x80140000); sh(0xBE83C, c.get('next_command', c.get('command', 0)))
    sw(0x9D218, c.get('language', 0))
    sb(0xA5D60, c.get('enemy_level', 7)); sw(0xA5D6C, c.get('enemy_hp', 40))
    sw(0xA5E28, 0x40000 if c.get('blocked') else 0)
    sw(0xA5E48, 0)
    if c.get('missing'): sw(0x141000, 0)
    if c.get('empty'): sw(0x9D20C, 0)
    put(0x150000, bytes(11*0xA0C)); put(0x160000, bytes(11*0x10C))
    for i in range(11):
        sb(0x150000+i*0xA0C, 1 if i<c.get('used', 0) else 0)
        sb(0x150001+i*0xA0C, 255)
    put(0x190000, bytes(0x4000))
    effect = c.get('effect', 2)
    if effect:
        sw(0x190154, 0x80191000); sw(0x191004, 0x800D4620)
    sw(0xE1044, 0x80192000 if effect == 2 else 0)
    sw(0x192034, 0x80193000)
    for a, n in RANGES: s[a:a+n] = r[a:a+n]
    return r, s

def fingerprint(r):
    h = 14695981039346656037
    for a, n in RANGES:
        for b in r[a:a+n]: h = ((h ^ b)*1099511628211) & 0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe = (ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest() == '452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _, s = fixture(exe, CASES[0]); base = words(s)
    common = [(i*4, v) for i, v in enumerate(base) if v]
    patches, cases = [], []
    for k, c in enumerate(CASES):
        r, s = fixture(exe, c); first = len(patches)
        patches.extend((i*4, v) for i, (v, b) in enumerate(zip(words(s), base)) if v != b)
        regs = execute(r, ENTRIES[c['entry']], bios_seed=c.get('seed', 1))
        result = regs[2] if c['entry'] == 2 else 0
        h = fingerprint(r)
        cases.append((c['entry'], c.get('seed', 1), first, len(patches), result, h))
        print(k, c, hex(result), hex(h), flush=True)
        if '--dump' in sys.argv: (ROOT/f'pc_port/build/item-execution-oracle-{k}.bin').write_bytes(r)
    out = ['/* Generated by pe_item_execution_oracle.py --write-header. */']
    for name, rows in (('ranges', RANGES), ('common', common), ('patches', patches)):
        out.append(f'static const uint32_t INV14_item_execution_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a, b in rows); out.append('};')
    out.append('static const struct { unsigned entry,seed,first,end; uint32_t result; uint64_t hash; } INV14_item_execution_cases[]={')
    for e, seed, a, b, result, h in cases:
        out.append(f'    {{{e},{seed},{a},{b},0x{result:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:
        (ROOT/'pc_port/tests/retail_item_execution_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original medicine animation, command dispatch and escape cases')

if __name__ == '__main__': main()
