#!/usr/bin/env python3
"""Original linked actor clip selection/restart and recursive ticking graphs."""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute
RANGES=((0x9D20C,4),(0x9D254,4),(0xB0CD8,0x20),(0xB0E98,0x600),(0x150000,0x1800),(0x160000,0x200))
CASES=[]
for entry in (0x8001A680,0x8001A784,0x8001A4AC):
 for variant in range(64):
  for command in (5,7,0x10005):CASES.append((entry,variant,command))

def fixture(ex,c):
 entry,v,command=c;r=bytearray(0x200000);r[0x10000:0x10000+len(ex)-0x800]=ex[0x800:]
 for a,n in RANGES:r[a:a+n]=bytes(n)
 def sw(a,x):struct.pack_into('<I',r,a,x&0xFFFFFFFF)
 def sh(a,x):struct.pack_into('<H',r,a,x&65535)
 actors=[0x150000+i*0x400 for i in range(6)]
 sw(0x9D20C,0x80000000+actors[0])
 for i,a in enumerate(actors):
  sw(a+4,0x80000000+actors[i+1] if i<5 else 0)
  r[a+12]=i;r[a+13]=i+10;r[a+14]=5 if v&(1<<(i%3)) else 7;r[a+15]=8
  sw(a+20,((i+1)<<16)|0xABCD);sw(a+24,(i<<16)|0x1234);sw(a+28,0x18000)
  sh(a+18,i+1 if v&8 else 8)
  flags=8 | (0x100 if v&16 else 0) | (0x200 if v&8 else 0)
  if i in (0,1):flags|=0x100000
  if i in (1,2,3):flags|=0x200000
  if i==0 and v&32:flags|=0x800000
  sw(a+0x98,flags)
  if i in (1,3,5):sw(a+0x18C,0x80150000)
  if i==2:sw(a+0x18C,0x80150400)
  for cmd in (5,7):
   resource=0x160000+i*32+cmd*4
   sw(0xB0E98+i*192+cmd*4,0x80000000+resource)
   r[resource+2]=0 if v&32 else 10+i
 return r

def fingerprint(r):
 h=14695981039346656037
 for a,n in RANGES:
  for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
 return h

def main():
 ex=(ROOT/'build/disc1.candidate.exe').read_bytes();assert hashlib.sha1(ex).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
 common=None;patches=[];cases=[]
 for k,c in enumerate(CASES):
  r=fixture(ex,c);seed={a+i:struct.unpack_from('<I',r,a+i)[0] for a,n in RANGES for i in range(0,n,4)}
  if common is None:common={a:v for a,v in seed.items() if v}
  first=len(patches);patches.extend((a,v) for a,v in seed.items() if v!=common.get(a,0))
  actor=0x80150800 if c[0]==0x8001A4AC else 0x80150000
  execute(r,c[0],(actor,c[2]))
  cases.append((first,len(patches),c[0],actor,c[2],fingerprint(r)))
 out=['/* Generated by pe_linked_animation_oracle.py --write-header. */']
 for name,rows in (('ranges',RANGES),('common',sorted(common.items())),('patches',patches)):
  out.append(f'static const uint32_t LAN_{name}[][2]={{')
  out.extend(f'{{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
 out.append('static const struct { unsigned first,end; uint32_t entry,actor,command; uint64_t hash; } LAN_cases[]={')
 out.extend(f'{{{a},{b},0x{e:X}u,0x{actor:X}u,0x{cmd:X}u,UINT64_C(0x{h:016X})}},' for a,b,e,actor,cmd,h in cases);out.append('};')
 header='\n'.join(out)+'\n';path=ROOT/'pc_port/tests/retail_linked_animation_cases.h'
 if '--write-header' in sys.argv:path.write_text(header)
 else:assert path.read_text()==header
 print(f'PASS {len(cases)} original linked-actor animation graphs')
if __name__=='__main__':main()
