#!/usr/bin/env python3
"""Execute original EA205..207 with full channel lookup and command FIFO."""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute

RANGES=((0x9CDF0,4),(0x9D2F4,4),(0xB0CD8,0x120),(0xB8628,0x300),
        (0xBCD80,0x20),(0x140000,0x100))
CASES=[]
for key in (205,206,207):
 for slot in (0,1):
  for handle in (0,1,127,128,254,255):
   CASES.append(dict(key=key,slot=slot,handle=handle))
 for id in (128,255,256,0xFFFFFFFF,0xFFFFFF80,43):
  CASES.append(dict(key=key,id=id,handle=7,record_id=id&255))
 for duration in (0,1,0x7FFFFFFF,0x80000000,0xFFFFFFFF):
  CASES.append(dict(key=key,duration=duration,queue=17))

def fixture(exe,c):
 r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
 for a,n in RANGES:r[a:a+n]=bytes(n)
 def sw(a,v):struct.pack_into('<I',r,a,v&0xFFFFFFFF)
 sw(0x9CDF0,0x5FF);sw(0x9D2F4,c.get('queue',0));sw(0xB0CD8,0x40000400)
 r[0xB0DB4:0xB0DB8]=bytes((2,3,4,5))
 slot=c.get('slot',0);r[0xB0DB4+slot*2]=c.get('record_id',42)
 r[0xB0DB5+slot*2]=c.get('handle',17)
 # Seed untouched command parameters and script outputs to catch over-writes.
 for i in range(5):sw(0xBCD80+i*4,0xABCD0000+i)
 values=(c['key'],c.get('id',42),c.get('duration',0x12345678),0xFFFFFF9A,0x234,0xDEADBEEF)
 for i,v in enumerate(values):sw(0x140000+i*4,0x80140040+i*4);sw(0x140040+i*4,v)
 return r

def fingerprint(r):
 h=14695981039346656037
 for a,n in RANGES:
  for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
 return h

def main():
 exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
 assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
 common=None;patches=[];cases=[]
 for k,c in enumerate(CASES):
  r=fixture(exe,c);initial={a+i:struct.unpack_from('<I',r,a+i)[0] for a,n in RANGES for i in range(0,n,4)}
  if common is None:common={a:v for a,v in initial.items() if v}
  first=len(patches);patches.extend((a,v) for a,v in initial.items() if v!=common.get(a,0))
  regs=execute(r,0x80015DAC,(0x80140000,),instruction_budget=100000);assert regs[2]==1
  cases.append((first,len(patches),fingerprint(r)))
  print(k,c,hex(cases[-1][-1]),flush=True)
  if '--dump' in sys.argv:(ROOT/f'local/live/music-volume-oracle-{k}.bin').write_bytes(r)
 out=['/* Generated by pe_music_volume_oracle.py; full original instruction execution. */']
 for name,rows in (('ranges',RANGES),('common',sorted(common.items())),('patches',patches)):
  out.append(f'static const uint32_t SEW21_{name}[][2]={{')
  out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
 out.append('static const struct { unsigned first,end; uint64_t hash; } SEW21_cases[]={')
 out.extend(f'    {{{a},{b},UINT64_C(0x{h:016X})}},' for a,b,h in cases);out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_music_volume_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',len(cases),'original music volume cases')
if __name__=='__main__':main()
