#!/usr/bin/env python3
"""Complete original EA200/201/203/204 graphs that stay off 6CDA4."""
import hashlib, struct, sys
from pe_battle_hud_oracle import ROOT, execute
STOPS = (0x80086FF8, 0x8006CDA4)

RANGES = (
    (0x9CDF0, 4), (0x9CE00, 4), (0x9D180, 8), (0x9D2F4, 4), (0x9D300, 0x14),
    (0xB0CD8, 0x198), (0xB8628, 0x300), (0xBCD80, 0x20),
    (0x130000, 0x240), (0x140000, 0x100), (0x141000, 0x20),
)
CASES = []
for key in (200, 201, 203, 204):
    for kind in (0, 1, 2, 3):
        for block in (0, 1):
            CASES.append(dict(key=key, kind=kind, block=block))
    for ident in (0, 7, 42, 0xFFFFFF80):
        CASES.append(dict(key=key, kind=1, ident=ident, block=0))
    for volume in (0, 0x7F, 0x80, 0x12345678):
        CASES.append(dict(key=key, kind=1, volume=volume, block=1))


def fixture(exe, c):
    r = bytearray(0x200000)
    r[0x10000:0x10000 + len(exe) - 0x800] = exe[0x800:]
    for a, n in RANGES:
        r[a:a + n] = bytes(n)

    def sw(a, v):
        struct.pack_into('<I', r, a & 0x1FFFFF, v & 0xFFFFFFFF)

    def sh(a, v):
        struct.pack_into('<H', r, a & 0x1FFFFF, v & 0xFFFF)

    sw(0x9CDF0, 0x5FF)
    sw(0x9CE00, 0x80140080)
    sw(0x9D2F4, 0)
    sw(0x9D300, 0x801400C0)
    sw(0x1400C0 + 0x10, 0)
    sw(0xB0E64, 0x80130000)
    sw(0x130004, 0x40)
    sw(0x130070, (2 << 22) | 0x100)
    sw(0x130100, 0xAB00001D)
    sw(0x130104, 0xCD000200)
    sh(0x130108, 5)
    sh(0x13010A, 7)
    sw(0x13010C, 0xAB000011)
    sw(0x130110, 0xCD000220)
    sh(0x130114, 9)
    sh(0x130116, 200)
    sw(0xB0E00, 0x80141000)
    sw(0xB0E04, 0x80141100)
    sw(0xB0CD8, 0x40000400)
    r[0xB0DB2:0xB0DB8] = bytes((0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF))
    kind = c['kind']
    ident = c.get('ident', 99 if kind == 0 else 7)
    if kind in (1, 2, 3):
        slot = 1 if kind == 3 else 0
        r[0xB0DB4 + slot * 2] = ident & 255
        r[0xB0DB5 + slot * 2] = 17
        r[0xB0DB2 + slot] = 5
        if kind == 2:
            sw(0xB0CD8, 0x40000400 | (0x40 << slot))
    for i in range(5):
        sw(0xBCD80 + i * 4, 0xABCD0000 + i)
    values = (
        c['key'], ident, c.get('volume', 0x12345678) if c['key'] == 203 else c['block'],
        c['block'], 0x234, 0xDEADBEEF,
    )
    for i, v in enumerate(values):
        sw(0x140000 + i * 4, 0x80140040 + i * 4)
        sw(0x140040 + i * 4, v)
    return r


def fingerprint(r):
    h = 14695981039346656037
    for a, n in RANGES:
        for b in r[a:a + n]:
            h = ((h ^ b) * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return h


def main():
    exe = (ROOT / 'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest() == '452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    common = None
    patches = []
    cases = []
    for k, c in enumerate(CASES):
        r = fixture(exe, c)
        initial = {a + i: struct.unpack_from('<I', r, a + i)[0]
                   for a, n in RANGES for i in range(0, n, 4)}
        if common is None:
            common = {a: v for a, v in initial.items() if v}
        first = len(patches)
        patches.extend((a, v) for a, v in initial.items() if v != common.get(a, 0))
        regs = execute(r, 0x80015DAC, (0x80140000,), stop_at=STOPS,
                       instruction_budget=200000)
        assert not (0x8006D2B8 <= regs[31] < 0x8006D60C), (k, c, 'entered CD/SPU load')
        assert regs[2] in (0, 1), (k, c, hex(regs[2]))
        cases.append((first, len(patches), fingerprint(r), regs[2]))
        print(k, c, hex(cases[-1][2]), cases[-1][3], flush=True)
        if '--dump' in sys.argv and k == 0:
            (ROOT / 'local/live/music-start-oracle-0.bin').write_bytes(r)
    out = ['/* Generated by pe_music_start_oracle.py; full original instruction execution. */']
    for name, rows in (('ranges', RANGES), ('common', sorted(common.items())),
                       ('patches', patches)):
        out.append(f'static const uint32_t DAY1_music_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a, b in rows)
        out.append('};')
    out.append('static const struct { unsigned first,end; uint64_t hash; uint32_t result; } DAY1_music_cases[]={')
    out.extend(f'    {{{a},{b},UINT64_C(0x{h:016X}),0x{res:X}u}},' for a, b, h, res in cases)
    out.append('};')
    if '--write-header' in sys.argv:
        (ROOT / 'pc_port/tests/retail_music_start_cases.h').write_text('\n'.join(out) + '\n')
    print('PASS:', len(cases), 'original music start/stop cases')


if __name__ == '__main__':
    main()
