#!/usr/bin/env python3
"""Execute original menu resize, recursive release and cursor-save graphs."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute
from pe_menu_node_oracle import fixture as node_fixture, RANGES, fingerprint
from pe_scripted_exit_oracle import words

ENTRIES=(0x800647D0,0x8006269C,0x80062F3C,0x80064E90,0x80064A54)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for columns in (1,2,3):
    for rows in (3,7):
        for items in (0,1,3,4,5,9,27):case(columns=columns,rows=rows,items=items)
for owner_kind in (0,2):case(owner_kind=owner_kind,items=1)
case(items=-1);case(items=0x7FFFFFFF)
for target in ('parent','list','sibling','scroll','null','missing'):
    for restore in (0,1):case(1,target=target,restore=restore,rows=7)
for ident in (0,23,5,0xFFFFFFFF):case(2,id=ident)
case(3,rows=7)
for ident in (-1,0,71,72):
    for restore in (0,1):
        for flags in (0,32):case(4,id=ident,restore=restore,list_flags=flags)

def fixture(exe,c):
    r,s,_=node_fixture(exe,dict(entry=0))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def word(a):return struct.unpack_from('<I',r,a&0x1FFFFF)[0]
    for i,v in enumerate((12,20,c.get('columns',2),4,c.get('rows',3),16,8,c.get('list_flags',0))):sw(0x92888+23*32+i*4,v)
    parent=execute(r,0x80062D2C,(23,0,0,0))[2]
    node=execute(r,0x8006322C,(23,parent,parent))[2]
    sibling=execute(r,0x80062D2C,(23,parent,0,0))[2]
    sw(parent+32,c.get('owner_kind',1))
    sw(sibling+8,node);sw(sibling+12,parent)
    sw(node+120,sibling);sw(node+124,parent)
    sw(node+68,1);sw(node+72,9);sw(node+92,7)
    sw(0x9D15C,node);sw(0x9D16C,c.get('restore',0))
    scroll=word(node+128)
    if c['entry']==4:sw(node+112,c.get('id',23))
    target=dict(parent=parent,list=node,sibling=sibling,scroll=scroll,null=0,missing=0x80140800)[c.get('target','list')]
    args=((node,c.get('items',7)),(target,),(c.get('id',23),),(scroll,),(node,))[c['entry']]
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,tuple(a&0xFFFFFFFF for a in args)

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        execute(r,ENTRIES[c['entry']],args)
        h=fingerprint(r);cases.append((c['entry'],first,len(patches),args,h))
        print(k,c,hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/menu-lifecycle-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_menu_lifecycle_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t INV1_menu_lifecycle_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2]; uint64_t hash; } INV1_menu_lifecycle_cases[]={')
    for e,a,b,args,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args)
        out.append(f'    {{{e},{a},{b},{{{params}}},UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_menu_lifecycle_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original menu lifecycle cases')

if __name__=='__main__':main()
