#!/usr/bin/env python3
"""Original menu glyph/icon packets, drawing stack and field packet banks."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_name_input_oracle import fixture as name_fixture
from pe_scripted_exit_oracle import words

RANGES=((0,128),(0x9CDB0,0x600),(0xA2180,0x130),(0xA8028,0x2C),
        (0x140000,0x10000),(0x160000,0x4000),(0x170000,0x4000))
ENTRIES=(0x8005EED4,0x8005EB64,0x8005F1A0,0x8005F27C,0x8005F5B8,
         0x8005E8C4,0x8005E914,0x8005E8A4,0x80050F10,0x80050F64,
         0x80050FB8,0x8005100C,0x8005E6F0)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for character in (*range(17),20,21,99,249,250,251,252,253,254,255,256,511):case(character=character)
for prefix in (1,2,3,4):
    for character in (0,1,20,100,249,250,251):case(prefix=prefix,character=character)
for dim in (0,1,2):
    for x,y in ((0,0),(-7,-4),(65533,65534)):
        case(dim=dim,x=x,y=y,character=20)
        case(1,dim=dim,x=x,y=y,index=119)
for offset in (0x3FB0,0x3FD4,0x3FD8,0x3FDC,0x3FE0,0x3FE8,0x3FF0,0x3FF8,0x4000):
    case(character=20,offset=offset);case(1,index=98,offset=offset)
for text in ('','104830','0001090f10','fa10fb00fc11fd12fe13','1011fb','fafa10',
             'fb00fb01fbecfcedfdf9fef9'):
    for entry in (2,3):case(entry,text=text)
for entry in (3,):case(entry,null=1)
for index in (0,30,119,120):case(4,index=index)
for stack in (0x800A2270,0x800A2278,0x800A22A8,0x800A22B0):
    for entry in (5,6):case(entry,stack=stack)
for x,y in ((12,18),(-12,-18),(0x7FFFFFFF,0x80000000)):case(7,x=x,y=y)
for entry in (8,9,10,11):
    for index in (0,1,2):case(entry,index=index)
for bank in (0,1):case(12,bank=bank)

def fixture(exe,c):
    r,s,_=name_fixture(exe,dict(c,entry=0))
    def put(a,b):r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def word(a):return struct.unpack_from('<I',r,a&0x1FFFFF)[0]
    put(0,bytes((i*7+3)&255 for i in range(128)))
    put(0x160000,bytes((i*11+9)&255 for i in range(0x4000)))
    put(0x170000,bytes((i*13+7)&255 for i in range(0x4000)))
    put(0xA2270,bytes((i*19+2)&255 for i in range(64)))
    sw(0xA8050,0x148000-0xA8028);put(0x148000,bytes(((i%12)<<4)|(i%4) for i in range(0x800)))
    sw(0xA8030,0x148800-0xA8028)
    for i in range(200):
        put(0x148800+i*8,struct.pack('<BBHBBBB',i%240,(i*7)%240,0x800+i,
                                   12+i%20,8+i%30,i&3,0xA7))
    sw(0x9D100,0x80160000+c.get('offset',0));sw(0x9D104,0x80160000);sw(0x9D11C,0x80170004)
    sw(0x9D0D8,c.get('prefix',0));sw(0x9D10C,c.get('dim',0))
    sw(0x9D110,0xAB80D0F0);sw(0x9D114,0x00406878)
    sw(0x9D124,c.get('x',10));sw(0x9D128,c.get('y',20));sw(0x9D12C,c.get('stack',0x800A2270))
    sw(0x9CF54,0x80149800);put(0x149800,bytes.fromhex(c.get('text','104830'))+b'\xff')
    sw(0x9CEF4,word(0x9D15C));sw(0x9CDDC,c.get('bank',0));sw(0x9D120,0)
    for bank in (0,1):
        sw(0xA2180+bank*120+112,0x80170000+bank*0x1000)
        sw(0xA2180+bank*120+116,0x80160000+bank*0x1000)
    index=c.get('index',0);text=0 if c.get('null') else 0x80149800
    args=((c.get('character',20),),(index,),(text,),(text,),(index,),(),(),
          (c.get('x',0),c.get('y',0)),(index,),(index,),(index,),(index,),())[c['entry']]
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args);result=regs[2] if c['entry']==2 else 0
        cases.append((c['entry'],first,len(patches),args,result,fingerprint(r)))
        print(k,c,hex(result),hex(fingerprint(r)),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/menu-text-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_menu_text_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t NAM5_menu_text_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2],result; uint64_t hash; } NAM5_menu_text_cases[]={')
    for e,a,b,args,v,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{v:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_menu_text_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} complete original menu text cases')

if __name__=='__main__':main()
