#!/usr/bin/env python3
"""Run original menu allocation, modal insertion and cursor call graphs."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_scripted_exit_oracle import words

RANGES=((0x9D154,32),(0xA22E0,0xE80),(0x140000,0x1000))
ENTRIES=(0x80062D2C,0x8006322C,0x80062A34,0x800631DC,0x80064AC0,
         0x80064D08,0x8005DA8C,0x8005DAB4)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for modal in (0,1,2):
    for active in (0,1,2,3):
        for parent in (0,1):case(modal=modal,active=active,parent=parent)
for x,y in ((0,0),(0,1),(17,29)):
    for width,height in ((80,24),(81,25)):case(x=x,y=y,width=width,height=height)
for rows in (1,4,9):
    for restore in (0,1):
        for parent in (0,1):case(1,rows=rows,restore=restore,parent=parent,active=2)
for active in (0,1,2,3):
    for kind in (1,2,3):case(2,active=active,kind=kind)
for active in (0,1,2,3):case(3,active=active)
for enabled in (0,1):
    for flags in (0,32):
        for row in (-1,2,9):case(4,restore=enabled,list_flags=flags,row=row,last=1)
case(4,id=-1);case(4,null=1)
for parent in (0,1):case(5,parent=parent,active=2)
for entry in (6,7):
    for ident in (0,23,64,65,0xFFFFFFFF):case(entry,id=ident)

def fixture(exe,c):
    r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    s=bytearray(0x200000)
    def put(a,b):r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sb(a,v):put(a,bytes((v&255,)))
    for a,n in RANGES:put(a,bytes(n))
    put(0xA22E0,bytes((i*37+19)&255 for i in range(0xD80)))
    for i in range(24):sw(0xA22E0+i*144,0x800A22E0+(i+1)*144 if i<23 else 0)
    sw(0x9D158,0x800A22E0);sw(0x9D16C,c.get('restore',0))
    count=c.get('active',0);sw(0x9D154,0x80140000 if count else 0)
    for i in range(count):
        a=0x140000+i*144
        sw(a,0x80140000+(i+1)*144 if i+1<count else 0)
        sw(a+32,1);sw(a+36,23 if i==count-1 else 5);sw(a+68,1 if i==1 else 0)
    node=0x140500;sw(node+4,0x80140000);sw(node+56,4);sw(node+88,c.get('rows',4))
    sw(node+100,c.get('list_flags',0));sw(node+104,c.get('last',0));sw(node+112,c.get('id',23))
    if c.get('parent'):sw(0x140008,0x80000000+node)
    spec=0x92478+23*16
    for i,v in enumerate((c.get('x',0),c.get('y',0),c.get('width',80),c.get('height',24))):sw(spec+i*4,v)
    spec=0x92888+23*32
    for i,v in enumerate((12,20,2,4,c.get('rows',4),16,8,c.get('list_flags',0))):sw(spec+i*4,v)
    sb(0xA3060+23*4,1);sb(0xA3061+23*4,c.get('row',2));sb(0xA3062+23*4,-1)
    parent=0x80140000 if c.get('parent') else 0
    args=((23,0x80140800,parent,c.get('modal',0)),(23,0x80140800,parent),
          (c.get('kind',1),23),(),(0 if c.get('null') else 0x80000000+node,),
          (0x80000000+node,),(c.get('id',23),),(c.get('id',23),))[c['entry']]
    return r,s,tuple(a&0xFFFFFFFF for a in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args)
        result=0 if c['entry'] in (4,5) else regs[2]
        cases.append((c['entry'],first,len(patches),args,result,fingerprint(r)))
        print(k,c,hex(result),hex(fingerprint(r)),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/menu-node-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_menu_node_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t NAM1_menu_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[4],result; uint64_t hash; } NAM1_menu_cases[]={')
    for e,a,b,args,v,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{v:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_menu_node_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} complete original menu node call graphs')

if __name__=='__main__':main()
