#!/usr/bin/env python3
"""Original naming lists, scroll/clipping, and nested menu drawing order."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_menu_window_oracle import fixture as window_fixture
from pe_scripted_exit_oracle import words

RANGES=((0,128),(0x9CDB0,0x600),(0xA2180,0xF30),(0xA8028,0x2C),(0xC0E44,4),
        (0x140000,0x10000),(0x160000,0x4000),(0x170000,0x4000))
ENTRIES=(0x800634D4,0x8006374C,0x80065260,0x800638D8,0x800500A8,
         0x8005010C,0x80050178,0x800501C8,0x80062830,0x80062FEC)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for row in (-1,0,1,3,8):
    for dim in (0,1):
        for frame in (0,8):case(row=row,dim=dim,frame=frame,top=1,saved=(1,1))
for draw in (0,0x80050F10,0x80050F64,0x80050FB8,0x8005100C):case(draw=draw,row=0,columns=1)
for bank in (0,1):
    for group in (17,23,24,25):case(1,bank=bank,group=group)
for visible,total,top,scroll in ((3,9,0,0),(3,9,3,0),(3,9,3,8),(3,9,3,-8),
                               (9,9,0,0),(10,9,0,0),(1,255,100,4)):
    case(2,visible=visible,total=total,top=top,scroll=scroll)
case(2,null=1)
for scroll in (-16,-8,-4,0,4,8,16):
    for selected in ((0,0),(2,4),(-1,3)):
        case(3,scroll=scroll,visible=3,top=3,selected=selected,pages=1)
for dim in (0,1):
    for focused in (0,1):
        for pad in (0,0x20000000):case(3,dim=dim,focused=focused,pad=pad,armed=1,frame=31)
for entry in (4,5,6,7):
    for alternate in ((0,) if entry==5 else (0,1)):
        for focused in (0,1):case(entry,alternate=alternate,focused=focused,frame=48)
for entry in (8,9):
    for group in (17,23,24,25):
        for modal in (0,1):case(entry,group=group,modal=modal,frame=16)
for entry in (0,1,3,4,5,6,7):case(entry,offset=0x3FE0)

def fixture(exe,c):
    r,s,_=window_fixture(exe,dict(c,entry=0))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def word(a):return struct.unpack_from('<I',r,a&0x1FFFFF)[0]
    def find(kind,id):
        p=word(0x9D154)
        while p:
            if word(p+32)==kind and word(p+36)==id:return p
            p=word(p)
        raise AssertionError((kind,id))
    group={5:23,6:24,7:25}.get(c['entry'],c.get('group',17))
    node=find(2,group);parent=find(1,23 if group in (23,24,25) else group)
    sw(0x9D108,c.get('bank',0));sw(parent+60,c.get('dim',0))
    sw(0x9D15C,node if c.get('focused',1) else 0)
    selected=c.get('selected',(0,0));sw(node+68,selected[0]);sw(node+72,selected[1])
    for key,off in (('top',92),('scroll',96),('visible',56),('total',88),('columns',52)):
        if key in c:sw(node+off,c[key])
    if 'saved' in c:sw(node+76,c['saved'][0]);sw(node+80,c['saved'][1])
    scrollbar=0x80149D00;sw(scrollbar+52,node)
    if c.get('pages'):sw(node+128,scrollbar)
    # Constructor's name-bar callback is tested separately once restored;
    # retain that window with an empty body to isolate nested draw ordering.
    sw(find(1,26)+48,0)
    if c.get('modal'):sw(parent+68,1)
    # Enough deterministic glyphs for an entire 11 by 9 page.
    put(0x149800,bytes(16+i%90 for i in range(128)))
    args=((node,c.get('draw',0x80050F10),c.get('row',0),c.get('dim',0)),(node,),
          (0 if c.get('null') else scrollbar,),(node,c.get('draw',0x80050F10)),
          (node,),(node,),(node,),(node,),(parent,),())[c['entry']]
    for a,n in RANGES:s[a&0x1FFFFF:(a&0x1FFFFF)+n]=r[a&0x1FFFFF:(a&0x1FFFFF)+n]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        execute(r,ENTRIES[c['entry']],args)
        cases.append((c['entry'],first,len(patches),args,fingerprint(r),c.get('frame',0)))
        print(k,c,hex(fingerprint(r)),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/menu-list-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_menu_list_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t NAM7_menu_list_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[4]; uint64_t hash; uint32_t frame; } NAM7_menu_list_cases[]={')
    for e,a,b,args,h,frame in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},UINT64_C(0x{h:016X}),{frame}u}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_menu_list_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} complete original menu list cases')

if __name__=='__main__':main()
