#!/usr/bin/env python3
"""Original beveled menu windows, selection pulse and SDK clip packets."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_menu_text_oracle import fixture as text_fixture
from pe_scripted_exit_oracle import words

RANGES=((0,128),(0x9CDB0,0x600),(0xA2180,0x160),(0xA8028,0x2C),(0xC0E44,4),
        (0x140000,0x10000),(0x160000,0x4000),(0x170000,0x4000))
ENTRIES=(0x8006153C,0x80061878,0x80061C34,0x80062090,0x800622BC,0x80075B4C,0x80075B84)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for second in (1,2,0x81,0x82):
    for thickness in (-4,-2,0,2,4):
        for shade in (0,1):case(second=second,thickness=thickness,shade=shade)
for shade in (0,1):case(1,shade=shade)
for shape in (0,0x80092354,0x80092380,0x800923A0):
    for textured in (0,1):
        for x,y in ((0,0),(-3,-7),(150,140)):case(2,shape=shape,textured=textured,x=x,y=y)
for pulse in (0,1):
    for frame in (0,1,8,16,31,32,33,48,63,64):case(3,pulse=pulse,frame=frame)
for pressed in (0,1):
    for focused in (0,1):
        for color in (0,0x123456,0x808080,0xFFFFFFFF):case(4,pressed=pressed,focused=focused,color=color,frame=17)
for entry in (0,1,2,3,4):
    for offset in (0x3F80,0x3FD8,0x3FF0,0x4000):case(entry,offset=offset,textured=1,pulse=1)
for entry in (5,6):
    for rect in ((0,0,0,0),(0,0,32,32),(0,224,320,224),(-20,-30,100,80),
                 (1020,510,20,40),(32767,-32768,-1,-2),(8,16,17,33)):
        case(entry,rect=rect)
case(5,null=1)

def fixture(exe,c):
    r,s,_=text_fixture(exe,dict(c,entry=0))
    def put(a,b):r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    put(0x930A8,exe[0x930A8-0x10000+0x800:0x930A8-0x10000+0x800+32])
    for i,(x,y) in enumerate(((10,20),(110,20),(10,80),(110,80))):
        sh(0xA22B0+i*4,y);sh(0xA22B2+i*4,x)
    sw(0x9D14C,0x123456);sw(0x9D150,0x2468AC);sw(0x9D130,c.get('color',0));sw(0xC0E44,0x315273)
    sh(0x95750,1024);sh(0x95752,512);sw(0x956AC,c.get('frame',0))
    # Read-only VSync(-1) executes its complete original RAM-query path.
    sw(0x94574,0x801497E0);sw(0x94578,0x801497E4);sw(0x9457C,0)
    put(0x149C00,struct.pack('<4h',*c.get('rect',(0,0,32,32))))
    width=c.get('width',100);height=c.get('height',60);shade=c.get('shade',0)
    args=((0,c.get('second',1),c.get('thickness',2),shade),(0x800930A8,shade),
          (width,height,c.get('shape',0),c.get('textured',0)),(width,height,c.get('pulse',0)),
          (width,height,c.get('pressed',0),c.get('focused',0)),
          (0x80160000,0 if c.get('null') else 0x80149C00),(0x80160000,0x80149C00))[c['entry']]
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        execute(r,ENTRIES[c['entry']],args)
        cases.append((c['entry'],first,len(patches),args,fingerprint(r),c.get('frame',0)))
        print(k,c,hex(fingerprint(r)),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/menu-window-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_menu_window_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t NAM6_menu_window_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[4]; uint64_t hash; uint32_t frame; } NAM6_menu_window_cases[]={')
    for e,a,b,args,h,frame in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},UINT64_C(0x{h:016X}),{frame}u}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_menu_window_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} complete original menu window cases')

if __name__=='__main__':main()
