#!/usr/bin/env python3
"""Original name buffer editing and name-entry grid construction."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_menu_node_oracle import fixture as menu_fixture
from pe_scripted_exit_oracle import words

RANGES=((0x91694,12),(0x9D004,4),(0x9D0C0,12),(0x9D154,32),(0xA22E0,0xD80),
        (0xB0CD8,4),(0xC0DC0,0x1310),(0x140000,0x1000))
ENTRIES=(0x8005BD10,0x8005BD94,0x8005BE1C,0x8005BF08,0x8005BCB0,
         0x8005BEDC,0x8005BEE8,0x80062A20,0x80063428,0x80052FCC,0x8004DD64)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
names=('', '10', '104830', '1011121314151617','fa10fb11fc12fd13fe14151617',
       '10111213141516fd17','0f0f0f','fa10','fafa10')
for entry in (0,1,3):
    for name in names:case(entry,name=name)
for character in (0,15,249,250,254,255,256,32767):case(character=character)
for limit in (-1,0,1,2,8):
    for entry in (0,1,3):case(entry,limit=limit,name='104830')
for record in (0,1,2):case(2,record=record)
for entry in (4,6):
    for alternate in (0,1,-1,4):case(entry,alternate=alternate)
case(5)
for index in range(4):case(7,index=index)
for column,row in ((-1,0),(0,-1),(0,0),(1,3),(2,7),(0x40000001,7)):
    case(8,column=column,row=row)
case(8,null=1)
for record in (0,1,2):case(9,record=record)
for alternate in (0,1):
    for record in (0,1,2):
        for restore in (0,1):case(10,alternate=alternate,record=record,restore=restore)

def fixture(exe,c):
    r,s,_=menu_fixture(exe,dict(c,entry=0,active=0))
    def put(a,b):r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    for a,n in RANGES:put(a,bytes(n))
    for a,n in ((0x92354,0xD54),):put(a,exe[a-0x10000+0x800:a-0x10000+0x800+n])
    for i in range(24):sw(0xA22E0+i*144,0x800A22E0+(i+1)*144 if i<23 else 0)
    sw(0x9D158,0x800A22E0);sw(0x9D16C,c.get('restore',0))
    for i in range(128):
        p=0xC0EAC+i*32
        sb(p+5,0x13 if i&1 else 0x55);sb(p+6,9 if i%3 else 1);sb(p+4,1)
    record=0 if not c.get('record') else 0x800C0EAC+(0 if c['record']==1 else 32)
    sw(0x9D0C0,0x800C0DE0);sw(0x9D0C4,c.get('limit',8));sw(0x9D0C8,record)
    put(0xC0DDE,b'\x11\x22'+bytes.fromhex(c.get('name','104830'))+b'\xff')
    sw(0x9D218,c.get('alternate',0));sw(0x9D048,0x80140400);sw(0x9D050,2)
    sh(0x140400,0x100);sh(0x140402,0x101)
    # Two original archive string tables with default Aya and item names.
    sw(0xA802C,0x140800-0xA8028);sw(0x140804,0x100);sw(0x140808,0x200)
    sh(0x140900,31);sh(0x14093E,0x60);put(0x140960,b'\x10\x48\x30\xff')
    sh(0x140A00,1);sh(0x140A02,0x10);put(0x140A10,b'\x40\x41\x42\x43\xff')
    node=0x80140200
    for i in range(4):sw(0x140208+i*4,0x80140400+i*16)
    sw(0x140234,3);sw(0x140244,c.get('column',1));sw(0x140248,c.get('row',2))
    args=((c.get('character',0x12),),(),(),(),(),(),(),(node,c.get('index',0)),
          (0 if c.get('null') else node,),(record,),(-1 if not record else c['record']-1,))[c['entry']]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args)
        result=0 if c['entry'] in (0,2,9,10) else regs[2]
        cases.append((c['entry'],first,len(patches),args,result,fingerprint(r)))
        print(k,c,hex(result),hex(fingerprint(r)),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/name-entry-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_name_entry_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t NAM2_name_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2],result; uint64_t hash; } NAM2_name_cases[]={')
    for e,a,b,args,v,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{v:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_name_entry_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} complete original name entry cases')

if __name__=='__main__':main()
