#!/usr/bin/env python3
"""Original PE menu construction, drawing, confirmation and reservation."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_pe_cost_oracle import fixture as cost_fixture,RANGES as COST_RANGES
from pe_scripted_exit_oracle import words
RANGES=COST_RANGES
ENTRIES=(0x80055610,0x8006346C,0x80046ABC,0x80046B58,0x80046C20,0x80057B70,
         0x80046DBC,0x8004FC3C,0x80050B48,0x80061044,0x8004FC80,0x800634D4,
         0x80062FEC,0x80044E98,0x80043DA4,0x8005E30C)
RESULT_ENTRIES={1,3,7,13,14}
CASES=[]
def case(entry=12,**kw):CASES.append(dict(entry=entry,**kw))
for known in (0,1,2,0x15555,0xFFFFF,0xFFF00000,0xFFFFFFFF):case(0,known=known);case(2,known=known)
for index in (-1,0,1,19,31,32):
    for bits in (0,1,0xFFFFFFFF):case(1,index=index,bits=bits)
for battle in (0,1):
    for entry in (2,3,4,5,6,7,8,10,12,13,14,15):case(entry,battle=battle)
for entry in (3,13,15):
    for event in (0,64,0x10000):
        for pe in (0,300):case(entry,event=event,pe=pe)
for confirmed in (0,1):
    for battle in (0,1):case(6,confirmed=confirmed,battle=battle)
for ability in range(20):case(5,ability=ability)
for value in (-2147483648,-1,0,1,200,400,2147483647):
    for maximum in (-1,0,400):
        for battle in (0,1):case(9,value=value,maximum=maximum,battle=battle)
for row in (-1,0,1,3,31,32):
    for dim in (0,1):case(11,row=row,dim=dim)
for known in (0,1,0xFFFFF):
    for pe in (0,300):case(12,known=known,pe=pe)
for entry in (9,10,12):case(entry,offset=0x3FE0)

def fixture(exe,c):
    r,s,_=cost_fixture(exe,dict(c,entry=2))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def word(a):return struct.unpack_from('<I',r,a&0x1FFFFF)[0]
    def find(kind,id):
        p=word(0x9D154)
        while p:
            if word(p+32)==kind and word(p+36)==id:return p
            p=word(p)
        raise AssertionError((kind,id))
    put(0x10760,r[0x10760:0x10788])
    # Use the actual main-menu owner and no leftover item/action windows.
    execute(r,0x80062F9C);sw(0x9CEF0,0x3F);execute(r,0x800438EC)
    main=find(2,0);sw(main+72,1);sw(main+68,0)
    sw(0xC0E24,c.get('known',1));execute(r,0x80055610)
    window=find(1,0);node=main
    if c['entry'] not in (0,2,14,15):
        execute(r,0x80046ABC,(main,));window=find(1,8);node=find(2,8)
        # Enabled bits are normally refreshed by the first rendered list.
        sw(node+116,c.get('bits',0xFFFFFFFF));sw(node+68,0);sw(node+72,c.get('index',0))
    if c['entry'] in (6,13):
        execute(r,0x80046C20);window=find(1,41);node=find(2,41)
        sw(node+68,c.get('selection',0));sw(node+72,0)
        if c['entry']==6:execute(r,0x80062F1C,(window,))
    if c['entry']==1:sw(node+72,c.get('index',0))
    if c['entry']==15:
        q=0x80140500;sw(q,0);sw(q+4,1);sw(q+8,c.get('event',0x10000))
        sw(0x9D0E0,q);sw(0x9D0E4,q);sw(0x9D0EC,1);sw(0x9D0E8,0)
    sw(0x9D100,0x80160000+c.get('offset',0));sw(0x9D104,0x80160000)
    ability=c.get('ability',0);event=c.get('event',0x10000)
    args=((),(node,),(main,),(window,event),(),(ability,),
          (window,c.get('confirmed',1)),(c.get('index',0),),(c.get('index',0),),
          (c.get('value',200),c.get('maximum',400)),(node,),
          (node,0x80050B48,c.get('row',0),c.get('dim',0)),(),(window,event),
          (window,event),())[c['entry']]
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args)
        result=regs[2] if c['entry'] in RESULT_ENTRIES else 0;h=fingerprint(r)
        cases.append((c['entry'],first,len(patches),args,result,h))
        print(k,c,hex(result),hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/pe-menu-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_pe_menu_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t INV19_pe_menu_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[4],result; uint64_t hash; } INV19_pe_menu_cases[]={')
    for e,a,b,args,result,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{result:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_pe_menu_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original PE menu cases')

if __name__=='__main__':main()
