#!/usr/bin/env python3
"""Original PE menu reservations, cost discounts and enabled choices."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_inventory_use_oracle import fixture as use_fixture,RANGES as USE_RANGES
from pe_scripted_exit_oracle import words
RANGES=USE_RANGES+((0x178000,80),)
ENTRIES=(0x800515F8,0x800579D4,0x8004324C,0x800524D0,0x8005DC10)
CASES=[]
def case(entry=2,**kw):CASES.append(dict(entry=entry,**kw))
for pe in (-32768,-1,0,1,300,32767):
    for count in (0,1,4):case(0,pe=pe,history=count)
for maximum in (-32768,-1,0,400,32767):case(0,maximum=maximum)
for missing in (0,1,2):
    for output in (0,0x8015FA40,0x15FA40):case(0,missing=missing,output=output)
for cost in (0,1,400,0x80000000,0xFFFFFFFF):case(0,history=2,reservation=cost)
for ability in range(20):
    for discount in (0,1):case(1,ability=ability,discount=discount)
for ability in range(20):
    for battle in (0,1):
        for pe in (0,30,300):case(ability=ability,battle=battle,pe=pe)
for ability in (0,1,2,5,6,7,8,10,18,19):
    case(ability=ability,no_targets=1);case(ability=ability,hp=45)
for kind in (0,1,4,5,6,7,8,9,19,20,21):
    for ammo in (0,1):case(ability=6,kind=kind,ammo=ammo,reserve=0)
for ability in (5,6,19):
    for maximum in (0,1,2,3,400):case(ability=ability,maximum=maximum)
for flags in (0,1,2,3,128,255):
    for battle in (0,1,32,33):case(ability=0,item_flags=flags,battle=battle)
for armor in (-1,0,1,2,9,10):case(1,armor=armor,discount=1)
for flags in (0,256,512,1024,0xFFFFFFFF):
    case(3,status=flags);case(ability=5,status=flags)
for missing in (1,2):case(3,missing=missing)
case(4)

def fixture(exe,c):
    r,s,_=use_fixture(exe,dict(entry=0,battle=c.get('battle',1)))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    pe=c.get('pe',300);ability=c.get('ability',0)
    sw(0x15C108,pe<<16);sw(0x15C128,c.get('maximum',400)<<16)
    sw(0x15C14C,c.get('status',0));sh(0xC0E08,c.get('hp',18));sh(0xC0E06,45)
    sw(0xA8048,0x178000-0xA8028)
    for i in range(20):
        sh(0x178000+i*4+2,2+i*3);sb(0x154000+(i+235)*32+5,c.get('item_flags',3))
    sb(0xC0E22,c.get('armor',1));sb(0xC0EB2,c.get('kind',1));sh(0xC0EB6,c.get('ammo',6))
    for i in range(3):sh(0xA1E6E+i*32,c.get('reserve',10))
    sb(0xC0EE0,2 if c.get('discount') else 0);sb(0xC0EE1,7);sb(0xC0EE2,14)
    sw(0x9CF3C,c.get('no_targets',0));sw(0x9D028,c.get('battle',1))
    count=c.get('history',0);sw(0x9D014,0x800A1AA0+count*36)
    for i in range(count):
        sw(0xA1AA0+i*36,1 if i%2==0 else 4);sw(0xA1AA8+i*36,c.get('reservation',20+i))
    sw(0x15FA40,0xA5A51234)
    if c.get('missing')==1:sw(0x9D254,0)
    if c.get('missing')==2:sw(0x15C000,0)
    args=((c.get('output',0x8015FA40),),(ability,c.get('available',pe)),(ability,),(),())[c['entry']]
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args)
        result=regs[2];h=fingerprint(r)
        cases.append((c['entry'],first,len(patches),args,result,h))
        print(k,c,hex(result),hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/pe-cost-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_pe_cost_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t INV16_pe_cost_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2],result; uint64_t hash; } INV16_pe_cost_cases[]={')
    for e,a,b,args,result,h in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{result:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_pe_cost_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original PE reservation, cost and availability cases')

if __name__=='__main__':main()
