#!/usr/bin/env python3
"""Original complete PE battle command lifecycle and recovery."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_item_execution_oracle import fixture as item_fixture,RANGES as ITEM_RANGES
from pe_scripted_exit_oracle import words
RANGES=ITEM_RANGES+((0x9E054,12),)
ENTRIES=(0x80022394,0x80020D50)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for ability in range(20):
    for phase in ('start','wait','finish'):case(ability=ability,phase=phase)
for ability in (0,5,7,8,10,19):
    for target in ('self','enemy','dead','hidden'):
        case(ability=ability,phase='start',target=target)
for ability in (0,5,7,8,10,19):
    for effect_used in (0,1,2,3):case(ability=ability,effect_used=effect_used)
for next_command in (0,1,2,6,386,387,406,407,65535):case(next_command=next_command)
for awake in (0,1):
    for command in (0,9,387,406):case(awake=awake,command=command,count=3)
for idle in (0,3,4):case(idle=idle,phase='finish')
for hp in (-1,0,1,45):case(1,hp=hp)
for ability in (0,6,19):case(ability=ability,phase='start',used=11)
for phase in (0,1,8,9,10):case(ability=19,status=0x80000,awaken_phase=phase)
for phase in ('wait','finish'):case(ability=6,status=0x100000,phase=phase)

def fixture(exe,c):
    r,s=item_fixture(exe,dict(c,phase=c.get('phase','wait'),command=c.get('command',c.get('ability',0)+387),
                       cmd=15,count=c.get('count',2),hp=c.get('hp',18)))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    put(0x1074C,r[0x1074C:0x10788]);put(0xE1044,r[0xE1044:0xE2854])
    sw(0x14404C,c.get('status',0)|(0x200000 if c.get('phase')=='start' else 0))
    sw(0x144008,2000<<16);sw(0x144028,400<<16)
    sb(0x9D2A0,c.get('awake',1));sb(0x9D25C,c.get('awaken_phase',0))
    sw(0x9D258,0);sb(0x150000,c.get('effect_used',1 if c.get('phase')=='wait' else 0))
    sb(0x150001,255);sb(0x14000F,7);sh(0x14001A,7 if c.get('phase')=='finish' else 2)
    target=c.get('target','self');actor=0x80140000 if target=='self' else 0x80141000
    sw(0xBE830,actor);sw(0xA5E28,0x2AAAA)
    if target=='dead':sw(0xA5D6C,0)
    if target=='hidden':sw(0x141098,0x4000)
    if c.get('ability')==19:
        sb(0x9CE3C,7)
        for i in range(7):sw(0xBE830+i*8,actor);sh(0xBE834+i*8,406)
    if c.get('status')==0x100000:sb(0x14000E,4)
    # Every effect descriptor is the original executable's data. Use real
    # heal/cure descriptors through the already-bound generic constructor.
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,()

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args,bios_seed=c.get('seed',1))
        result=regs[2];h=fingerprint(r)
        cases.append((c['entry'],first,len(patches),args,result,h,c.get('seed',1)))
        print(k,c,hex(result),hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/pe-action-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_pe_action_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t INV20_pe_action_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2],result,seed; uint64_t hash; } INV20_pe_action_cases[]={')
    for e,a,b,args,result,h,seed in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},{result}u,{seed}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_pe_action_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original PE battle-action cases')

if __name__=='__main__':main()
