#!/usr/bin/env python3
"""Original battle-controller animation continuation and counterattack calls.

The controller region has explicit entry/exit addresses; every callee executes
fully. Counterattack fixtures use unavailable effect entries, exercising the
original allocation failure while preserving command queue behavior.
"""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_player_tick_oracle import fixture as player_fixture,RANGES as PLAYER_RANGES
from pe_scripted_exit_oracle import words

RANGES=PLAYER_RANGES+((0xBE830,256),)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for cmd in range(20):
    for end in (0,1):case(cmd=cmd,end=end)
for restore in (1,2,3,65535):
    for saved in (6,7,9,11,13):case(cmd=1,end=1,restore=restore,saved=saved)
for locked in (0,1):
    for end in (0,1):case(cmd=13,end=end,actor_flags=locked*256)
case(cmd=13,end=1,field=1,actor_flags=256)
case(cmd=0,end=1,field=1,counter=1)
case(cmd=0,end=1,queued=1,counter=1)
case(cmd=0,end=1,mode=1,counter=1)
for level in (0,6,7,8,9,128,255):
    for bp in (0,50,500,10000):case(1,enemy_level=level,bp=bp,seed=10)
case(1,hp=0);case(1,hp=-1)
for flags in (0,0x4000,0x6000,0x40000000):
    for kind in (0,3):
        for child in (0,1):case(2,enemy_flags=flags,kind=kind,child=child)
for weapon in (0,1,3,0x41,0xC2):
    for queued in (0,2):case(2,weapon=weapon,queued=queued)
for bp in (0,10000):case(cmd=0,end=1,counter=1,bp=bp)
case(cmd=0,end=1,frames=2)

def fixture(exe,c):
    r,s,args=player_fixture(exe,{'entry':0})
    def put(a,b):r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    sb(0x14000E,c.get('cmd',4));sb(0x14000F,7);sh(0x14001A,7 if c.get('end') else 6)
    sw(0x140098,c.get('actor_flags',0));sw(0x9D2E8,5)
    sh(0x9D298,c.get('restore',0));sb(0x9D29A,c.get('saved',6));sw(0x9D29C,0x38000)
    sw(0x9D1D0,0x80141000);sb(0xB0CE6,c.get('field',0));sw(0x9D28C,c.get('mode',0))
    sb(0x9CE3C,c.get('queued',0));sb(0x9D2D8,255)
    sw(0x147010,c.get('weapon',2)|(0x8000 if c.get('counter') else 0))
    sh(0x147006,1);sw(0x14700C,7);sw(0x147014,0x03020100)
    sw(0xA5D5C+16,c.get('hp',40));sb(0xA5D5C+4,c.get('enemy_level',7));sh(0xC0E28,c.get('bp',500))
    sw(0x141098,c.get('enemy_flags',0));sb(0xA5D5C+5,c.get('kind',0))
    sw(0x141004,0x80142000 if c.get('child') else 0)
    sw(0x142000,0x800A5E38);sw(0x142004,0);sw(0x14218C,0x80141000)
    sb(0xA5E38+5,1);sw(0xA5E38+16,40)
    # Legitimate absent effect entries return -8 in original 6F39C.
    sw(0x942E0,0x80148000);put(0x148000,bytes(0x300))
    return r,s

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        for _ in range(c.get('frames',1)):
            if c['entry']==0:execute(r,0x8002A5BC,stop_at=(0x8002AA24,),bios_seed=c.get('seed',1))
            else:execute(r,0x800306E0 if c['entry']==1 else 0x80025BD8,(0x80141000,),bios_seed=c.get('seed',1))
        cases.append((c['entry'],c.get('frames',1),c.get('seed',1),first,len(patches),fingerprint(r)))
        print(k,c,hex(fingerprint(r)),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/player-animation-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_player_animation_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t ATK32_animation_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,frames,seed,first,end; uint64_t hash; } ATK32_animation_cases[]={')
    out.extend(f'    {{{e},{f},{s},{a},{b},UINT64_C(0x{h:016X})}},' for e,f,s,a,b,h in cases);out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_player_animation_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original player animation / counterattack cases')

if __name__=='__main__':main()
