#!/usr/bin/env python3
"""Untouched 79384/79414 SDK leaves; hardware arithmetic from psx-spx GTE.
https://psx-spx.consoledev.net/geometrytransformationenginegte/
"""
import hashlib,random,struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_transition_loader_oracle import fnv

def main():
 ex=(ROOT/'build/disc1.candidate.exe').read_bytes()
 assert hashlib.sha1(ex).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
 base=bytearray(0x200000);base[0x10000:0x10000+len(ex)-0x800]=ex[0x800:]
 digest=hashlib.sha256(base[0x79384:0x794c4]).hexdigest()
 assert digest=='418c0e10f86f636b682b2353689a5ce9a3f0719d39d63a9e371c6714f35e3028'
 rng=random.Random(48);cases=[]
 for kind in range(2):
  for i in range(1400):
   ctrl=[0]*32
   if i%3==0:
    ctrl[:8]=[rng.getrandbits(32) for _ in range(8)]
    ctrl[24:31]=[rng.getrandbits(32) for _ in range(7)]
   else:
    ctrl[0]=ctrl[2]=ctrl[4]=4096
    ctrl[5:8]=[rng.randrange(-300,301)&0xffffffff,rng.randrange(-300,301)&0xffffffff,rng.randrange(0,10000)]
    ctrl[24:31]=[160<<16,120<<16,1000,(-4194)&0xffffffff,0x1400000,341,256]
   verts=[rng.getrandbits(32) for _ in range(8)] if i%3==0 else [v&0xffffffff for j in range(4) for v in (rng.randrange(-600,601)&65535|((rng.randrange(-600,601)&65535)<<16),rng.randrange(-1000,10001))]
   cases.append((kind,i%9,ctrl,verts))
 # Positive, negative, collinear geometry, depth thresholds, signed scale extremes.
 for kind in range(2):
  for depth in (-32768,-1,0,1,499,500,501,1000,32767,32768,65535,65536,0x7fffffff,0x80000000):
   for scale in (-32768,-1,0,256,341,32767):
    for order in range(3):
     ctrl=[0]*32;ctrl[0]=ctrl[2]=ctrl[4]=4096;ctrl[7]=depth&0xffffffff
     ctrl[26:31]=[1000,0,0,scale&0xffffffff,scale&0xffffffff]
     verts=[0,0,100,0,(100<<16) if order==0 else ((-100&65535)<<16) if order==1 else 200,0,100|(100<<16),0]
     cases.append((kind,0,ctrl,verts))
 out=['/* Generated by pe_projection_oracle.py, original EXE SHA pinned. */','static const struct { unsigned kind,alias; uint32_t ctrl[32],vertices[8],ret,state[18]; uint64_t hash; } DAY1_projection_cases[]={']
 counts=[0,0,0]
 for kind,alias,ctrl,verts in cases:
  r=bytearray(base);r[0x140000:0x140100]=bytes((i*13+7)&255 for i in range(256))
  struct.pack_into('<8I',r,0x140000,*verts)
  p=[0x80140000+i*8 for i in range(4)];o=[0x80140040+i*4 for i in range(7)]
  if alias==1:o[0]=p[3]
  if alias==2:o[1]=p[3]+4
  if alias==3:o[6]=p[3]
  if alias==4:o[6]=o[0]
  if alias==5:o[4]=o[6]
  if alias==6:o[5]=o[6]
  if alias==7:o[:]=[p[3]]*7
  if alias==8:o[2]=p[0];o[3]=p[1]
  args=p[:3]+[o[0]] if not kind else p
  stack=o[1:3]+o[4:7] if not kind else o
  for j,v in enumerate(stack):struct.pack_into('<I',r,0x1ff010+j*4,v)
  state={};ret=execute(r,0x80079414 if kind else 0x80079384,args,initial_cop_control=dict(enumerate(ctrl)),strict_gte_flags=True,final_gte=state)[2]
  counts[0 if ret==0 else 1 if ret<0x80000000 else 2]+=1
  d=state['data'];values=d[7:15]+d[16:20]+d[24:28]+[d[0],d[1]&65535]
  h=fnv(r[0x140000:0x140100])
  arr=lambda vs:'{'+','.join(f'0x{v&0xffffffff:X}u' for v in vs)+'}'
  out.append(f' {{{kind},{alias},'+arr(ctrl)+','+arr(verts)+f',0x{ret:X}u,'+arr(values)+f',UINT64_C(0x{h:016X})'+'},')
 out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_projection_cases.h').write_text('\n'.join(out)+'\n')
 print(f'PASS: {len(cases)} original SDK projection cases; zero/front/back={counts}; source SHA256 {digest}')
if __name__=='__main__':main()
