#!/usr/bin/env python3
"""Original 1A9F8 -> 1D170 polygon graph on synthetic script boundaries.

No mocked callees. Math lookup values are independently generated by integer
square root and checked against the local EXE; no extracted assets are emitted.
Actor flag 80 isolates the polygon pass from the separately checked mesh pass.
"""
import hashlib
import itertools
import math
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute

RANGES=((0x960BC,384),(0x96250,384),(0x9CE2C,4),(0x9D20C,4),
        (0x9D254,4),(0x9D264,4),(0x9D2E8,4),(0x9D2F8,4),
        (0x120000,0x240),(0x130000,128))
POLYGONS=(((0,0),(1000,0),(1000,1000),(0,1000)),
          ((-900,-400),(1100,-200),(700,1300),(-600,1000)),
          ((-300,-300),(300,-300),(300,300),(-300,300)),
          ((0,0),(1000,1000),(0,1000)), ())
MOVES=(((500,500),(510,520)),((920,300),(950,310)),
       ((920,920),(950,950)),((80,300),(50,290)),
       ((300,80),(310,50)),((300,920),(310,950)),
       ((0,0),(5,5)),((700,400),(725,425)),
       ((-250,100),(-280,130)),((220,220),(270,270)),
       ((-250,-250),(-290,-290)),((500,500),(490,490)))


def cases():
    return itertools.product(range(len(POLYGONS)),MOVES,(0,1,65,130),(2048,4096),(0,4))


def fixture(exe,poly,move,radius,scale,enabled):
    r=bytearray(0x200000)
    r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    for a,n in RANGES:r[a:a+n]=bytes(n)
    def sw(a,v):struct.pack_into('<I',r,a&0x1FFFFF,v&0xFFFFFFFF)
    def sh(a,v):struct.pack_into('<H',r,a&0x1FFFFF,v&65535)
    for i in range(64,256):
        for a,v in ((0x960BC,math.isqrt(i<<18)),(0x96250,math.isqrt((4096**2*64)//i))):
            assert struct.unpack_from('<H',exe,a-0xF800+(i-64)*2)[0]==v
            sh(a+(i-64)*2,v)
    actor,points=0x80120000,0x80130000
    sw(0x9D254,actor);sw(0x9D20C,actor);sw(actor+0x98,0x80)
    sw(0x9D2F8,points);sh(0x9D264,len(POLYGONS[poly]));sw(0x9D2E8,enabled|0x101)
    sw(0x9CE2C,0xABCD1234);sh(actor+0x224,radius);sh(actor+0x26,scale)
    for i,(x,z) in enumerate(POLYGONS[poly]):sw(points+i*8,x*65536);sw(points+i*8+4,z*65536)
    for off,(x,z) in ((0x40,move[0]),(0x28,move[1])):
        sw(actor+off,x*65536+0xABCD);sw(actor+off+8,z*65536+0x1234)
    sw(actor+0x44,0x12345678);sw(actor+0x2C,0x87654321)
    return r


def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h


def main():
    exe=(ROOT/'build/extracted/disc1/SLUS_006.62').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    common=None;patches=[];rows=[]
    for c in cases():
        r=fixture(exe,*c)
        initial={a+i:struct.unpack_from('<I',r,a+i)[0] for a,n in RANGES for i in range(0,n,4)}
        if common is None:common={a:v for a,v in initial.items() if v}
        first=len(patches);patches.extend((a,v) for a,v in initial.items() if v!=common.get(a,0))
        execute(r,0x8001A9F8,(),instruction_budget=900000)
        rows.append((first,len(patches),fingerprint(r)))
    out=['/* Generated by pe_polygon_boundary_oracle.py; synthetic state, original instructions. */']
    for name,values in (('ranges',RANGES),('common',sorted(common.items())),('patches',patches)):
        out.append(f'static const uint32_t POLY_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in values);out.append('};')
    out.append('static const struct { unsigned first,end; uint64_t hash; } POLY_cases[]={')
    out.extend(f'    {{{a},{b},UINT64_C(0x{h:016X})}},' for a,b,h in rows);out.append('};')
    content='\n'.join(out)+'\n';path=ROOT/'pc_port/tests/retail_polygon_boundary_cases.h'
    if '--write-header' in sys.argv:path.write_text(content)
    if '--check' in sys.argv:assert path.read_text()==content,'polygon boundary header drift'
    print('PASS:',len(rows),'original polygon boundary graphs')


if __name__=='__main__':main()
