#!/usr/bin/env python3
"""Original complete PE ability application and field synchronization."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_inventory_use_oracle import fixture as use_fixture,RANGES as USE_RANGES
from pe_scripted_exit_oracle import words
RANGES=USE_RANGES+((0x15C000,0x1400),(0x9D1A8,8),(0x9D228,2))
ENTRIES=(0x80024250,0x80051770)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for ability in range(20):
    for discount in (0,1):case(ability=ability,discount=discount)
for ability in (0,1,2,3,4,5,9,11,12,18,19):
    for battle in (0,1):case(ability=ability,battle=battle)
for ability in (0,1,2,18):
    for hp in (0,1,44,45,32760,65530):case(ability=ability,hp=hp)
for ability in (3,4,9,18):
    for status in (0,1,2,3,4,8,12,16,32,48,64,128,192,4096,0xFFFFFFFF):case(ability=ability,status=status)
for ability in (7,8,10):
    for resistance in (0,0x15555,0x2AAAA,0x3FFFF):
        for seed in (1,2,17):case(ability=ability,resistance=resistance,seed=seed)
for maximum in (-2147483648,-1,0,1,2,3,0x500000):case(ability=5,maximum=maximum)
for ability in (0,3,4,18):
    for bank in (0,1):case(1,ability=ability,battle=0,bank=bank)
for ability in (-1,20,255):case(ability=ability)

def fixture(exe,c):
    r,s,_=use_fixture(exe,dict(entry=0,battle=c.get('battle',1),bank=c.get('bank',0)))
    def put(a,b):a&=0x1FFFFF;r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    put(0x10760,r[0x10760:0x10788])
    sw(0x15C108,2000<<16);sw(0x15C128,c.get('maximum',400<<16))
    sh(0x15C10C,c.get('hp',18));sw(0x15C14C,c.get('status',0x1055))
    sw(0x15C16C,0x8015D200);sw(0x15D204,512 if c.get('discount') else 0)
    sw(0x15C400,0x8015C800);sw(0x15C800,0xA5000000);sw(0x15C8CC,c.get('resistance',0x2AAAA))
    sw(0xB0EA8,0x8015C900);sb(0x15C902,8);sb(0x15C40E,4);sh(0x15C422,1);sw(0x9D1AC,0xA5FF00AA)
    # Existing commit fixture supplies the real camera/attenuation setup.
    sw(0x9D2E8,0xFFFF)
    args=(c.get('ability',0),0x8015C400) if c['entry']==0 else (c.get('ability',0),)
    for a,n in RANGES:s[a:a+n]=r[a:a+n]
    return r,s,tuple(v&0xFFFFFFFF for v in args)

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args,bios_seed=c.get('seed',1))
        result=regs[2];h=fingerprint(r)
        cases.append((c['entry'],first,len(patches),args,result,h,c.get('seed',1)))
        print(k,c,hex(result),hex(h),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/pe-apply-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_pe_apply_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t INV18_pe_apply_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[2],result,seed; uint64_t hash; } INV18_pe_apply_cases[]={')
    for e,a,b,args,result,h,seed in cases:
        params=','.join(f'0x{x:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},{result}u,{seed}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_pe_apply_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original PE application cases')

if __name__=='__main__':main()
