#!/usr/bin/env python3
"""Complete original recovery, inventory selection and status-item calls.

Equipped armor removal is excluded until the equipment-menu callbacks are
restored. Automatic recovery tests use absent effect resources, so these
fixtures validate status/item consumption rather than effect rendering.
"""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT,execute
from pe_player_tick_oracle import fixture as player_fixture,RANGES as PLAYER_RANGES
from pe_scripted_exit_oracle import words

RANGES=PLAYER_RANGES+((0xA1B30,0x470),(0xC0E00,0x1224))
ENTRIES=(0x80023E14,0x800523F8,0x8003335C,0x8005409C,0x80057D30,
         0x8005485C,0x800553A4,0x80059A40,0x80054E4C,0x80054CF8,
         0x8001F9C4,0x80020288)
CASES=[]
def case(entry=0,**kw):CASES.append(dict(entry=entry,**kw))
for item in range(5,19):
    for flags in (0,0x55,0xAA,0xFF,0x1000):case(item=item,flags=flags)
for item in range(6,18):case(item=item,battle=0,hp=2)
for item in (6,7,8,9,10):
    for hp in (1,44,45,46,32760):case(item=item,hp=hp)
for key in (0,19,20,99,990,65535):case(1,key=key)
for nullable in (1,2,3):case(1,nullable=nullable)
for icon in range(13):case(2,icon=icon)
for item in (0,1,6,7,10,13,17,256,258,999):case(3,item=item)
for index in (0,2,3,4,5):case(4,index=index)
for rng in (0,31,520):
    for equipped in (0,1):case(5,rng=rng,equipped=equipped)
for category in (0,1,2,3,4):
    for amount in (0,1,50,1000,-10,-100):case(6,category=category,amount=amount)
for stock in (0,1,2,4,7):case(6,stock_mask=stock,rng=520)
for capacity in (5,6,8,20,60):
    for reserve in (0,8,9,10):case(7,capacity=capacity,reserve=reserve)
for capacity in (5,6,8,20,60):
    for extra in (-1,0,1,2,5):case(8,capacity=capacity,extra=extra)
for extra in (0,1,2,3):case(9,extra=extra,capacity=8)
for flags in (0,1,4,16,64,128,4096,0x1055):case(10,flags=flags,armor_flags=0x8000)
for hp in (0,1,8,9,40):case(10,hp=hp,armor_flags=0x4000)
for attr in (10,11,12,13):case(11,attribute=attr)

def fixture(exe,c):
    r,s,args=player_fixture(exe,dict(c,entry=0))
    def put(a,b):r[a:a+len(b)]=b;s[a:a+len(b)]=b
    def sw(a,v):put(a,struct.pack('<I',v&0xFFFFFFFF))
    def sh(a,v):put(a,struct.pack('<H',v&65535))
    def sb(a,v):put(a,bytes((v&255,)))
    for a in range(0xA1B30,0xA1B4C,4):sw(a,0)
    sw(0xA8034,0x180000-0xA8028);sw(0xA8038,0x182000-0xA8028);sw(0xA803C,0x184000-0xA8028)
    for t in range(7):
        sh(0xC0E28+t*2,c.get('key',20))
        for j in range(128):sw(0x182000+t*512+j*4,j*10)
    for j in range(99):
        sw(0x184000+j*24+12,0x30000+j*128);sw(0x184000+j*24+16,0x20000+j*64)
    for j in range(256):
        a=0x180000+j*32;put(a,bytes(32));sb(a+5,128);sb(a+6,j+1)
    put(0xC0E48,bytes(100));put(0xC0EAC,bytes(128*32))
    inventory=(256,257,6,10,13,17,0,0)
    for i,v in enumerate(inventory):sh(0xC0E48+i*2,v)
    for i in range(2):
        a=0xC0EAC+i*32;sb(a,1);sb(a+5,128);sb(a+6,i+1)
        if i==1 and c.get('reserve'):sb(a+20,1);sb(a+21,c['reserve'])
    sb(0xC0E20,0 if c.get('equipped',1) else 255);sb(0xC0E22,1 if c.get('equipped',1) else 255)
    sb(0xC0E0C,c.get('capacity',8));sw(0x9D018,0)
    sw(0x9D048,0x800C0E48);sw(0x9D050,min(c.get('capacity',8),50))
    sw(0x9D058,0x8009D05C);sw(0x9D064,2);sw(0x9D06C,c.get('extra',0))
    sw(0x9D038,c.get('rng',0));put(0xA1B90,bytes((i*37+19)&255 for i in range(521)))
    for i in range(3):sh(0xA1E6E+i*32,(50+i*25) if (c.get('stock_mask',7)&(1<<i)) else 0)
    sh(0x147800,c.get('category',0));sh(0x147804,c.get('amount',0))
    sw(0x942E0,0x80190000);put(0x190000,bytes(0x300))
    null=c.get('nullable',0)
    args=((c.get('item',6),),(0 if null&1 else 0x80147808,0 if null&2 else 0x8014780C),
          (0x80140000,0,c.get('icon',0)),(c.get('item',6),),(c.get('index',2),),(),
          (0x80147800,0x80147804),(0x80147808,),(c.get('extra',0),),(),(),(0x800A5D5C,))[c['entry']]
    return r,s,args

def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

def main():
    exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    _,s,_=fixture(exe,CASES[0]);base=words(s);common=[(i*4,v) for i,v in enumerate(base) if v]
    patches=[];cases=[]
    for k,c in enumerate(CASES):
        r,s,args=fixture(exe,c);first=len(patches)
        patches.extend((i*4,v) for i,(v,b) in enumerate(zip(words(s),base)) if v!=b)
        regs=execute(r,ENTRIES[c['entry']],args)
        result=regs[2] if c['entry'] in (3,4,5,7,8) else 0
        cases.append((c['entry'],first,len(patches),args,result,fingerprint(r)))
        print(k,c,hex(result),hex(fingerprint(r)),flush=True)
        if '--dump' in sys.argv:(ROOT/f'pc_port/build/recovery-item-oracle-{k}.bin').write_bytes(r)
    out=['/* Generated by pe_recovery_item_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',common),('patches',patches)):
        out.append(f'static const uint32_t ATK33_item_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned entry,first,end; uint32_t args[3],result; uint64_t hash; } ATK33_item_cases[]={')
    for e,a,b,args,v,h in cases:
        params=','.join(f'0x{x&0xFFFFFFFF:08X}u' for x in args) or '0'
        out.append(f'    {{{e},{a},{b},{{{params}}},0x{v:08X}u,UINT64_C(0x{h:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_recovery_item_cases.h').write_text('\n'.join(out)+'\n')
    print(f'PASS: {len(cases)} original recovery / inventory / status-item cases')

if __name__=='__main__':main()
