#!/usr/bin/env python3
"""Execute all 121 original room-cleanup words, including real finalizers."""
import hashlib
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute
from pe_btl14_m0005i_publish_oracle import find_disc, read_form1

RANGES = ((0x150000, 0x3000), (0xE1044, 0x1A4), (0x9D1A0, 4))
CALLBACKS = (0x800C7DD4, 0x800C8F18, 0x800C9C10, 0x800CA7A8,
             0x800CD970, 0x800CCF90, 0x800CE1EC, 0x800CBFB4)


def main():
    exe = (ROOT / 'build/disc1.candidate.exe').read_bytes()
    assert hashlib.sha1(exe).hexdigest() == '452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    overlay = read_form1(find_disc(ROOT), 12868, 2)
    assert hashlib.sha256(overlay).hexdigest() == 'bff195a272f6b7fc19a4eba453c8ad6b138537b7dfa8c64a0da44c534777a77f'
    patches, cases, common = [], [], None
    for active in (0, 0x80):
        for count in (0, 1, 8):
            for missing in (0, 1, 2):
                r = bytearray(0x200000)
                r[0x10000:0x10000 + len(exe) - 0x800] = exe[0x800:]
                r[0x18EFE8:0x18EFE8 + len(overlay)] = overlay
                initial = {}

                def sw(a, v):
                    struct.pack_into('<I', r, a, v)
                    initial[a] = v

                for a, n in RANGES:
                    for offset in range(0, n, 4):
                        sw(a + offset, 0)
                sw(0x942E0, 0x80150000)
                sw(0xB0E64, 0x80160000)
                sw(0x9D1A0, 0x40C0 if active else 0x4040)
                sw(0x160004, 0x20)
                sw(0x160024, (count << 22) | 0x40)
                for i, code in enumerate((0x45, 7, 8, 0x54, 0x55, 0xFF, 0x45, 9)):
                    sw(0x160044 + i * 12, code << 24)
                for code in range(0x56):
                    desc = 0x151000 + code * 32
                    sw(0x150000 + code * 4, 0 if missing == 1 and code % 2 else 0x80000000 + desc)
                    sw(desc, 0xAB123456)
                    sw(desc + 24, 0 if missing == 2 else
                       0x8018F1BC if code == 0x45 else CALLBACKS[code % 8])
                for i in range(0x69):
                    sw(0xE1044 + i * 4, 0x80152000 + i * 4 if i % 3 else 0)
                    sw(0x152000 + i * 4, 0xCD765432)
                for a in (0x18EFFC, 0x18F000, 0x18F1C4, 0x18FB3C):
                    initial[a] = struct.unpack_from('<I', r, a)[0]
                first = len(patches)
                if common is None:
                    common = {a: v for a, v in initial.items() if v}
                patches.extend((a, v) for a, v in sorted(initial.items()) if v != common.get(a, 0))
                regs = execute(r, 0x800696F0, ())
                assert regs[2] == 0
                h = 1469598103934665603
                for a, n in RANGES:
                    for b in r[a:a+n]:
                        h = ((h ^ b) * 1099511628211) & 0xFFFFFFFFFFFFFFFF
                cases.append((first, len(patches), h))
                print(active, count, missing, hex(h), flush=True)
    out = ['/* Generated by pe_room_cleanup_oracle.py; synthetic state, original execution. */']
    for name, rows in (('ranges', RANGES), ('common', sorted(common.items())), ('patches', patches)):
        out.append(f'static const uint32_t SEW16_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a, b in rows)
        out.append('};')
    out.append('static const struct { unsigned first,end; uint64_t hash; } SEW16_cases[]={')
    out.extend(f'    {{{a},{b},UINT64_C(0x{h:016X})}},' for a, b, h in cases)
    out.append('};')
    if '--write-header' in sys.argv:
        (ROOT / 'pc_port/tests/retail_room_cleanup_cases.h').write_text('\n'.join(out) + '\n')
    print('PASS:', len(cases), 'complete original room cleanup cases')


if __name__ == '__main__':
    main()
