#!/usr/bin/env python3
"""Original 3F284..298 and 3F2A8..2E8 cleanup regions, including E0060.

Checks the persistent cleanup effects surrounding the display-sync calls.
This does not execute the loader, actor-spawn graph or display-sync calls.
"""
import hashlib
import itertools
import struct
import sys
from pe_battle_hud_oracle import ROOT, execute

RANGES=((0x942EC,4),(0x9CDA4,4),(0x9D1A0,4),(0x9D2E8,4),
        (0xB0CD8,4),(0xB0E5C,4),(0xE21A4,4),(0xE2800,4),(0x130000,0x100))


def fixture(exe,flags,count):
    r=bytearray(0x200000)
    r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    for a,n in RANGES:r[a:a+n]=bytes(n)
    def sw(a,v):struct.pack_into('<I',r,a&0x1FFFFF,v&0xFFFFFFFF)
    sw(0x942EC,0xA5A5ABCD);sw(0x9CDA4,123);sw(0x9D1A0,flags)
    sw(0x9D2E8,flags);sw(0xB0CD8,flags);sw(0xB0E5C,0x80130100)
    sw(0xE21A4,0x5A5A0000|(count&65535));sw(0xE2800,0xDEADBEEF)
    for i in range(10):r[0x1300EC-i*20]=0 if i%3==1 else i+1
    return r


def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h


def main():
    exe=(ROOT/'build/extracted/disc1/SLUS_006.62').read_bytes()
    assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
    common=None;patches=[];rows=[]
    for c in itertools.product((0,0x40,0xC,0x402,0x4000044F,0xFFFFFFFF),(-1,0,1,2,5)):
        r=fixture(exe,*c)
        initial={a+i:struct.unpack_from('<I',r,a+i)[0] for a,n in RANGES for i in range(0,n,4)}
        if common is None:common={a:v for a,v in initial.items() if v}
        first=len(patches);patches.extend((a,v) for a,v in initial.items() if v!=common.get(a,0))
        execute(r,0x8003F284,(),stop_at=(0x8003F298,),instruction_budget=10000)
        execute(r,0x8003F2A8,(),stop_at=(0x8003F2E8,),instruction_budget=1000)
        rows.append((first,len(patches),fingerprint(r)))
    out=['/* Generated by pe_room_entry_cleanup_oracle.py; synthetic cleanup state. */']
    for name,values in (('ranges',RANGES),('common',sorted(common.items())),('patches',patches)):
        out.append(f'static const uint32_t RCLEAN_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in values);out.append('};')
    out.append('static const struct { unsigned first,end; uint64_t hash; } RCLEAN_cases[]={')
    out.extend(f'    {{{a},{b},UINT64_C(0x{h:016X})}},' for a,b,h in rows);out.append('};')
    content='\n'.join(out)+'\n';path=ROOT/'pc_port/tests/retail_room_entry_cleanup_cases.h'
    if '--write-header' in sys.argv:path.write_text(content)
    if '--check' in sys.argv:assert path.read_text()==content,'room cleanup header drift'
    print('PASS:',len(rows),'original room cleanup region pairs')


if __name__=='__main__':main()
