#!/usr/bin/env python3
"""Original EA room sound commands, including complete projection and FIFO calls."""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute
RANGES=((0x9CDF0,4),(0x9D20C,4),(0x9D254,4),(0x9D268,4),(0x9D2F0,8),
        (0xB0CD8,0x240),(0xB8628,0x300),(0xBCD80,0x240),
        (0x140000,0x400),(0x150000,0x800),(0x160000,0x800))
CASES=[]
for key in (300,350,351,352,353):
 for sound in (0,1,2):
  for x in (-32768,0,32767):CASES.append(dict(key=key,sound=sound,x=x))
for target in (0,2,3,258):
 for absent in (0,1):
  for retired in (0,1):CASES.append(dict(key=352,target=target,absent=absent,retired=retired,sound=1))
for queue in (0,1,17):CASES.append(dict(key=300,sound=1,queue=queue))

def fixture(exe,c):
 r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
 for a,n in RANGES:r[a:a+n]=bytes(n)
 def sw(a,v):struct.pack_into('<I',r,a&0x1FFFFF,v&0xFFFFFFFF)
 def sh(a,v):struct.pack_into('<H',r,a&0x1FFFFF,v&65535)
 def sb(a,v):r[a&0x1FFFFF]=v&255
 sw(0x9CDF0,0x5FF);sw(0x9D2F4,c.get('queue',0))
 sw(0xB0E64,0x80160000);sw(0x160004,0x40)
 sw(0x16006C,(2<<22)|0x100)
 for i in range(2):
  sh(0x160100+i*12+10,0x7E2+i)
  sw(0x160100+i*12+4,0x200+i*16)
  sw(0x160200+i*16,0x4F414B41 if c['sound']==1 else 0x12345678)
 sw(0xBCFA4,0x80140000);sw(0xBCFA8,0x80140100);sw(0x140100,256)
 for i in range(3):sh(0x140000+i*8,4096)
 sw(0x14001C,1024);sh(0xBCF94,160);sh(0xBCF96,112)
 sh(0xB0DD0,100);sh(0xB0DD2,1000);sb(0xB0DCE,20);sb(0xB0DCF,120)
 sw(0x9D20C,0x80150000);sw(0x9D2F0,0x80150000)
 sw(0x9D254,0 if c.get('absent') else 0x80150280)
 for i in range(2):
  a=0x150000+i*0x280;sw(a+4,0x80150280 if i==0 else 0)
  sb(a+12,2);sb(a+13,7);sw(a+0x98,16 if c.get('retired') else 0)
  for j,v in enumerate((c.get('x',40)+i,17,-200)):sw(a+40+j*4,v*65536+0xABCD)
 key=c['key'];values=[key,0x7E2 if c['sound'] else 0x1234,0x12345678,0xFFFF,0x123,0xDEADBEEF]
 if key==350:values[1:5]=[0x12345,0x123,0x98765,0x234]
 if key==352:values[2:4]=[c.get('target',2),7 if not c.get('absent') else 9]
 if key==353:values[2:5]=[(c.get('x',40)*65536+0xFEED)&0xFFFFFFFF,0x0011CAFE,0xFF381234]
 for i,v in enumerate(values):sw(0x140200+i*4,0x80140240+i*4);sw(0x140240+i*4,v)
 return r

def fingerprint(r):
 h=14695981039346656037
 for a,n in RANGES:
  for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
 return h

def main():
 exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
 assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
 common=None;patches=[];cases=[]
 for k,c in enumerate(CASES):
  r=fixture(exe,c);initial={a+i:struct.unpack_from('<I',r,a+i)[0] for a,n in RANGES for i in range(0,n,4)}
  if common is None:common={a:v for a,v in initial.items() if v}
  first=len(patches);patches.extend((a,v) for a,v in initial.items() if v!=common.get(a,0))
  regs=execute(r,0x80015DAC,(0x80140200,),instruction_budget=900000);assert regs[2]==1
  cases.append((first,len(patches),fingerprint(r)))
  print(k,c,hex(cases[-1][-1]),flush=True)
  if '--dump' in sys.argv:(ROOT/f'local/live/script-sound-oracle-{k}.bin').write_bytes(r)
 out=['/* Generated by pe_script_sound_oracle.py; original execution on synthetic state. */']
 for name,rows in (('ranges',RANGES),('common',sorted(common.items())),('patches',patches)):
  out.append(f'static const uint32_t SEW19_{name}[][2]={{')
  out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
 out.append('static const struct { unsigned first,end; uint64_t hash; } SEW19_cases[]={')
 out.extend(f'    {{{a},{b},UINT64_C(0x{h:016X})}},' for a,b,h in cases);out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_script_sound_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',len(cases),'original script sound cases')
if __name__=='__main__':main()
