#!/usr/bin/env python3
"""Original 97BA0 subdividing model packet emitter, all eight streams."""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_m0000i_leaves_oracle import load_overlay
from pe_transition_loader_oracle import fnv
STRIDES=(28,36,36,48,64,72,60,76)
VERTEX=(4,4,12,16,40,40,36,44)
RANGES=((0,1024),(0x140000,0x1800),(0x145000,0x1000),(0x146000,0x5000),(0x14B000,16),(0x19C9C0,4),(0x1EA5E0,4))
def fixture(base,seed,mask,mode,bias,shape,depth):
 r=bytearray(base)
 def nextval():
  nonlocal seed
  seed^=(seed<<13)&0xffffffff;seed^=seed>>17;seed^=(seed<<5)&0xffffffff
  return seed
 def sw(a,v):struct.pack_into('<I',r,a,v&0xffffffff)
 for a,n in RANGES:
  for i in range(0,n,4):sw(a+i,nextval())
 ctrl={0:4096,2:4096,4:4096,5:nextval()%201-100,6:nextval()%201-100,7:nextval()%3000+1000,24:160<<16,25:120<<16,26:1000,27:-4194,28:0x1400000,29:341,30:256}
 if shape:ctrl.update({5:0,6:0,7:depth})
 sw(0x140000,0x40);sw(0x140004,0x40)
 for kind in range(8):
  count=(1+nextval()%3) if mask>>kind&1 else 0
  if shape:count=1 if mask>>kind&1 else 0
  struct.pack_into('<H',r,0x140040+kind*2,count)
  sw(0x140050+kind*4,0xc0+kind*0x200)
  for i in range(3):
   p=0x140100+kind*0x200+i*STRIDES[kind]+VERTEX[kind]
   order=nextval()%4
   if shape:order=shape-1
   coords=((-200,-200),(200,-200),(-200,200),(200,200))
   if order==1:coords=(coords[0],coords[2],coords[1],coords[3])
   if order==2:coords=((0,0),)*4
   if order==3:coords=tuple(((nextval()%65536)-32768,(nextval()%65536)-32768) for _ in range(4))
   for j in range(4 if kind in (1,3,5,7) else 3):
    z=(nextval()%4096)-1024
    struct.pack_into('<4h',r,p+j*8,*coords[j],0 if shape else z,0)
 packet=0x80145000
 if mode in (1,2):packet=0x80140100+((mask.bit_length()-1) if mask else 0)*0x200+(4 if mode==1 else 16)
 ot=0x80146000
 kind=(mask.bit_length()-1) if mask else 0
 index=((256 if kind==1 else 255)+bias)>>2
 if mode==3:ot=packet-index*4
 if mode==4:ot=0x80140100-index*4
 descriptor=0x140100+kind*0x200 if mode==5 else 0x14B000
 sw(0x19C9C0,0x80000000+descriptor);sw(descriptor,packet);sw(descriptor+4,ot);sw(0x1EA5E0,bias)
 return r,ctrl

def main():
 ex,o,b=load_overlay();base=bytearray(0x200000);base[0x10000:0x10000+len(ex)-0x800]=ex[0x800:];base[b&0x1fffff:(b&0x1fffff)+len(o)]=o
 digest=hashlib.sha256(o[0x80197BA0-b:0x8019959C-b]).hexdigest()
 assert digest=='8a823f37071d3fc46dba908ad18da507e51145bbd576efe69d59af85fce3f4a3'
 cases=[]
 for mode in range(3):
  for mask in range(256):cases.append((52+mode*65537+mask*101,mask,mode,0,0,1024))
 for kind in range(8):
  for index in (0,1,2,63,64,498,499,500,501,502,508,509,510,511,699,700,701,702,1023,4095):
   depth=(index*16384+1022)//1023
   for bias in (-3,0,3):
    for shape in (1,2,3):cases.append((52+kind*101,1<<kind,0,bias,shape,depth))
  for mode in (3,4):cases.append((52+kind*101,1<<kind,mode,0,1,1024))
 for low in range(4):
  for high in range(4,8):cases.append((52+low*101+high,1<<low|1<<high,5,0,1,1024))
 out=['/* Generated by pe_subdiv_model_oracle.py from untouched original code. */','static const struct { uint32_t seed,mask,mode,bias,shape,depth,state[16]; uint64_t hash; } DAY1_subdiv_model_cases[]={']
 visited=set()
 for seed,mask,mode,bias,shape,depth in cases:
  r,ctrl=fixture(base,seed,mask,mode,bias,shape,depth)
  state={};execute(r,0x80197BA0,(0x80149999,0x80140040),initial_cop_control=ctrl,initial_regs={i:(seed*101+i*65537)&0xffffffff for i in list(range(1,4))+list(range(6,28))+[30]},strict_gte_flags=True,final_gte=state,instruction_budget=500000,visited_pcs=visited)
  d=state['data'];vs=d[7:15]+d[16:20]+d[24:28]
  h=fnv(b''.join(r[a:a+n] for a,n in RANGES))
  out.append(f' {{{seed},{mask},{mode},0x{bias&0xffffffff:X}u,{shape},{depth},'+'{'+','.join(f'0x{x&0xffffffff:X}u' for x in vs)+'}'+f',UINT64_C(0x{h:016X})'+'},')
 out.append('};')
 header='\n'.join(out)+'\n'
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_subdiv_model_cases.h').write_text(header)
 else:assert (ROOT/'pc_port/tests/retail_subdiv_model_cases.h').read_text()==header
 paths=(0x80197CDC,0x80197E30,0x80197F88,0x801980F4,0x801984CC,0x801987AC,0x80198A68,0x80198E4C,0x801992A0,0x80199440)
 assert all(pc in visited for pc in paths),[hex(pc) for pc in paths if pc not in visited]
 print(f'PASS: {len(cases)} original subdivision emitter cases; all8 streams plus near/far texture paths; SHA256 {digest}')
if __name__=='__main__':main()
