#!/usr/bin/env python3
"""Execute original StoreImage worker with explicit GPU read/MMIO scripts.

The production GPU's readback/async completion is tested independently.
Only the unused high half of an odd final read word is host-defined as zero.
"""
import hashlib
from pathlib import Path
import sys
from b53e_oracle import (Machine,Exe,HardwareEvent,callee_script,seed_rect,RECT,
    LIMIT_W,LIMIT_H,WAIT_DEADLINE,WAIT_COUNTER,GP0,GPUSTAT_GP1,DMA2_MADR,DMA2_BCR,DMA2_CHCR)

ROOT=Path(__file__).resolve().parents[2]
DEST=0x800D0000
CASES=[]
for w,h in ((-1,1),(0,1),(1,-1),(1,0),(1,1),(2,1),(3,1),(30,1),(31,1),(32,1),
            (33,1),(34,1),(63,1),(64,1),(65,1),(7,3),(7,5),(256,32),(1024,512),
            (2048,1),(1,1024),(32767,1)):
    for x,y in ((0,0),(1023,511)):CASES.append((x,y,w,h,1024,512))
CASES.extend(((7,8,100,10,32,4),(7,8,32,4,0,512),(7,8,32,4,1024,0)))

class ReadMachine(Machine):
    def load(self,address,size,signed=False):
        if address==GP0 and size==4:return self.consume_hardware('read',address)
        return super().load(address,size,signed)

def pixel(i):return (i*37+0x123)&65535

def main():
    exe=Exe(ROOT/'build/disc1.candidate.exe');out=['/* Generated by pe_store_image_oracle.py --write-header. */',
        'static const struct { int16_t rect[4],limits[2]; uint16_t width,height; uint32_t result,count,prefix[15],dma[3]; } NAM10_store_image_cases[]={']
    for k,(x,y,w,h,lw,lh) in enumerate(CASES):
        cw=max(0,min(w,lw));ch=max(0,min(h,lh));words=(cw*ch+1)//2;prefix=words%16;blocks=words//16
        script=[]
        def event(kind,pc,address,value):script.append(HardwareEvent(kind,pc,address,value))
        if words:
            event('read',0x8007698C,GPUSTAT_GP1,0x04000000)
            event('write',0x800769E0,GPUSTAT_GP1,0x04000000)
            event('write',0x800769F0,GP0,0x01000000)
            event('write',0x80076A00,GP0,0xC0000000)
            event('write',0x80076A14,GP0,(x&65535)|((y&65535)<<16))
            event('write',0x80076A28,GP0,cw|(ch<<16))
            event('read',0x80076A38,GPUSTAT_GP1,0x0C000000)
            for i in range(prefix):
                value=pixel(i*2)|((pixel(i*2+1) if i*2+1<cw*ch else 0)<<16)
                event('read',0x80076A9C,GP0,value)
            if blocks:
                event('write',0x80076AC4,GPUSTAT_GP1,0x04000003)
                event('write',0x80076AD4,DMA2_MADR,DEST+prefix*4)
                event('write',0x80076AE8,DMA2_BCR,(blocks<<16)|16)
                event('write',0x80076AF8,DMA2_CHCR,0x01000200)
        machine=ReadMachine(exe,script,callee_script(31));seed_rect(machine,x,y,w,h)
        machine.seed(LIMIT_W,2,lw);machine.seed(LIMIT_H,2,lh)
        result=machine.run(RECT,DEST,entry=0x800768A0);machine.assert_scripts_consumed()
        assert machine.peek(WAIT_DEADLINE,4)==271 and machine.peek(WAIT_COUNTER,4)==0
        observed=[machine.peek(DEST+i*4,4) for i in range(prefix)]
        dma=[next((e.value for e in reversed(machine.hardware_observed) if e.kind=='write' and e.address==a),0)
             for a in (DMA2_MADR,DMA2_BCR,DMA2_CHCR)]
        out.append('    {{%s},{%d,%d},%d,%d,0x%08Xu,%d,{%s},{%s}},'%(
            ','.join(map(str,(x,y,w,h))),lw,lh,machine.peek(RECT+4,2),machine.peek(RECT+6,2),result,prefix,
            ','.join('0x%08Xu'%v for v in observed) or '0',','.join('0x%08Xu'%v for v in dma)))
        print(k,(x,y,w,h,lw,lh),'result',hex(result),'CPU words',prefix,'DMA',dma,flush=True)
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_store_image_cases.h').write_text('\n'.join(out)+'\n')
    print('PASS:',len(CASES),'complete original StoreImage worker cases; body SHA256',
          hashlib.sha256(exe.body(0x800768A0,0x280)).hexdigest())

if __name__=='__main__':main()
