#!/usr/bin/env python3
"""Offline static C transcription of the original subdivision emitter.
No instruction stream, register array or opcode dispatch is used by the port.
Native locals replace the nonescaping MIPS stack frame; explicit labels retain
original branch/write ordering for the two different packet cursors.
"""
import hashlib,re,sys
from capstone import Cs,CS_ARCH_MIPS,CS_MODE_MIPS32,CS_MODE_LITTLE_ENDIAN
from pe_m0000i_leaves_oracle import load_overlay
from pe_battle_hud_oracle import ROOT

def main():
 ex,o,b=load_overlay();raw=o[0x80197BA0-b:0x8019959C-b]
 assert len(raw)==1663*4 and hashlib.sha256(raw).hexdigest()=='8a823f37071d3fc46dba908ad18da507e51145bbd576efe69d59af85fce3f4a3'
 cs=Cs(CS_ARCH_MIPS,CS_MODE_MIPS32|CS_MODE_LITTLE_ENDIAN);cs.skipdata=True
 ins={i.address:(i.mnemonic,i.op_str) for i in cs.disasm(raw,0x80197BA0)}
 targets=set();delays=set()
 for pc,(m,a) in ins.items():
  if m in ('blez','beqz','bnez','j'):targets.add(int(a.split(',')[-1].strip(),16));delays.add(pc+4)
  if m=='jal':delays.add(pc+4)
 assert not targets&delays
 def reg(s):return '0u' if s=='$zero' else s.removeprefix('$')
 def number(s):return str(int(s,0)) if int(s,0)>=0 else f'({int(s,0)})'
 def address(s):
  m=re.fullmatch(r'([^()]*)\((\$\w+)\)',s);assert m,s
  off=int(m[1] or '0',0)
  if m[2]=='$sp':return f'frame[{off//4}]',True
  return f'{reg(m[2])}'+(f'+0x{off:X}u' if off>0 else f'-0x{-off:X}u' if off<0 else ''),False
 def plain(pc):
  m,a=ins[pc];p=[x.strip() for x in a.split(',')]
  if m=='nop':return []
  if m=='move':return [f'{reg(p[0])}={reg(p[1])};']
  if m=='lui':return [f'{reg(p[0])}=0x{int(p[1],0)<<16:X}u;']
  if m=='addiu':return [f'{reg(p[0])}={reg(p[1])}+(uint32_t){number(p[2])};']
  if m in ('addu','subu','and','or'):
   op={'addu':'+','subu':'-','and':'&','or':'|'}[m];return [f'{reg(p[0])}={reg(p[1])}{op}{reg(p[2])};']
  if m=='ori':return [f'{reg(p[0])}={reg(p[1])}|{number(p[2])}u;']
  if m in ('sll','sra'):
   return [f'{reg(p[0])}='+ (f'(uint32_t)((int32_t){reg(p[1])}>>{number(p[2])})' if m=='sra' else f'{reg(p[1])}<<{number(p[2])}')+';']
  if m in ('slt','slti','sltiu'):
   rhs=reg(p[2]) if m=='slt' else number(p[2]);cast='(int32_t)' if m!='sltiu' else '(uint32_t)'
   return [f'{reg(p[0])}=({cast}{reg(p[1])}<{cast}{rhs});']
  if m in ('lw','lh','lhu','lbu','sw','sh','sb'):
   addr,stack=address(p[1]);r=reg(p[0])
   if stack:assert m in ('lw','sw');return [f'{r}={addr};' if m=='lw' else f'{addr}={r};']
   if m=='lh':return [f'{r}=(uint32_t)(int32_t)(int16_t)PE_LoadU16({addr});']
   if m.startswith('l'):return [f'{r}=PE_LoadU'+{'lw':'32','lhu':'16','lbu':'8'}[m]+f'({addr});']
   bits={'sw':32,'sh':16,'sb':8}[m];return [f'PE_StoreU{bits}({addr},(uint{bits}_t){r});']
  if m=='lwc2':
   n=int(p[0][1:]);addr,stack=address(p[1]);assert not stack and n<6
   v=f'g_pe_gte.v{n//2}'
   return [f'word=PE_LoadU32({addr});',f'{v}[2]=(int16_t)word;'] if n%2 else [f'word=PE_LoadU32({addr});',f'{v}[0]=(int16_t)word; {v}[1]=(int16_t)(word>>16);']
  if m=='swc2':
   addr,stack=address(p[1]);assert not stack
   n=int(p[0][1:]);value={7:'g_pe_gte.otz',12:'g_pe_gte.sxy[0]',13:'g_pe_gte.sxy[1]',14:'g_pe_gte.sxy[2]',24:'(uint32_t)g_pe_gte.mac0'}[n]
   return [f'PE_StoreU32({addr},{value});']
  if m=='.byte':
   w=int.from_bytes(raw[pc-0x80197BA0:pc-0x80197BA0+4],'little')
   return [{0x4A280030:'PE_GTE_RTPT_coordinates(xy,z);',0x4A180001:'PE_GTE_RTPS_coordinates(xy,z);',0x4B400006:'(void)PE_GTE_NCLIP();',0x4B58002D:'PE_GTE_AVSZ3(g_pe_gte.sz+1);'}[w]]
  raise AssertionError((hex(pc),m,a))
 out=['''/* Original 80197BA0..8019959C, all1663 words.
 * SHA256 8a823f37071d3fc46dba908ad18da507e51145bbd576efe69d59af85fce3f4a3.
 * Static native C transcription: no runtime instruction fetch/decode. Labels
 * preserve original control flow and distinct payload/link cursor sequences.
 * Prologue/epilogue saves collapse into C locals; the nonescaping spill frame
 * stays native. Generated by pe_subdiv_model_translate.py from pinned overlay.
 */
#include "pe_port_compat.h"
#include "pe_sdk.h"
void func_80197BA0(pe_addr_t unused, pe_addr_t model)
{
    uint32_t at=0,v0=0,v1=0,a0=unused,a1=model,a2=0,a3=0;
    uint32_t t0=0,t1=0,t2=0,t3=0,t4=0,t5=0,t6=0,t7=0,t8=0,t9=0;
    uint32_t s0=0,s1=0,s2=0,s3=0,s4=0,s5=0,s6=0,s7=0,fp=0;
    uint32_t frame[46]={0},word,xy[3],z[3];
    int branch;
''']
 sections={0x80197BD4:'Model streams and cached depth bias.',0x80197C34:'Flat triangle stream.',0x80197D84:'Flat quad stream.',0x80197EE4:'Gouraud triangle stream.',0x8019804C:'Gouraud quad stream.',0x801981D4:'Textured triangles: subdivision, three UV depth bands.',0x801988CC:'Textured quads: subdivision, three UV depth bands.',0x80199200:'Textured Gouraud triangles.',0x80199394:'Textured Gouraud quads.'}
 skip=set();count=0
 for pc in range(0x80197BA4,0x80199568,4):
  m,a=ins[pc]
  # Elide only ABI callee saves, not internal spills or stream state.
  if pc in skip or (pc<0x80197BD4 and m=='sw'):continue
  if pc in sections:out.append('    /* '+sections[pc]+' */')
  if pc in targets:out.append(f'L_{pc:08X}:;')
  lines=[]
  if m in ('blez','beqz','bnez','j'):
   if m!='j':
    r=reg(a.split(',')[0]);test={'blez':f'(int32_t){r}<=0','beqz':f'{r}==0','bnez':f'{r}!=0'}[m]
    lines.append(f'branch=({test});')
   lines+=plain(pc+4);target=int(a.split(',')[-1].strip(),16)
   lines.append(('if(branch) ' if m!='j' else '')+f'goto L_{target:08X};');skip.add(pc+4)
  elif m=='jal':
   lines+=plain(pc+4);target=int(a,16);assert target in (0x80079384,0x80079414)
   args=['a0','a1','a2','a3']+[f'frame[{i}]' for i in range(4,9 if target==0x80079384 else 11)]
   lines.append(f'v0=(uint32_t)func_{target:08X}('+','.join(args)+');');skip.add(pc+4)
  else:lines+=plain(pc)
  if lines:out.append(f'    /* {pc:08X} */ '+' '.join(lines));count+=len(lines)
 out+=['}',''];text='\n'.join(out)
 p=ROOT/'pc_port/game/boot/func_80197BA0_port.c'
 if '--write' in sys.argv:p.write_text(text)
 else:assert p.read_text()==text
 print(f'PASS: static full emitter transcription; {count} C statements, {len(targets)} original branch labels')
if __name__=='__main__':main()
