#!/usr/bin/env python3
"""Execute original E2 embedded polygon wrapper, including full VM calls."""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute

RANGES=((0x9CE00,4),(0x9D1A0,4),(0x9D2F0,4),(0x9D300,16),
        (0x91120,4),(0x91428,4),(0x120F80,64),(0x140000,0x300),
        (0x145000,0x280),(0x150000,0x300))
POLYGONS=((),((-100,-100),(100,-100),(100,100),(-100,100)),
          ((0,0),(300,0),(300,300),(100,100),(0,300)),
          ((-32768,-32768),(32767,-32768),(32767,32767),(-32768,32767)))
CASES=[dict(poly=p,x=x,y=y,vm=vm) for p in range(len(POLYGONS))
       for x,y in ((0,0),(100,100),(-100,-100),(301,0),(-32768,32767),(50,250))
       for vm in (0,1)]

def fixture(exe,c):
 r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
 for a,n in RANGES:r[a:a+n]=bytes(n)
 def sw(a,v):struct.pack_into('<I',r,a,v&0xFFFFFFFF)
 sw(0x91120,0x800172FC);sw(0x91428,0x8001A390)
 sw(0x9D2F0,0x80145000);sw(0x14509C,0x80150000)
 poly=POLYGONS[c['poly']]
 for i,(x,y) in enumerate(poly):sw(0x150100+i*8,x*65536+0xABCD);sw(0x150104+i*8,y*65536+0xDCBA)
 values=(c['x']*65536+0x1234,c['y']*65536+0x5678,len(poly)|0xABCD0000,0x80000080,0xDEADBEEF)
 for i,v in enumerate(values):sw(0x140000+i*4,0x80140040+i*4);sw(0x140040+i*4,v)
 if c['vm']:
  sw(0x9D300,0x80140100);sw(0x140100,0x80140200);sw(0x140110,1)
  for i,v in enumerate((0x2000A0E2,0,*values[:4],0,0x20,0)):sw(0x140200+i*4,v)
 return r

def fingerprint(r):
 h=14695981039346656037
 for a,n in RANGES:
  for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
 return h

def main():
 exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
 assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
 common=None;patches=[];cases=[]
 for k,c in enumerate(CASES):
  r=fixture(exe,c);initial={a+i:struct.unpack_from('<I',r,a+i)[0] for a,n in RANGES for i in range(0,n,4)}
  if common is None:common={a:v for a,v in initial.items() if v}
  first=len(patches);patches.extend((a,v) for a,v in initial.items() if v!=common.get(a,0))
  regs=execute(r,0x80017018 if c['vm'] else 0x8001A390,() if c['vm'] else (0x80140000,),instruction_budget=100000)
  if not c['vm']:assert regs[2]==1
  cases.append((c['vm'],first,len(patches),fingerprint(r)))
  print(k,c,hex(cases[-1][-1]),flush=True)
  if '--dump' in sys.argv:(ROOT/f'local/live/script-polygon-oracle-{k}.bin').write_bytes(r)
 out=['/* Generated by pe_script_polygon_oracle.py; full original instruction execution. */']
 for name,rows in (('ranges',RANGES),('common',sorted(common.items())),('patches',patches)):
  out.append(f'static const uint32_t SEW22_{name}[][2]={{')
  out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
 out.append('static const struct { unsigned vm,first,end; uint64_t hash; } SEW22_cases[]={')
 out.extend(f'    {{{v},{a},{b},UINT64_C(0x{h:016X})}},' for v,a,b,h in cases);out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_script_polygon_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',len(cases),'original script polygon cases')
if __name__=='__main__':main()
