#!/usr/bin/env python3
"""Execute original transition GTE setters, then read control registers.

A test-only caller reads cfc2 after the untouched retail call graph returns.
No original callee or arithmetic is substituted. Matrix terminal words and
DQA are compared at their implemented hardware halfword widths.
"""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute
REGS=tuple(range(8,24))+(27,28)
INITIAL={i:(0x11223344+i*0x01010101)&0xFFFFFFFF for i in REGS}
CASES=[]
for entry in (0x80078E34,0x80078E64):
 for seed in (0,255,0xA5,0x37):CASES.append((entry,(0x80140000,0,0),seed))
for entry in (0x80078FC4,0x80078FE4):
 for args in ((0,0,0),(128,128,128),(255,1,17),(0xFFFFFFFF,0x80000000,0x7FFFFFFF),(0x12345678,0xFEDCBA98,0x0FFFFFFF)):
  CASES.append((entry,args,0))
for near,far in ((6500,11500),(0,100),(0,99),(100,0),(100,100),(100,199),(100,200),
                 (-100,100),(-10000,-100),(0x7FFFFFFF,0x80000063),
                 (0x80000000,0x7FFFFFFF),(0xFFFFFFFF,0x7FFFFFFF),(65535,131071),
                 (8388608,8388708),(100000,100100)):
 for h in (1,16,768,-1,-768,0x7FFFFFFF,0x80000000):
  CASES.append((0x80077E64,(near&0xFFFFFFFF,far&0xFFFFFFFF,h&0xFFFFFFFF),0))
# Width/degenerate spans skip all divisions even when H is zero.
CASES.append((0x80077E64,(1,100,0),0))
CASES.append((0x80077E64,(6500,11500,0),0))

def main():
 exe=(ROOT/'build/disc1.candidate.exe').read_bytes()
 assert hashlib.sha1(exe).hexdigest()=='452fb033f2eaa4b18aa20a5bca60b8125af3a37b'
 out=['/* Generated by pe_transition_gte_oracle.py --write-header. */',
      'static const uint32_t DAY1_tgte_initial[]={'+','.join(f'0x{INITIAL[i]:X}u' for i in REGS)+'};',
      'static const struct { uint32_t entry,args[3],seed,trap,control[18]; } DAY1_tgte_cases[]={']
 traps=0
 for entry,args,seed in CASES:
  r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
  r[0x140000:0x140020]=bytes((seed+i*17)&255 for i in range(32))
  code=[0x3C098014,0x35292100]
  for j,i in enumerate(REGS):code.extend(((18<<26)|(2<<21)|(8<<16)|(i<<11),(43<<26)|(9<<21)|(8<<16)|(j*4)))
  code.extend((8,0))
  for j,w in enumerate(code):struct.pack_into('<I',r,0x142000+j*4,w)
  before=bytes(r)
  trap=0
  try:
   execute(r,entry,args,initial_regs={31:0x80142000},initial_cop_control=INITIAL)
  except AssertionError as exc:
   # These retail BREAK sites occur before either coefficient ctc2.
   detail=exc.args[0]
   if detail not in (("0x80077f04","0x7000d"),("0x80077f1c","0x6000d")):
    # The interpreter reports DIV-by-zero before the subsequent BREAK 7.
    if not (entry==0x80077E64 and args[2]==0 and isinstance(detail,tuple) and
            detail[:2]==('division by zero in original fixture','0x80077ef8')):raise
   trap=1
  traps+=trap
  outside=bytearray(r[:0x1F0000]);outside[0x142100:0x142148]=before[0x142100:0x142148]
  assert outside==before[:0x1F0000],f'unexpected persistent write {entry:X}'
  values=[INITIAL[i] for i in REGS] if trap else list(struct.unpack_from('<18I',r,0x142100))
  for j,i in enumerate(REGS):
   if i in (12,20,27):values[j]&=65535
  out.append(f'    {{0x{entry:X}u,{{'+','.join(f'0x{v:X}u' for v in args)+f'}},{seed},{trap},{{'+','.join(f'0x{v:X}u' for v in values)+'}},')
 out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_transition_gte_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',len(CASES),'original GTE setup cases:',len(CASES)-traps,'control readbacks,',traps,'arithmetic traps')
if __name__=='__main__':main()
