#!/usr/bin/env python3
"""Retail transition packet initialization and double-buffered OT publication."""
import hashlib,struct,sys
from pe_m0000i_leaves_oracle import load_overlay
from pe_battle_hud_oracle import ROOT,execute
RANGES=((0x19C9D0,0x1E0),(0x1EA598,0x48),(0x19C1F0,0x10),
        (0x19C9C0,4),(0x19C02C,4),(0x140000,8),(0x142000,0x4000))

def fingerprint(r):
 h=14695981039346656037
 for a,n in RANGES:
  for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
 return h

def main():
 exe,overlay,base=load_overlay()
 code=overlay[0x80195F6C-base:0x80196498-base]
 print('80195F6C',len(code)//4,hashlib.sha256(code).hexdigest())
 steps=[]
 for seed in (0,255,0xA5,0x5A,37):
  for bank in (0,1):
   for flag in (0,1,2,0x101):
    r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    r[base&0x1FFFFF:(base&0x1FFFFF)+len(overlay)]=overlay
    for a,n in RANGES:
     for i in range(n):r[a+i]=(seed+i*17+(i>>8))&255
    def sw(a,v):struct.pack_into('<I',r,a,v)
    sw(0x19C1F0,flag);sw(0x19C02C,0)
    sw(0x19C9C0,0x80140000 if bank else 0x8019C1F8)
    sw(0x140004,0x80142000);sw(0x19C1FC,0x80142000)
    # Reinitialization preserves OT tag fields already linked by 92740.
    for i,entry in enumerate((0x80195F6C,0x80192740,0x80195F6C,0x80192740)):
     before=bytes(r);execute(r,entry)
     outside=bytearray(r[:0x1F0000])
     for a,n in RANGES:outside[a:a+n]=before[a:a+n]
     assert outside==before[:0x1F0000],f'uncompared write {entry:X}'
     steps.append((int(i==0),seed,bank,flag,entry,fingerprint(r)))
 out=['/* Generated by pe_transition_packets_oracle.py --write-header. */',
      'static const uint32_t DAY1_packets_ranges[][2]={']
 out += [f'    {{0x{a:X}u,0x{n:X}u}},' for a,n in RANGES];out += ['};']
 out += ['static const struct { unsigned reset,seed,bank,flag; uint32_t entry; uint64_t hash; } DAY1_packets_steps[]={']
 out += [f'    {{{reset},{seed},{bank},{flag},0x{entry:X}u,UINT64_C(0x{h:016X})}},' for reset,seed,bank,flag,entry,h in steps]
 out += ['};']
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_transition_packets_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',len(steps),'original transition packet history steps')
if __name__=='__main__':main()
