#!/usr/bin/env python3
"""Original transition display setup with explicit hardware providers.

74D28 (display mask),752AC (OTC),74F44 (VRAM clear),74DC0 (sync)
are provider boundaries. OTC writes its documented reverse links; other
providers record arguments only. Original GTE setters, BF8C and draw/disp
environment constructors execute. GTE control state is independently
validated by pe_transition_gte_oracle.py; it is not hashed here.
"""
import struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_m0000i_leaves_oracle import load_overlay
RANGES=((0x19C1F8,0xF0),(0x19C9C0,4),(0x140000,0x4000),(0x145000,0x4000),
        (0x14A000,0x4000),(0x150000,8),(0x9580C,4))
STOPS=(0x80074D28,0x800752AC,0x80074F44,0x80074DC0)
def hash_ram(r):
 h=14695981039346656037
 for a,n in RANGES:
  for v in r[a:a+n]:h=((h^v)*1099511628211)&0xFFFFFFFFFFFFFFFF
 return h

def run(r,entry):
 calls=[];regs=execute(r,entry,stop_at=STOPS)
 while regs[31]:
  ret=regs[31];w=struct.unpack_from('<I',r,(ret-8)&0x1FFFFF)[0];fn=0x80000000|((w&0x3FFFFFF)<<2)
  args=regs[4:8];args=[v&0xFFFFFFFF for v in args]
  if fn==0x800752AC:
   assert args[1]==4096
   a=args[0]&0x1FFFFF
   for i in range(4095,0,-1):struct.pack_into('<I',r,a+4*i,(args[0]+4*i-4)&0xFFFFFF)
   struct.pack_into('<I',r,a,0x9580C);struct.pack_into('<I',r,0x9580C,0x4957F8)
   calls.append((fn,*args[:2]))
  elif fn==0x80074F44:
   xy,wh=struct.unpack_from('<2I',r,args[0]&0x1FFFFF)
   calls.append((fn,xy,wh,*args[1:]))
  else:calls.append((fn,args[0]))
  regs[2]=0;regs=execute(r,ret,initial_regs=dict(enumerate(regs)),stop_at=STOPS)
 return calls

def main():
 exe,overlay,base=load_overlay();rows=[]
 for seed in (0,37,165,255):
  for swap in (0,1):
   for arena in (0x80100000,0xFFFFFFF0):
    r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
    r[base&0x1FFFFF:(base&0x1FFFFF)+len(overlay)]=overlay
    for a,n in RANGES:r[a:a+n]=bytes((seed+i*17+(i>>8))&255 for i in range(n))
    def sw(a,v):struct.pack_into('<I',r,a&0x1FFFFF,v&0xFFFFFFFF)
    sw(0x956EC,0);sw(0xB0E38,0x80145000 if swap else 0x80140000)
    sw(0xB0E3C,0x80140000 if swap else 0x80145000);sw(0xB0E4C,arena)
    for step in range(5):
     entry=0x8019BD78 if step in (0,4) else 0x8019BF50
     if step in (1,2,3):
      ctx=(0x8019C1F8,0x8019C270,0x80150000)[step-1]
      sw(0x19C9C0,ctx);sw(ctx,0xDEADBEEF)
      if step==3:sw(ctx+4,0x8014A000)
     calls=run(r,entry)
     if entry==0x8019BD78:
      assert [c[0] for c in calls]==[0x80074D28,0x800752AC,0x800752AC,0x80074F44,0x80074F44,0x80074DC0,0x80074D28]
      assert calls[0][1]==0 and calls[-1][1]==1
      assert calls[3][1:]==(0,0x00F00140,0,0,0) and calls[4][1:]==(0x00F00000,0x00F00140,0,0,0)
     else:assert len(calls)==1 and calls[0][0]==0x800752AC
     rows.append((seed,swap,arena,step,hash_ram(r)))
 out=['/* Generated by pe_transition_display_oracle.py --write-header. */',
      'static const uint32_t DAY1_display_ranges[][2]={'+','.join('{'+f'0x{a:X}u,0x{n:X}u'+'}' for a,n in RANGES)+'};',
      'static const struct { uint32_t seed,swap,arena,step; uint64_t hash; } DAY1_display_cases[]={']
 for seed,swap,arena,step,h in rows:out.append(f' {{{seed},{swap},0x{arena:X}u,{step},UINT64_C(0x{h:016X})}},')
 out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_transition_display_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',len(rows),'original display setup/reset history steps; explicit GPU provider contracts')
if __name__=='__main__':main()
