#!/usr/bin/env python3
"""Full original 92800 renderer: real wrappers, visibility, matrices and packets."""
import hashlib,struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_m0000i_leaves_oracle import load_overlay
from pe_transition_loader_oracle import fnv
from pe_transition_visibility_oracle import FIELDS
RANGES=((0,1024),(0x140000,0x4000),(0x150000,0x4000),(0x160000,0x10000),(0x170000,0x5000),(0x19BF00,0x2000),(0x1E4A00,0x400),(0x1EA200,0x400),(0x18F014,32),(0xA77FC,4))
SIMPLE=[0x19CC28,0x1E4A80,0x19C15C,0x19C160,0x19C164,0x19C168,0x19CDA4,0x19CDAC,0x19CDA0,0x19CDA8,0x19CDB0,0x19CDB4,0x19CDB8,0x19CDBC,0x19CDC0,0x19CDC4,0x19CDC8,0x19C180,0x1EA578,0x1EA57C,0x1EA580,0x1EA584,0x1EA588,0x1EA58C,0x19CC20,0x19CC24,0x19C148,0x19C150,0x19C14C,0x19C154]
LOD=[0x19C820,0x19C9C8,0x19C824,0x19C9CC]+list(range(0x19C3B0,0x19C400,4))+list(range(0x1E4DB0,0x1E4E00,4))
def common():
 r=bytearray(0x200000)
 def sw(a,v):struct.pack_into('<I',r,a,v&0xffffffff)
 # Every indexed submodel has its own stream mask; common source geometry.
 for index in range(84):
  h=0x140200+index*48;sw(0x140000+index*4,h-0x140000)
  for j in range(8):
   struct.pack_into('<H',r,h+j*2,1 if (index*37+85)>>j&1 else 0)
   sw(h+16+j*4,0x142000+j*0x100-h)
 for family in range(2):
  vertex=(4,4,12,16,16,16,24,28) if not family else (4,4,12,16,40,40,36,44)
  for j in range(8):
   p=0x142000+family*0x1000+j*0x100
   for i in range(0,80,4):sw(p+i,0x34402010+i*0x010101)
   for i,(x,y) in enumerate(((-100,-100),(100,-100),(-100,100),(100,100))):
    struct.pack_into('<4h',r,p+vertex[j]+i*8,x,y,0,0)
 h=0x143F00
 for j in range(8):struct.pack_into('<H',r,h+j*2,1);sw(h+16+j*4,0x143000+j*0x100-h)
 for i,g in enumerate(SIMPLE+LOD+[0x1EA260]):
  obj=0x150000+i*64;sw(g,0x80000000+obj);mo=12 if g in LOD else 8
  sw(obj,0);sw(obj+4,0x80140000);sw(obj+mo+28,1024)
  if g in LOD:sw(obj+4,2<<16|1);sw(obj+8,0x80140000);sw(obj+0x38,2000);sw(obj+0x3C,600)
  if g==0x1EA260:sw(obj+4,0x80143F00)
  sw(obj+mo+36,10<<16)
 for a in (0x19CC30,0x18F014):
  for i,v in enumerate((4096,0,4096,0,4096,0,0,0)):sw(a+i*4,v)
 sw(0x19BFF0,0x80153F00);sw(0x19C9C0,0x80153F40);sw(0x153F40,0x80160000);sw(0x153F44,0x80170000)
 for j,a in enumerate(FIELDS):sw(a,0 if j<16 else 1)
 return r

def main():
 ex,o,b=load_overlay();base=bytearray(0x200000);base[0x10000:0x10000+len(ex)-0x800]=ex[0x800:];base[b&0x1fffff:(b&0x1fffff)+len(o)]=o
 digest=hashlib.sha256(o[0x80192800-b:0x80193478-b]).hexdigest();print('source SHA256',digest,flush=True)
 assert digest=='926ba5886cd51536f747a8514c1ae8cd268b44b75aeaae8492f72112eef84690'
 init=common();common_words=[(a+i,struct.unpack_from('<I',init,a+i)[0]) for a,n in RANGES for i in range(0,n,4) if struct.unpack_from('<I',init,a+i)[0]]
 arr=lambda vs:'{'+','.join(f'0x{x&0xffffffff:X}u' for x in vs)+'}'
 out=['/* Generated by pe_transition_render_oracle.py, complete original call graph. */','static const uint32_t DAY1_transition_render_ranges[][2]={'+','.join(arr(x) for x in RANGES)+'};','static const uint32_t DAY1_transition_render_init[][2]={'+','.join(arr(x) for x in common_words)+'};','static const struct { uint32_t seed,patch_count,patches[128][2],state[28],next_rand; uint64_t hash; } DAY1_transition_render_cases[]={']
 visited=set()
 for n in range(128):
  r=bytearray(base)
  for a,length in RANGES:r[a:a+length]=init[a:a+length]
  seed=54+n*101
  for a,length in ((0,1024),(0x160000,0x10000),(0x170000,0x5000)):
   for i in range(0,length,4):struct.pack_into('<I',r,a+i,((a+i)*2654435761+seed)&0xffffffff)
  patches={}
  def sw(a,v):patches[a]=v&0xffffffff;struct.pack_into('<I',r,a,v&0xffffffff)
  def ptr(g):return struct.unpack_from('<I',r,g)[0]&0x1fffff
  sw(0x19C030,((n//3)%3)<<16);sw(0x19C034,n%3);sw(0x19C044,(n//9)%2);sw(0x19C1F0,(n//18)%3)
  sw(0x19C020,(-3,0,1,2,7,8,9,18)[n%8]);sw(0xA77FC,0x2000 if n&1 else 0);sw(0x19C0D0,0xFFF0FFF0+n)
  for i,g in enumerate(SIMPLE+LOD+[0x1EA260]):
   obj=ptr(g);mo=12 if g in LOD else 8
   sw(obj+mo+28,(384,385,600,1024,1999,2000,8000,12000)[(n+i)%8])
  for i,g in enumerate(SIMPLE[2:6]):sw(ptr(g)+0x1C,(28384,28383,28345,28354,0x7FFFFFFF,-30000)[(n+i)%6])
  sw(ptr(0x1EA578),0x24<<16 if n&1 else 0x52<<16)
  if n%4==1:sw(0x19C160,0x80000000+ptr(0x19C15C))
  if n%4==2:sw(0x19C150,0x80000000+ptr(0x1EA580)+4)
  if n%4==3:sw(0x19C14C,0x80000000+ptr(0x1EA578))
  if n&8:sw(0x18F028,3);sw(0x18F02C,5)
  if n&16:
   for a in FIELDS[12:16]:sw(a,-10000)
  state={};ctrl={24:160<<16,25:120<<16,26:1000,27:-4194,28:0x1400000,29:341,30:256}
  execute(r,0x80192800,initial_cop_control=ctrl,strict_gte_flags=True,final_gte=state,visited_pcs=visited,bios_seed=seed,instruction_budget=3000000)
  d=state['data'];cc=state['control'];vs=d[7:15]+d[16:20]+d[24:28]+list(struct.unpack('<10h',struct.pack('<5I',*cc[:5])))[:9]+cc[5:8]
  rng=seed
  for j in range(3 if (n//18)%3==1 else 1):rng=(rng*0x41C64E6D+0x3039)&0xffffffff
  h=fnv(b''.join(r[a:a+length] for a,length in RANGES))
  assert len(patches)<=128,len(patches)
  out.append(f' {{{seed},{len(patches)},'+'{'+','.join(arr(x) for x in patches.items())+'},'+arr(vs)+f',{rng>>16&32767},UINT64_C(0x{h:016X})'+'},')
  if n%16==15:print('cases',n+1,flush=True)
 out.append('};');header='\n'.join(out)+'\n'
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_transition_render_cases.h').write_text(header)
 else:assert (ROOT/'pc_port/tests/retail_transition_render_cases.h').read_text()==header
 calls={pc for pc in visited if 0x80192800<=pc<0x80193478 and struct.unpack_from('<I',o,pc-b)[0]>>26==3}
 expected={pc for pc in range(0x80192800,0x80193478,4) if struct.unpack_from('<I',o,pc-b)[0]>>26==3}
 assert calls==expected,(expected-calls)
 print(f'PASS 128 complete renderer cases, {len(calls)} call sites; {digest}')
if __name__=='__main__':main()
