#!/usr/bin/env python3
"""Four untouched original visibility routines, including DIV/BREAK prefixes."""
import hashlib,random,struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_m0000i_leaves_oracle import load_overlay
from pe_transition_loader_oracle import fnv
VECTORS=(0x19CBB0,0x19CBD0,0x19CBF0,0x19CB50)
OFFSETS=(0x19CB48,0x19CB4C,0x19CBA8,0x19CA90)
REFERENCES=(0x19CC04,0x19CC0C,0x19CC10,0x19CBC4)
LENGTHS=(0x19CBC8,0x19CC00,0x19CC08,0x19CBAC)
FIELDS=tuple(a+i*4 for a in VECTORS for i in range(3))+OFFSETS+REFERENCES+LENGTHS
ENTRIES=(0x8018FFF4,0x80190124,0x80190254,0x801904B0)
RANGES=((0x140000,16),(0x19CA90,0x190))
def main():
 ex,o,b=load_overlay();base=bytearray(0x200000);base[0x10000:0x10000+len(ex)-0x800]=ex[0x800:];base[b&0x1fffff:(b&0x1fffff)+len(o)]=o
 digest=hashlib.sha256(o[0x8018FFF4-b:0x80190998-b]).hexdigest()
 assert digest=='50dbed98c4cc99a403f96fb34619f3d06538d03a6d9902220f94fc1026047d3d'
 rng=random.Random(47);cases=[]
 for kind in range(4):
  for i in range(400):
   data=[rng.getrandbits(32) for _ in FIELDS];p=[rng.getrandbits(32) for _ in range(3)];radius=rng.getrandbits(32)
   cases.append((kind,i%3,radius,p,data))
  for side in range(4):
   for value in (0,1,-1,29,30,31,0x7FFFFFFF,0x80000000):
    for length in (0,1,-1,2):
     data=[0]*24;p=[1,0,0]
     for j in range(4):data[j*3]=1;data[16+j]=1;data[20+j]=1
     data[side*3]=value&0xffffffff;data[16+side]=0;data[20+side]=length&0xffffffff
     cases.append((kind,0,0,p,data))
 # Rejection of an earlier plane must not bypass a later trap.
 for kind,planes in ((2,2),(3,4)):
  for side in range(1,planes):
   data=[0]*24
   for j in range(4):data[j*3]=1;data[16+j]=1;data[20+j]=1
   data[0]=100;data[16]=0;data[side*3]=0;data[16+side]=0;data[20+side]=0
   cases.append((kind,0,0,[1,0,0],data))
 # Derive actual plane records by running original8F92C on camera geometry.
 for i in range(60):
  r=bytearray(base);struct.pack_into('<I',r,0x963E8,0)
  struct.pack_into('<9h',r,0x19CDF0,4096,0,0,0,4096,0,0,0,4096)
  struct.pack_into('<3i',r,0x19CE04,0,0,0)
  for j,(x,y) in enumerate(((-320,-240),(320,-240),(-320,240),(320,240))):struct.pack_into('<4h',r,0x19BFD0+j*8,x,y,1000,0)
  struct.pack_into('<3i',r,0x140000,i-30,0,0)
  execute(r,0x8018F92C,(0x80140000,))
  data=[struct.unpack_from('<I',r,a)[0] for a in FIELDS]
  for kind in range(4):cases.append((kind,0,i-30,[rng.randrange(-3000,3001)&0xffffffff for _ in range(3)],data))
 out=['/* Original visibility graphs; generated by pe_transition_visibility_oracle.py. */','static const uint32_t DAY1_visibility_fields[]={'+','.join(f'0x{a:X}u' for a in FIELDS)+'};','static const struct { unsigned kind,alias; uint32_t radius,point[3],fields[24],ret; unsigned trap; uint64_t hash; } DAY1_visibility_cases[]={']
 traps=0;accepted=0
 for kind,alias,radius,p,data in cases:
  r=bytearray(base)
  for a,n in RANGES:r[a:a+n]=bytes((i*17+5)&255 for i in range(n))
  for a,v in zip(FIELDS,data):struct.pack_into('<I',r,a,v)
  address=(0x140000,0x19CBB0,0x19CB48)[alias]
  if kind==1:struct.pack_into('<3H',r,address,*(x&65535 for x in p))
  else:struct.pack_into('<3I',r,address,*p)
  before=bytes(r);trap=0;ret=0
  try:ret=execute(r,ENTRIES[kind],(0x80000000+address,radius&0xffffffff))[2]
  except AssertionError as exc:
   d=exc.args[0]
   assert kind>=2 and isinstance(d,tuple),exc
   if d[0]=='division by zero in original fixture':pc=int(d[1],16)
   else:
    pc=int(d[0],16);assert d[1]=='0x6000d',exc
   assert 0x80190254<=pc<0x80190998,exc
   trap=1;traps+=1
  assert r[:0x1f0000]==before[:0x1f0000],'visibility wrote persistent RAM'
  h=fnv(b''.join(r[a:a+n] for a,n in RANGES));accepted+=ret==1 and not trap
  arr=lambda xs:'{'+','.join(f'0x{x&0xffffffff:X}u' for x in xs)+'}'
  out.append(f' {{{kind},{alias},0x{radius&0xffffffff:X}u,'+arr(p)+','+arr(data)+f',0x{ret:X}u,{trap},UINT64_C(0x{h:016X})'+'},')
 out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_transition_visibility_cases.h').write_text('\n'.join(out)+'\n')
 print(f'PASS: {len(cases)} original visibility cases; {traps} DIV/BREAK prefixes; {accepted} accepted; source SHA256 {digest}')
if __name__=='__main__':main()
