#!/usr/bin/env python3
"""Untouched original full transition view, concatenation and Euler graphs."""
import hashlib,random,struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_m0000i_leaves_oracle import load_overlay
from pe_transition_loader_oracle import fnv
RANGES=((0x140000,256),(0x19BFC4,8),(0x19C330,12),(0x19C810,12),(0x19CC30,32),(0x19CDF0,32))
def main():
 ex,o,b=load_overlay();base=bytearray(0x200000);base[0x10000:0x10000+len(ex)-0x800]=ex[0x800:];base[b&0x1fffff:(b&0x1fffff)+len(o)]=o
 for a,z,h in ((0x8018F05C,0x8018F344,'1602c7761c55ad4056272d59a2a2ef2bdd55f0ffe793126428f7e9f178da5435'),(0x800787D4,0x80078934,'484fff1d2984fac9730786048ad50065c006672118c2d6b4698dfb787d7b155c'),(0x800799E4,0x80079C70,'eb29f1f088bca83efc058df957cfe2cd49bcfbd3a215d41df7986888d2b9bba3')):
  assert hashlib.sha256(base[a&0x1fffff:z&0x1fffff]).hexdigest()==h
 out=['/* Generated by pe_transition_view_oracle.py from original instructions. */','static const uint8_t DAY1_view_tables[]={'+','.join(map(str,base[0x95F00:0x9B000]))+'};','static const uint8_t DAY1_view_template[]={'+','.join(map(str,base[0x18EFF4:0x18F014]))+'};','static const struct { unsigned kind,seed,offset,trap; uint32_t input[6],ret,state[18]; uint64_t hash; } DAY1_view_cases[]={']
 rng=random.Random(43);cases=[]
 for i in range(300):
  v=tuple(rng.randrange(-16000,16001) for _ in range(6))
  if i<20:v=((0,0,0,0,0,0),(0,0,0,0,0,1000),(0,0,0,0,1000,0),(10000,2000,-3000,-5000,7000,3000),(0,0,0,32767,32767,32767))[i%5]
  cases.append((0,i&255,64,v))
 for i in range(100):cases.append((1,i, (0,4,32,36,64)[i%5],tuple(rng.getrandbits(32) for _ in range(6))))
 for i in range(24):
  v=[0]*6;v[i%3]=0x80000000 if i&1 else 0x7FFFFFFF;v[3+i%3]=0xFFFF8000 if i&1 else 32767
  cases.append((1,128+i,(0,32,64)[(i//3)%3],tuple(v)))
 for i in range(100):cases.append((2,i,(0,4,16,64)[i%4],tuple(rng.getrandbits(32) for _ in range(6))))
 traps=0
 for kind,seed,offset,v in cases:
  r=bytearray(base)
  for a,n in RANGES:r[a:a+n]=bytes((seed+i*17)&255 for i in range(n))
  if kind==0:
   struct.pack_into('<3I',r,0x19C330,*(x&0xFFFFFFFF for x in v[:3]));struct.pack_into('<3I',r,0x19C810,*(x&0xFFFFFFFF for x in v[3:]))
  elif kind==1:
   for i in range(6):struct.pack_into('<I',r,0x140000+(20+i*4 if i<3 else 40+i*4),v[i])
   if seed>=128:
    for a in (0x140000,0x140020):struct.pack_into('<9h',r,a,4096,0,0,0,4096,0,0,0,4096)
  else:struct.pack_into('<3H',r,0x140000,*(x&65535 for x in v[:3]))
  before=bytes(r)
  code=[0x3C098014,0x35292100,(43<<26)|(9<<21)|(2<<16)]
  for j,reg in enumerate(range(8)):code.extend(((18<<26)|(2<<21)|(8<<16)|(reg<<11),(43<<26)|(9<<21)|(8<<16)|(4+j*4)))
  for j,reg in enumerate((8,9,10,11,20,21,22,25,26,27)):code.extend(((18<<26)|(8<<16)|(reg<<11),(43<<26)|(9<<21)|(8<<16)|(36+j*4)))
  code.extend((8,0))
  for j,w in enumerate(code):struct.pack_into('<I',r,0x142000+j*4,w)
  trap=0;ret=0;state=[0]*18
  try:
   execute(r,(0x8018F05C,0x800787D4,0x800799E4)[kind],() if kind==0 else ((0x80140000,0x80140020,0x80140000+offset) if kind==1 else (0x80140000,0x80140000+offset)),initial_regs={31:0x80142000})
   ret=struct.unpack_from('<I',r,0x142100)[0];state=list(struct.unpack_from('<18I',r,0x142104));state[4]&=65535
   for i in range(8,12):state[i]&=65535
  except AssertionError as exc:
   assert exc.args==('retail signed arithmetic overflow',),exc
   trap=1;traps+=1
  check=bytearray(r[:0x1F0000]);check[0x142000:0x142180]=before[0x142000:0x142180]
  for a,n in RANGES:check[a:a+n]=before[a:a+n]
  assert check==before[:0x1F0000],'unexpected persistent write'
  h=fnv(b''.join(r[a:a+n] for a,n in RANGES))
  out.append(f' {{{kind},{seed},{offset},{trap},{{'+','.join(f'0x{x&0xFFFFFFFF:X}u' for x in v)+f'}},0x{ret:X}u,{{'+','.join(f'0x{x:X}u' for x in state)+f'}},UINT64_C(0x{h:016X})}},')
 out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_transition_view_cases.h').write_text('\n'.join(out)+'\n')
 print(f'PASS: {len(cases)} original whole camera/SDK graphs; {traps} overflow prefixes')
if __name__=='__main__':main()
