#!/usr/bin/env python3
"""Original M0000I object-pool histories, including all constructor callees."""
import hashlib,struct,sys
from pe_m0000i_leaves_oracle import load_overlay
from pe_battle_hud_oracle import ROOT,execute
RANGES=((0x19C340,0xB60),(0x1E4A88,0x5DA4),(0x140000,0x400))
RETURNS={0x801915DC,0x80191754,0x80190AEC,0x80190B78,0x80190C1C,0x8019959C}
CODE_RANGES=((0x80190998,0x80190D3C),(0x80191580,0x80191854),(0x8019959C,0x801995BC))

def fingerprint(r):
 h=14695981039346656037
 for a,n in RANGES:
  for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
 return h

def fixture(exe,overlay,base,seed):
 r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
 r[base&0x1FFFFF:(base&0x1FFFFF)+len(overlay)]=overlay
 for a,n in RANGES:
  for i in range(n):r[a+i]=(seed+i*17+(i>>8))&255
 for i,index in enumerate((-1,0,1,2)):
  struct.pack_into('<I',r,0x140080+index*4,0x100+i*0x40)
  struct.pack_into('<I',r,0x140080+0x100+i*0x40+0x30,0xABCD0000+i*0x1234)
 return r

def main():
 exe,overlay,base=load_overlay()
 for a,b in CODE_RANGES:
  print(hex(a),hex(b),(b-a)//4,hashlib.sha256(overlay[a-base:b-base]).hexdigest())
 steps=[]
 def history(seed):
  r=fixture(exe,overlay,base,seed);first=True
  def run(entry,*args):
   nonlocal first
   before=bytes(r)
   regs=execute(r,entry,args,instruction_budget=100000)
   outside=bytearray(r[:0x1F0000])
   for a,n in RANGES:outside[a:a+n]=before[a:a+n]
   assert outside==before[:0x1F0000],f'uncompared persistent write {entry:X}'
   ret=regs[2] if entry in RETURNS else 0
   steps.append((int(first),seed,entry,args,ret,fingerprint(r)))
   first=False
   return ret
  return run
 for seed in (0,0xA5,0x37):
  run=history(seed);run(0x80190998)
  # Every real pool slot, linked iteration, head/middle/tail release and LIFO reuse.
  ids=[run(0x801915DC) for _ in range(200)]
  assert ids==list(range(200))
  run(0x80191740)
  assert [run(0x80191754) for _ in range(200)]==[0x801E4E00+i*108 for i in ids]
  assert run(0x80191754)==0
  removed=(0,99,199,100,1)
  for i in removed:run(0x80191678,i|0x12340000)
  assert [run(0x801915DC) for _ in removed]==list(reversed(removed))
  # Drain in a permutation so both neighboring-link rewrites and the final
  # empty-list sentinel are exercised, then reuse every freed slot.
  release_order=[(i*73)%200 for i in range(200)]
  for i in release_order:run(0x80191678,i)
  run(0x80191740);assert run(0x80191754)==0
  assert [run(0x801915DC) for _ in release_order]==list(reversed(release_order))
  # Reinitializing restores lists while retaining untouched record bytes.
  run(0x80190998);run(0x80191740);assert run(0x80191754)==0
  # Constructors link depth one/two records, preserve partial field writes,
  # truncate indices, and load metadata through the original relative table.
  root=0x8019C340
  parent=run(0x80190AEC,root,0x87654321)
  children=[]
  for index in (0,1,2,0x12340001,0xFFFFFFFF):
   children.append(run(0x80190B78,parent,index,0x80140080))
   children.append(run(0x80190C1C,parent,index,0xABCD1234,0x5678FFFF,
                       0x80000000,0xFFFFFFFF,0x80140080))
  siblings=[run(0x80190AEC,root,i) for i in range(3)]
  for object in (children[0],children[4],children[-1],siblings[-1],siblings[0]):run(0x80190D08,object)
  for i in range(5):run(0x80190B78,parent,i%3,0x80140080)
  run(0x80191740)
  for _ in range(15):
   if not run(0x80191754):break
  for index in (0,1,2,0xFFFFFFFF):run(0x8019959C,0x80140080,index)
  run(0x80191580,0x80140200)
 out=['/* Generated by pe_transition_pool_oracle.py --write-header. */',
      'static const uint32_t DAY1_pool_ranges[][2]={']
 out += [f'    {{0x{a:X}u,0x{n:X}u}},' for a,n in RANGES];out+=['};']
 out+=['static const struct { unsigned reset,seed; uint32_t entry,args[7],ret; uint64_t hash; } DAY1_pool_steps[]={']
 for reset,seed,entry,args,ret,h in steps:
  out.append(f'    {{{reset},{seed},0x{entry:X}u,{{'+','.join(f'0x{v:X}u' for v in (*args,*(0 for _ in range(7-len(args)))))+f'}},0x{ret:X}u,UINT64_C(0x{h:016X})}},')
 out+=['};']
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_transition_pool_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',len(steps),'original pool history steps')
if __name__=='__main__':main()
