#!/usr/bin/env python3
"""OriginalF55C and original ratan2 execute without provider substitution."""
import hashlib,itertools,struct,sys
from pe_battle_hud_oracle import ROOT,execute
from pe_m0000i_leaves_oracle import load_overlay
from pe_transition_loader_oracle import fnv
RANGES=((0x140000,512),(0x150000,32),(0x19BFCC,4))
def main():
 exe,overlay,base=load_overlay();body=overlay[0x8018F55C-base:0x8018F92C-base]
 assert hashlib.sha256(body).hexdigest()=='6ac9986399afc33fe8e6f847b18740745eb61dad3ce8d70ca91de52ea741830f'
 for time in (0,256):
  r=bytearray(0x200000);r[base&0x1FFFFF:(base&0x1FFFFF)+len(overlay)]=overlay
  struct.pack_into('<I',r,0x140000,16);struct.pack_into('<H',r,0x140016,2)
  struct.pack_into('<I',r,0x1FF010,0x80150010)
  regs=execute(r,0x8018F55C,(time,0,0x80140000,0x80150000),stop_at=(0x8018F5C8,))
  assert regs[4]==0 and r[0x19BFCC]==bool(time) and r[0x150000:0x150018]==bytes(24)
 table=exe[0x8AEEC:0x8AEEC+2050];rows=[]
 for seed,count,time,alias in itertools.product(range(12),(0,1,3,4,7,-3),(0,1,127,255,256,511,1024,1280,0x800000FF,0xFFFFFFFF),range(2)):
  r=bytearray(0x200000);r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:];r[base&0x1FFFFF:(base&0x1FFFFF)+len(overlay)]=overlay
  for a,n in RANGES:r[a:a+n]=bytes((seed+i*17)&255 for i in range(n))
  rec=0x140041+seed%4;struct.pack_into('<I',r,0x14000C,rec-0x140000);struct.pack_into('<H',r,rec+6,count&65535)
  rand=seed+1
  for i in range(16):
   for j in range(3):
    rand=(rand*1664525+1013904223)&0xFFFFFFFF;struct.pack_into('<H',r,rec+8+i*8+j*2,rand>>16)
  pos=0x80150000 if not alias else 0x80000000+rec+8;rot=0x80150010 if not alias else pos+2
  # The fifth argument is passed at the caller's SP+16.
  struct.pack_into('<I',r,0x1FF010,rot)
  regs=execute(r,0x8018F55C,(time,3,0x80140000,pos))
  result=regs[2];h=fnv(b''.join(r[a:a+n] for a,n in RANGES));rows.append((seed,count,time,alias,result,h))
 out=['/* OriginalF55C + original79FB4; generated by pe_transition_path_oracle.py. */','static const uint16_t DAY1_path_atan[]={'+','.join(str(x) for x in struct.unpack('<1025H',table))+'};','static const struct { uint32_t seed; int count; uint32_t time,alias,result; uint64_t hash; } DAY1_path_cases[]={']
 for seed,count,time,alias,result,h in rows:out.append(f' {{{seed},{count},0x{time:X}u,{alias},0x{result:X}u,UINT64_C(0x{h:016X})}},')
 out.append('};')
 if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_transition_path_cases.h').write_text('\n'.join(out)+'\n')
 print('PASS:',len(rows),'original path interpolation cases, including aliased outputs')
if __name__=='__main__':main()
