#!/usr/bin/env python3
"""Full original transition-position -> audio FIFO -> effect voice execution.

Pinned retail overlay/EXE; no substituted callees. The Python GTE executes
original COP2 operations; this does not establish audible SPU synthesis.
"""
import hashlib
import struct
import sys
from pe_m0000i_leaves_oracle import load_overlay
from pe_battle_hud_oracle import ROOT, execute

RANGES=((0x963E8,0x64),(0x9D268,4),(0x9D2F4,4),(0xB0DCC,8),
        (0xB8628,72),(0xBC000,0xD50),(0xBCD50,4),(0xBCD80,0x20),
        (0xBCF94,4),(0xBCFA4,8),(0x19CC30,0x20),(0x140000,12))
CONTROL={0:4096,1:0,2:4096,3:0,4:4096,5:11,6:0xFFFFFFEA,7:999}


def fingerprint(r):
    h=14695981039346656037
    for a,n in RANGES:
        for b in r[a:a+n]:h=((h^b)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h


def main():
    exe,overlay,base=load_overlay()
    code=overlay[0x80191EFC-base:0x80191FE8-base]
    print('80191EFC',len(code)//4,hashlib.sha256(code).hexdigest())
    cases=[];patches=[];common=None
    poses=((0,0,0),(-400,0,0),(400,0,0),(10000,0,0),(-10000,0,0),
           (0,400,8000),(0,-400,-2000),(0x12340080,0xFFFF0001,0x80000100))
    fixtures=[]
    for matrix in (0,1):
        for position in poses:
            for handle in (5,0x405,0x10405,0xFFFFFFFF):
                fixtures.append((0x80191EFC,(handle,0x80140000),matrix,position))
    # Direct producers additionally verify group masking and untouched fields.
    for entry in (0x800868F0,0x80086A28):
        for handle in (0,0x405,0xFFFFFFFF):
            for group in (0,0xFF,0x120000FF,0xFFFFFFFF):
                for value in (0,127,128,255,0xFFFFFFFF):
                    fixtures.append((entry,(handle,group,value),0,(0,0,0)))
    for k,(entry,args,matrix,position) in enumerate(fixtures):
        r=bytearray(0x200000)
        r[0x10000:0x10000+len(exe)-0x800]=exe[0x800:]
        r[base&0x1FFFFF:(base&0x1FFFFF)+len(overlay)]=overlay
        for a,n in RANGES:r[a:a+n]=bytes(n)
        def sw(a,v):struct.pack_into('<I',r,a,v&0xFFFFFFFF)
        def sh(a,v):struct.pack_into('<H',r,a,v&65535)
        sw(0x963E8,matrix*32)
        sw(0xBCFA4,0x80145678);sw(0xBCFA8,0x80146780)
        sh(0xBCF94,160);sh(0xBCF96,112)
        r[0xB0DCE:0xB0DD0]=bytes((16,64));sh(0xB0DD0,0);sh(0xB0DD2,4095)
        cells=(4096,0,0,0,4096,0,0,0,4096) if not matrix else (0,0,4096,0,4096,0,-4096,0,0)
        for i,v in enumerate(cells):sh(0x19CC30+i*2,v)
        for i,v in enumerate((matrix*100,-matrix*20,1024)):sw(0x19CC44+i*4,v)
        for i,v in enumerate(position):sw(0x140000+i*4,v)
        for i in range(8):sw(0xBCD80+i*4,0x12345600+i)
        sw(0xBCD50,0xFFF000)
        for i in range(12):
            a=0xBC000+i*0x11C
            sw(a+0x28,0x400+i if i<6 else i-6)
            sw(a+0x2C,0xFF if i%2 else 0x2000000)
            sh(a+0x74,7);sh(a+0x76,0x3456);sh(a+0x78,9);sh(a+0xD8,0x4567)
            sw(a+0xF4,0xABC00000+i*4)
        initial=bytes(r)
        seed={a+i:struct.unpack_from('<I',r,a+i)[0] for a,n in RANGES for i in range(0,n,4)}
        if common is None:common={a:v for a,v in seed.items() if v}
        first=len(patches);patches.extend((a,v) for a,v in seed.items() if v!=common.get(a,0))
        execute(r,entry,args,initial_cop_control=CONTROL)
        queued=fingerprint(r)
        execute(r,0x8008CA84)
        outside=bytearray(r[:0x1F0000])
        for a,n in RANGES:outside[a:a+n]=initial[a:a+n]
        if outside!=initial[:0x1F0000]:
            raise AssertionError([hex(i) for i,(a,b) in enumerate(zip(outside,initial)) if a!=b][:20])
        cases.append((first,len(patches),entry,args,queued,fingerprint(r)))
        print(k,hex(entry),hex(queued),hex(cases[-1][-1]))
    out=['/* Generated by pe_transition_sound_oracle.py --write-header. */']
    for name,rows in (('ranges',RANGES),('common',sorted(common.items())),('patches',patches)):
        out.append(f'static const uint32_t DAY1_ts_{name}[][2]={{')
        out.extend(f'    {{0x{a:X}u,0x{b:X}u}},' for a,b in rows);out.append('};')
    out.append('static const struct { unsigned first,end; uint32_t entry,args[3]; uint64_t queued,consumed; } DAY1_ts_cases[]={')
    for first,end,entry,args,queued,consumed in cases:
        arg=list(args)+[0]*(3-len(args))
        out.append(f'    {{{first},{end},0x{entry:X}u,{{'+','.join(f'0x{v:X}u' for v in arg)+f'}},UINT64_C(0x{queued:016X}),UINT64_C(0x{consumed:016X})}},')
    out.append('};')
    if '--write-header' in sys.argv:(ROOT/'pc_port/tests/retail_transition_sound_cases.h').write_text('\n'.join(out)+'\n')
    print('PASS:',len(cases),'original transition sound/producer graphs')

if __name__=='__main__':main()
