/* Provider traces generated by executing the original overlay, not the port. */
#include "retail_transition_packages_cases.h"
#include "game_port.h"
static unsigned package_stop_at;
static unsigned package_current,package_calls,package_phase,package_issues[2],package_polls[2];
static uint64_t package_trace;
static void package_call(uint32_t fn,uint32_t a,uint32_t b,uint32_t c)
{
    uint32_t words[]={fn,a,b,c};
    for(unsigned i=0;i<4;i++)for(unsigned j=0;j<4;j++)
        package_trace=byte(package_trace,(uint8_t)(words[i]>>(j*8)));
    if(++package_calls>=100){fprintf(stderr,"package provider overflow\n");exit(1);}
}
static void package_mutate(void)
{
    if(package_stop_at==package_calls)PE_Port_RequestStop(PE_PORT_STOP_UNRESOLVED_BOUNDARY);
    if(!DAY1_package_cases[package_current].mutate)return;
    PE_StoreU32(0x800B0DD8u,PE_LoadU32(0x800B0DD8u)+17u);
    for(unsigned i=0;i<4;i++)PE_StoreU16(0x80093170u+i*2,
        (uint16_t)(PE_LoadU16(0x80093170u+i*2)+i+1));
    PE_StoreU8(0x8019C1F0u,PE_LoadU8(0x8019C1F0u)^1u);
}
int __wrap_func_8006E6A8(int lba,pe_addr_t dest,int sectors)
{
    package_call(0x8006E6A8u,(uint32_t)lba,dest,(uint32_t)sectors);
    if(dest==0x801D0260u)package_phase=0;
    else if(dest==0x8019CE10u)package_phase=1;
    else{fprintf(stderr,"unexpected package destination\n");exit(1);}
    int result=(DAY1_package_cases[package_current].profile&1)&&package_issues[package_phase]<2?-1:-2;
    package_issues[package_phase]++;
    package_mutate();return result;
}
int __wrap_func_8006E7E8(void)
{
    static const int simple[]={2,-2,0},retry[]={2,-2,-1,1,0};
    package_call(0x8006E7E8u,0,0,0);
    unsigned i=package_polls[package_phase]++;
    unsigned retrying=DAY1_package_cases[package_current].profile&2;
    if(i>=(retrying?5u:3u)){fprintf(stderr,"unexpected package poll\n");exit(1);}
    int result=retrying?retry[i]:simple[i];
    package_mutate();return result;
}
static int test_transition_packages(void)
{
    for(package_current=0;package_current<sizeof(DAY1_package_cases)/sizeof(DAY1_package_cases[0]);package_current++){
        PE_RamReset();
        unsigned edge=DAY1_package_cases[package_current].edge;
        const uint16_t regular[]={1975,2016,2105,2205},limits[]={65535,0,65535,1};
        for(unsigned i=0;i<4;i++)PE_StoreU16(0x80093170u+i*2,edge?limits[i]:regular[i]);
        PE_StoreU32(0x800B0DD8u,edge?0xFFFFFFF0u:1013u);
        PE_StoreU32(0x8019C1F0u,DAY1_package_cases[package_current].flag);
        package_calls=package_phase=0;package_trace=UINT64_C(14695981039346656037);
        for(unsigned i=0;i<2;i++)package_issues[i]=package_polls[i]=0;
        PE_Port_RunControlReset();
        func_80191C94();
        uint64_t state=UINT64_C(14695981039346656037);
        const uint32_t ranges[][2]={{0x80093170u,8},{0x800B0DD8u,4},{0x8019C1F0u,4}};
        for(unsigned i=0;i<3;i++)for(unsigned j=0;j<ranges[i][1];j++)state=byte(state,PE_LoadU8(ranges[i][0]+j));
        if(package_calls!=DAY1_package_cases[package_current].calls || package_trace!=DAY1_package_cases[package_current].trace || state!=DAY1_package_cases[package_current].state){
            fprintf(stderr,"package case%u calls%u/%u trace%016llX/%016llX state%016llX/%016llX\n",package_current,package_calls,DAY1_package_cases[package_current].calls,(unsigned long long)package_trace,(unsigned long long)DAY1_package_cases[package_current].trace,(unsigned long long)state,(unsigned long long)DAY1_package_cases[package_current].state);return 1;
        }
    }
    printf("PASS: %u original package-loader control-flow cases\n",package_current);
    /* Every provider boundary in a retrying two-stage run must stop promptly. */
    package_current=12;
    for(package_stop_at=1;package_stop_at<=DAY1_package_cases[package_current].calls;package_stop_at++){
        package_calls=package_phase=0;package_trace=UINT64_C(14695981039346656037);
        for(unsigned i=0;i<2;i++)package_issues[i]=package_polls[i]=0;
        PE_Port_RunControlReset();func_80191C94();
        if(package_calls!=package_stop_at || !PE_Port_ShouldStop()){
            fprintf(stderr,"package boundary%u advanced to%u calls\n",package_stop_at,package_calls);return 1;
        }
    }
    printf("PASS: %u package provider stop prefixes\n",package_stop_at-1);
    package_stop_at=0;PE_Port_RunControlReset();return 0;
}
