/*
 * Guest-code dispatch (overlay-port mechanism step 3,
 * docs/ai_context/PC_PORT_FROM_DECOMP.md §3b).
 *
 * A retail call through a guest code pointer (a callback slot, a handler
 * word, a function table, an overlay behaviour table) jumps to whatever code
 * sits at that 32-bit address.  PE_GuestCall reproduces that: it resolves the
 * address to the host implementation of the function that is there and calls
 * it, or — when nothing is known to be there — records a loud boundary
 * carrying the address (never a guess) and returns 0.
 *
 * Resolution (PE_GuestCode_Resolve):
 *   * EXE addresses -> the generated EXE table (every generated EXE leaf and
 *     every canonical-header pc_port function with an all-integer host
 *     signature);
 *   * overlay addresses -> the overlay tables.  Several overlays can have a
 *     function at the same address (rooms, ovl_03D2 and ovl_0700 share an
 *     arena), so a candidate is taken only when
 *       (a) the loader declared its overlay resident (PE_Overlay_SetResident,
 *           optionally verified against the committed manifest SHA-1), or
 *       (b) the generator recorded a fingerprint of the leaf's retail bytes
 *           and guest RAM at that address matches it;
 *     otherwise the address is unresolved (loud).
 * Tables are generated by tools/analysis/gen_overlay_ports.py into
 * pc_port/game/decomp_ovl/_dispatch/zz_dispatch_port.c.
 */
#ifndef PE_GUESTCODE_H
#define PE_GUESTCODE_H
#include <stddef.h>
#include <stdint.h>
#include "pe_guest_ram.h"

typedef int (*PeGuestThunk)(uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3);

typedef struct {
    uint32_t vma;          /* retail entry address */
    uint32_t size;         /* retail byte size (fingerprint window) */
    uint32_t fingerprint;  /* FNV-1a of the retail bytes, 0 = none */
    PeGuestThunk thunk;
    const char *symbol;    /* host symbol, for diagnostics */
} PeGuestCodeEntry;

typedef struct {
    const char *id;        /* "exe" or the overlay id */
    uint32_t lo, hi;       /* load window [lo, hi) */
    const char *sha1;      /* committed blob SHA-1 (overlays), or NULL */
    uint32_t load_size;    /* bytes hashed for sha1 */
    const PeGuestCodeEntry *entries;
    unsigned count;
} PeGuestCodeTable;

/* The generated registry (pc_port/game/decomp_ovl/_dispatch/zz_dispatch.c)
 * is linked only into the full runtime executables (parasite-eve-port,
 * pe-native-tests), which call PE_GuestCode_InstallGenerated() at startup.
 * Linking it into the static library would pull every thunk's object (the
 * whole port) into every small test executable.  Without a registry every
 * guest call is a loud boundary. */
void PE_GuestCode_SetRegistry(const PeGuestCodeTable *const *tables, unsigned count);
void PE_GuestCode_InstallGenerated(void);   /* defined in zz_dispatch.c */

/* Residency: declare which overlay a loader just placed in guest RAM.
 * Clears every overlay whose window overlaps.  Returns 0 on success, -1 for
 * an unknown overlay id. */
int PE_Overlay_SetResident(const char *ovl);
/* Same, after checking the SHA-1 of guest RAM [lo, lo+load_size) against
 * the committed manifest hash; returns -2 (and sets nothing) on mismatch. */
int PE_Overlay_SetResidentVerified(const char *ovl);
int PE_Overlay_IsResident(const char *ovl);
void PE_Overlay_ResetResidency(void);

/* NULL when the address cannot be resolved with certainty. */
const PeGuestCodeEntry *PE_GuestCode_Resolve(pe_addr_t addr);

/* The retail `jalr`: call the code at `fn` with up to four argument
 * registers.  Unresolved -> loud boundary (site, fn, args), returns 0. */
int PE_GuestCall(const char *site, pe_addr_t fn, unsigned arity,
                 uintptr_t a0, uintptr_t a1, uintptr_t a2, uintptr_t a3);

/* Exposed for tests. */
uint32_t PE_GuestCode_Fnv1a(pe_addr_t addr, uint32_t size);
void PE_GuestCode_Sha1Hex(pe_addr_t addr, uint32_t size, char out[41]);

#endif
