/* MDEC tables, software pixels and deferred DMA for the libpress path. */
#include "pe_mdec.h"

#include "pe_gpu.h"
#include "game_port.h"
#include "pe_bootstrap.h"
#include "pe_irq_delivery.h"

#include <string.h>

#define MDEC_DMA_CHCR_INPUT 0x01000201u

static PeMdecState g_mdec;

static uint8_t g_quant[2][64];
static int16_t g_scale[64];
static unsigned g_tables;
static int g_decode_valid,g_input_pending;
static uint32_t g_output_bytes;
static uint16_t g_input[131070];
static uint32_t g_input_pos,g_input_count,g_decode_command,g_macroblocks;
static uint8_t g_pixels[768];
static uint32_t g_pixel_pos,g_pixel_count;
/* Output of a previous command still ahead of the current one in the
 * data-out FIFO (see MdecBeginCommand). */
#define MDEC_STALE_MACROBLOCKS 64u
static uint8_t g_stale[MDEC_STALE_MACROBLOCKS*768u];
static uint32_t g_stale_pos,g_stale_count;
static int g_drain;

static int MdecBoundary(const char *name,uint32_t value)
{
    Bootstrap_ReturnVoid1(name,"MDEC_decode",value);
    PE_Port_RequestStop(PE_PORT_STOP_UNRESOLVED_BOUNDARY);return 0;
}
/* Defined floor division avoids implementation-defined signed right shifts. */
static int32_t MdecShift(int64_t value,unsigned bits)
{
    int64_t divisor=INT64_C(1)<<bits;
    return (int32_t)(value>=0?value/divisor:-((-value+divisor-1)/divisor));
}
static int32_t MdecSigned(unsigned value,unsigned bits)
{
    unsigned mask=(1u<<bits)-1u;value&=mask;
    return value&(1u<<(bits-1u))?(int32_t)value-(int32_t)(1u<<bits):(int32_t)value;
}
static int32_t MdecClamp(int32_t value,int32_t low,int32_t high)
{
    return value<low?low:value>high?high:value;
}
static void MdecIDCT(int32_t block[64])
{
    int32_t temporary[64];
    for(unsigned pass=0;pass<2u;pass++) {
        for(unsigned y=0;y<8u;y++) for(unsigned x=0;x<8u;x++) {
            int64_t sum=0;
            for(unsigned z=0;z<8u;z++) sum+=(int64_t)block[y+z*8u]*MdecShift(g_scale[x+z*8u],3u);
            temporary[x+y*8u]=MdecShift(sum+4095,13u);
        }
        memcpy(block,temporary,sizeof(temporary));
    }
    for(unsigned i=0;i<64u;i++) block[i]=MdecSigned((unsigned)block[i],9u);
}
static int MdecBlock(int32_t block[64],const uint8_t quant[64])
{
    /* Zigzag traversal generated by diagonals, with the first AC at (1,0). */
    unsigned scan[64],index=0;
    for(unsigned diagonal=0;diagonal<15u;diagonal++) {
        for(unsigned n=0;n<8u;n++) {
            unsigned y=(diagonal&1u)?n:7u-n;
            if(diagonal>=y && diagonal-y<8u) scan[index++]=y*8u+diagonal-y;
        }
    }
    memset(block,0,64u*sizeof(*block));
    while(g_input_pos<g_input_count && g_input[g_input_pos]==0xFE00u) g_input_pos++;
    if(g_input_pos==g_input_count) return g_drain?0:MdecBoundary("MDEC_missing_block",g_input_pos);
    uint16_t code=g_input[g_input_pos++];unsigned scale=code>>10u,k=0;
    for(;;) {
        int32_t value=MdecSigned(code,10u);
        if(!scale) value*=2;
        else if(!k) value*=quant[0];
        else value=MdecShift((int64_t)value*quant[k]*scale+4,3u);
        block[scale?scan[k]:k]=MdecClamp(value,-1024,1023);
        if(g_input_pos==g_input_count) return g_drain?0:MdecBoundary("MDEC_unterminated_block",g_input_pos);
        code=g_input[g_input_pos++];k+=(code>>10u)+1u;
        if(k>=64u) break;
    }
    MdecIDCT(block);return 1;
}
static uint8_t MdecComponent(int32_t value)
{
    int32_t clamped=MdecClamp(value,-128,127);
    return (uint8_t)clamped^((g_decode_command&0x04000000u)?0u:0x80u);
}
static int MdecMacroblock(void)
{
    unsigned depth=(g_decode_command>>27u)&3u;
    int32_t blocks[6][64];
    unsigned count=depth<2u?1u:6u;
    for(unsigned i=0;i<count;i++) if(!MdecBlock(blocks[i],g_quant[count==6u && i<2u])) return 0;
    g_pixel_pos=0;g_pixel_count=0;
    if(depth<2u) {
        for(unsigned i=0;i<64u;i++) {
            uint8_t value=MdecComponent(blocks[0][i]);
            if(depth) g_pixels[g_pixel_count++]=value;
            else if(!(i&1u)) g_pixels[g_pixel_count]=value>>4u;
            else g_pixels[g_pixel_count++]|=(uint8_t)(value&0xF0u);
        }
    } else {
        for(unsigned y=0;y<16u;y++) for(unsigned x=0;x<16u;x++) {
            unsigned uv=(y/2u)*8u+x/2u,yi=2u+(y/8u)*2u+x/8u;
            int32_t lum=blocks[yi][(y&7u)*8u+(x&7u)],cr=blocks[0][uv],cb=blocks[1][uv];
            uint8_t red=MdecComponent(lum+MdecShift(359*cr+128,8u));
            uint8_t green=MdecComponent(lum+MdecShift(-88*cb-183*cr+128,8u));
            uint8_t blue=MdecComponent(lum+MdecShift(454*cb+128,8u));
            if(depth==2u) {g_pixels[g_pixel_count++]=red;g_pixels[g_pixel_count++]=green;g_pixels[g_pixel_count++]=blue;}
            else {
                unsigned r=(red+4u)>>3u,g=(green+4u)>>3u,b=(blue+4u)>>3u;
                uint16_t pixel=(uint16_t)((r>31u?31u:r)|((g>31u?31u:g)<<5u)|((b>31u?31u:b)<<10u)|((g_decode_command&0x02000000u)?0x8000u:0u));
                g_pixels[g_pixel_count++]=(uint8_t)pixel;g_pixels[g_pixel_count++]=(uint8_t)(pixel>>8u);
            }
        }
    }
    g_macroblocks++;return 1;
}
static int MdecBeginCommand(uint32_t command,pe_addr_t source)
{
    uint32_t words=command&0xFFFFu;
    if(command>>29u!=1u) return MdecBoundary("MDEC_decode_command",command);
    unsigned required_tables=((command>>27u)&3u)<2u?5u:7u;
    if((g_tables&required_tables)!=required_tables) return MdecBoundary("MDEC_missing_tables",g_tables);
    if(!PE_RangeIsRam(source,words*4u)) return MdecBoundary("MDEC_input_range",source);
    /* A new decode command while the previous one still holds input
     * (psx-spx MDEC: a command owns exactly its N parameter words; FE00h
     * at a block start or after EOB is ignored, anywhere else it is EOB).
     * The hardware decodes those words in order, so their macroblocks are
     * queued in the data-out FIFO ahead of the new command's output and
     * the next DMA1 reads them first.  Model that: finish the old
     * command's complete macroblocks into g_stale (after any output not
     * yet read) and serve it before the new command's pixels.  A trailing
     * partial macroblock yields no output (only complete macroblocks
     * reach the FIFO); psx-spx does not document it further.  The
     * command is only parsed here, lazily at DMA0 service, so an
     * already-queued DMA1 request belongs to the new command.  Not
     * reached by the Day-1 movies (FMV001-FMV004: 0 occurrences). */
    if(g_input_pos<g_input_count || g_pixel_pos<g_pixel_count) {
        uint32_t keep=g_stale_count-g_stale_pos;
        memmove(g_stale,g_stale+g_stale_pos,keep);g_stale_pos=0;g_stale_count=keep;
        for(;;) {
            uint32_t n=g_pixel_count-g_pixel_pos;
            if(n) {
                if(g_stale_count+n>sizeof(g_stale)) return MdecBoundary("MDEC_stale_output_overflow",g_stale_count);
                memcpy(g_stale+g_stale_count,g_pixels+g_pixel_pos,n);
                g_stale_count+=n;g_pixel_pos=g_pixel_count;
                g_mdec.stale_output_bytes+=n;
            }
            while(g_input_pos<g_input_count && g_input[g_input_pos]==0xFE00u) g_input_pos++;
            if(g_input_pos==g_input_count) break;
            g_drain=1;
            int ok=MdecMacroblock();
            g_drain=0;
            if(!ok) {g_pixel_pos=g_pixel_count=0;break;}
        }
        g_input_pos=g_input_count;
        g_mdec.stale_input_discards++;
    }
    g_decode_command=command;g_input_count=words*2u;g_input_pos=0;g_pixel_pos=g_pixel_count=0;g_macroblocks=0;g_decode_valid=1;
    for(unsigned i=0;i<g_input_count;i++) g_input[i]=PE_LoadU16(source+i*2u);
    return 1;
}
int PE_MDEC_BeginDecode(pe_addr_t command_block)
{
    if(!PE_RangeIsRam(command_block,4u)) return MdecBoundary("MDEC_command_range",command_block);
    return MdecBeginCommand(PE_LoadU32(command_block),command_block+4u);
}
int PE_MDEC_HasDecode(void) { return g_decode_valid || g_input_pending; }
int PE_MDEC_Service(void)
{
    int completed=0;
    if(PE_Port_ShouldStop()) return 0;
    if(g_mdec.dma0_active && (g_mdec.control_last_write&0x40000000u) && (PE_GPU_ReadDPCR()&8u)) {
        if(g_input_pending) {
            uint32_t available=(g_mdec.dma0_bcr>>16u)*32u;
            if((g_mdec.command_last_write&0xFFFFu)>available) return MdecBoundary("MDEC_input_short",available);
            if(!MdecBeginCommand(g_mdec.command_last_write,g_mdec.dma0_madr)) return 0;
        }
        g_input_pending=0;g_mdec.dma0_active=0;g_mdec.completed_upload_count++;
        g_mdec.dma0_madr+=(g_mdec.dma0_bcr>>16u)*128u;
        g_mdec.dma0_bcr&=0xFFFFu;g_mdec.dma0_chcr&=~0x01000000u;
        (void)PE_GPU_LatchDMACompletionFlag(0u);completed=1;
    }
    if((g_mdec.dma1_chcr&0x01000000u) && g_decode_valid && !g_input_pending &&
       (g_mdec.control_last_write&0x20000000u) && (PE_GPU_ReadDPCR()&0x80u)) {
        pe_addr_t destination=PE_RAM_BASE+(g_mdec.dma1_madr&0x00FFFFFCu);
        if(!PE_MDEC_ReadPixels(destination,g_output_bytes)) return 0;
        g_mdec.dma1_madr=(g_mdec.dma1_madr+g_output_bytes)&0xFFFFFFu;
        g_mdec.dma1_bcr&=0xFFFFu;g_mdec.dma1_chcr&=~0x01000000u;
        g_mdec.completed_output_count++;g_output_bytes=0;
        (void)PE_GPU_LatchDMACompletionFlag(1u);completed=1;
    }
    if(completed) (void)PE_IRQ_BridgeDICRRisingEdge(PE_IRQ_Generation());
    return completed;
}
int PE_MDEC_SubmitOutput(pe_addr_t destination,uint32_t words)
{
    if(g_mdec.dma1_chcr&0x01000000u) {
        (void)PE_MDEC_Service();
        if(PE_Port_ShouldStop()) return 0;
        if(g_mdec.dma1_chcr&0x01000000u) return MdecBoundary("MDEC_output_wait",g_mdec.dma1_chcr);
    }
    PE_GPU_WriteDPCR(PE_GPU_ReadDPCR()|0x88u);
    g_mdec.dma1_chcr=0;
    g_mdec.dma1_madr=destination&0xFFFFFFu;
    g_mdec.dma1_bcr=((words>>5u)<<16u)|0x20u;
    uint32_t blocks=g_mdec.dma1_bcr>>16u;
    g_output_bytes=(blocks?blocks:65536u)*128u;
    g_mdec.dma1_chcr=0x01000200u;g_mdec.output_count++;
    return 1;
}
int PE_MDEC_ReadPixels(pe_addr_t destination,uint32_t bytes)
{
    if(!PE_RangeIsRam(destination,bytes)) return MdecBoundary("MDEC_output_range",destination);
    for(unsigned i=0;i<bytes;i++) {
        if(g_stale_pos<g_stale_count) {PE_StoreU8(destination+i,g_stale[g_stale_pos++]);continue;}
        if(g_pixel_pos==g_pixel_count && !MdecMacroblock()) return 0;
        PE_StoreU8(destination+i,g_pixels[g_pixel_pos++]);
    }
    /* Ignore command-end padding after the last complete output block. */
    if(g_pixel_pos==g_pixel_count) while(g_input_pos<g_input_count && g_input[g_input_pos]==0xFE00u) g_input_pos++;
    return 1;
}
uint32_t PE_MDEC_DecodedMacroblocks(void) { return g_macroblocks; }

static uint64_t Fnv1a64(const uint8_t *data, uint32_t size)
{
    uint64_t value = UINT64_C(0xCBF29CE484222325);
    uint32_t i;

    for (i = 0u; i < size; i++) {
        value ^= data[i];
        value *= UINT64_C(0x100000001B3);
    }
    return value;
}

void PE_MDEC_Init(void)
{
    memset(&g_mdec, 0, sizeof(g_mdec));
    memset(g_quant,0,sizeof(g_quant));memset(g_scale,0,sizeof(g_scale));g_tables=0;
    g_input_pos=g_input_count=g_pixel_pos=g_pixel_count=g_macroblocks=0;
    g_stale_pos=g_stale_count=0;
    g_decode_valid=g_input_pending=0;g_output_bytes=0;
}

void PE_MDEC_BeginReset(void)
{
    uint32_t reset_count = g_mdec.reset_count + 1u;

    memset(&g_mdec, 0, sizeof(g_mdec));
    g_mdec.reset_count = reset_count;
    g_input_pos=g_input_count=g_pixel_pos=g_pixel_count=g_macroblocks=0;
    g_stale_pos=g_stale_count=0;
    g_decode_valid=g_input_pending=0;g_output_bytes=0;
    PE_MDEC_WriteControl(0x80000000u);
}

void PE_MDEC_WriteControl(uint32_t value)
{
    g_mdec.control_last_write = value;
    g_mdec.control_write_count++;
}

void PE_MDEC_ClearDmaChannels(void)
{
    g_mdec.dma0_madr = 0u;
    g_mdec.dma0_bcr = 0u;
    g_mdec.dma0_chcr = 0u;
    g_mdec.dma1_chcr = 0u;
    g_mdec.dma1_madr=g_mdec.dma1_bcr=0;g_input_pending=0;g_output_bytes=0;
    g_mdec.dma0_active = 0;
}

int PE_MDEC_SubmitInputTable(pe_addr_t command_block, uint32_t size_words)
{
    uint32_t blocks = size_words >> 5;
    uint32_t words = blocks << 5;
    uint32_t bytes = words << 2;
    const uint8_t *payload;
    PeMdecUpload *upload;

    if (g_mdec.dma0_active) {
        (void)PE_MDEC_Service();
        if(PE_Port_ShouldStop()) return -1;
        if(g_mdec.dma0_active) {MdecBoundary("MDEC_input_wait",g_mdec.dma0_chcr);return -1;}
    }
    g_mdec.input_wait_count++;

    payload = PE_TranslateConst((pe_addr_t)(command_block + 4u), bytes);
    PE_GPU_WriteDPCR(PE_GPU_ReadDPCR() | 0x88u);
    g_mdec.command_last_write = PE_LoadU32(command_block);
    g_mdec.dma0_madr = (pe_addr_t)(command_block + 4u);
    g_mdec.dma0_bcr = (blocks << 16) | 0x20u;
    g_mdec.dma0_chcr = MDEC_DMA_CHCR_INPUT;
    g_mdec.dma0_active = 1;

    upload = &g_mdec.uploads[g_mdec.upload_count % PE_MDEC_UPLOAD_HISTORY];
    upload->command = g_mdec.command_last_write;
    upload->source = g_mdec.dma0_madr;
    upload->word_count = words;
    upload->bcr = g_mdec.dma0_bcr;
    upload->payload_fnv1a64 = Fnv1a64(payload, bytes);
    /* Retain actual device tables as well as historical upload telemetry. */
    unsigned kind=g_mdec.command_last_write>>29u;
    if(kind==2u && bytes>=64u) {
        memcpy(g_quant[0],payload,64u);g_tables|=1u;
        if((g_mdec.command_last_write&1u) && bytes>=128u) {memcpy(g_quant[1],payload+64u,64u);g_tables|=2u;}
    } else if(kind==3u && bytes>=128u) {
        for(unsigned i=0;i<64u;i++) g_scale[i]=(int16_t)((unsigned)payload[i*2u]|((unsigned)payload[i*2u+1u]<<8u));
        g_tables|=4u;
    }
    if(kind==1u) g_input_pending=1;
    g_mdec.upload_count++;
    return 0;
}

void PE_MDEC_GetState(PeMdecState *out)
{
    if (out != NULL)
        *out = g_mdec;
}
