#!/usr/bin/env bash
# scripts/setup_mipsel_host.sh — install the "modern" mipsel-linux-gnu mips
# cross toolchain into tools/mipsel-host/ WITHOUT root.
#
# Why this exists: the documented build path runs scripts/build_us.sh inside
# the `pe-mipsel-img` docker image (debian:trixie + gcc-mipsel-linux-gnu). Some
# hosts have no docker/podman/distrobox and no mipsel GCC anywhere in the apt
# sources (Ubuntu 26.04 "resolute" ships only binutils-mipsel-linux-gnu; the
# `gcc-mipsel-linux-gnu` package is absent). This script pins the *exact same*
# Debian trixie packages the Dockerfile installs, downloads the .debs, checks
# their SHA-256, unpacks them under the git-ignored tools/mipsel-host/, and
# writes thin bin/ shims so the tree-local toolchain is self-contained
# (LD_LIBRARY_PATH + GCC's relocatable cc1 lookup are handled by the shims).
#
# The result is byte-identical tooling to the docker image:
#   gcc (Debian 14.2.0-13) 14.2.0, GNU as/ld (Debian) 2.44
#
# Idempotent: a stamp file keyed on the pinned package set short-circuits
# re-runs; downloads are hash-verified. Requires network + curl + dpkg-deb.
# Docs: docs/ai_context/TOOLCHAIN_REBUILD.md
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PREFIX="$ROOT/tools/mipsel-host"
CACHE="$PREFIX/.debs"
BASE="http://deb.debian.org/debian"
STAMP="$PREFIX/.installed"

# name|pool-path|sha256 — Debian trixie (13), amd64 host packages. These are
# the transitive closure of `gcc-mipsel-linux-gnu` + `binutils-mipsel-linux-gnu`
# as resolved by the Debian trixie index on 2026-09-11, restricted to what this
# build actually needs (it compiles freestanding C with `-c`, so no libc
# headers and no target libc are required; host libmpc/libisl are needed by
# cc1 and are the only host runtime libraries Ubuntu lacks).
PACKAGES=(
  "gcc-14-mipsel-linux-gnu|pool/main/g/gcc-14-cross-mipsen/gcc-14-mipsel-linux-gnu_14.2.0-13cross1_amd64.deb|04a58165ab8f9a1c692d5244b5608251e9b18649e8832a8226cd103de2fa878a"
  "gcc-14-mipsel-linux-gnu-base|pool/main/g/gcc-14-cross-mipsen/gcc-14-mipsel-linux-gnu-base_14.2.0-13cross1_amd64.deb|3983042af2d6b7b365a588b394d538559a59a3d0d2cc2a0efac2bb3a23c99501"
  "gcc-14-cross-base-mipsen|pool/main/g/gcc-14-cross-mipsen/gcc-14-cross-base-mipsen_14.2.0-13cross1_all.deb|5823a47dba0c833ce0381cd8e5cf21c9120df92a54a603685dedad8dbf6ea74a"
  "cpp-14-mipsel-linux-gnu|pool/main/g/gcc-14-cross-mipsen/cpp-14-mipsel-linux-gnu_14.2.0-13cross1_amd64.deb|40fec73bd218c5766da2981103b8e8f66f7bc60de748d0673f1f10e657d8be43"
  "libgcc-14-dev-mipsel-cross|pool/main/g/gcc-14-cross-mipsen/libgcc-14-dev-mipsel-cross_14.2.0-13cross1_all.deb|4b5fa7f019ebf939eeeeead8551b99cf2f777479b84af1d920193849fe969174"
  "binutils-mipsel-linux-gnu|pool/main/b/binutils-mipsen/binutils-mipsel-linux-gnu_2.44-3cross1+nmu1+b1_amd64.deb|2514dd910f344c923531f959ea4ffd542e51640aac0caa1bc51ee293851788ab"
  "binutils-common|pool/main/b/binutils/binutils-common_2.44-3_amd64.deb|002da5d23f8757dee97a2c0a40e0e1d4d85a43da094488ee2ee7068d4d3691f9"
  "libsframe1|pool/main/b/binutils/libsframe1_2.44-3_amd64.deb|38f625dfdc582717029ac3a3e97c51d994ec2e7a0e9b230c6b44e40d1276311f"
  "libmpc3|pool/main/m/mpclib3/libmpc3_1.3.1-1+b3_amd64.deb|2af0a5c128e03694a41c0b011bd8a958b7297436cdb3a15ddad7866dae8c300b"
  "libisl23|pool/main/i/isl/libisl23_0.27-1_amd64.deb|ac8518042e81c00de1effb72bba7e88ac4ecd488f7ea8b9e3ebc63159cb53b35"
)

sha256_of() { sha256sum "$1" | awk '{print $1}'; }

want="$(
  for entry in "${PACKAGES[@]}"; do printf '%s\n' "$entry"; done | sha256sum | awk '{print $1}'
)"

if [[ -f "$STAMP" && "$(cat "$STAMP")" == "$want" && -x "$PREFIX/bin/mipsel-linux-gnu-gcc" ]]; then
    echo "OK  mipsel-host toolchain already installed: $PREFIX"
    exit 0
fi

mkdir -p "$CACHE"

for entry in "${PACKAGES[@]}"; do
    IFS='|' read -r name path digest <<<"$entry"
    deb="$(basename "$path")"
    dest="$CACHE/$deb"
    if [[ -f "$dest" && "$(sha256_of "$dest")" == "$digest" ]]; then
        continue
    fi
    echo "Fetching $name ($deb) ..."
    rm -f "$dest"
    curl -fsSL -o "$dest" "$BASE/$path"
    actual="$(sha256_of "$dest")"
    if [[ "$actual" != "$digest" ]]; then
        echo "ERROR: SHA-256 mismatch for $deb" >&2
        echo "  expected $digest" >&2
        echo "  actual   $actual" >&2
        exit 1
    fi
done

echo "Unpacking into $PREFIX ..."
mkdir -p "$PREFIX/usr"
for entry in "${PACKAGES[@]}"; do
    IFS='|' read -r _ path _ <<<"$entry"
    dpkg-deb -x "$CACHE/$(basename "$path")" "$PREFIX"
done

# Self-contained shims: bin/<name> sets the library path Debian's relocated
# cross libs need and re-exports PATH so the gcc driver can find as/ld, then
# execs the real binary under usr/bin/.
make_shim() {
    local name="$1" target="$2"
    cat >"$PREFIX/bin/$name" <<EOF
#!/bin/sh
# Generated by scripts/setup_mipsel_host.sh — do not edit.
self="\$0"
case "\$self" in */*) ;; *) self="\$(command -v -- "\$self")" ;; esac
prefix="\$(CDPATH= cd -- "\$(dirname -- "\$self")/.." && pwd)"
export LD_LIBRARY_PATH="\$prefix/usr/lib/x86_64-linux-gnu\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export PATH="\$prefix/bin:\$prefix/usr/bin:\$PATH"
exec "\$prefix/usr/bin/$target" "\$@"
EOF
    chmod +x "$PREFIX/bin/$name"
}

mkdir -p "$PREFIX/bin"
shopt -s nullglob
for real in "$PREFIX"/usr/bin/mipsel-linux-gnu-*; do
    base="$(basename "$real")"
    make_shim "$base" "$base"
done
# Debian ships the driver as `mipsel-linux-gnu-gcc-14`; the metapackage only
# adds the version-less symlink. Provide the name the build expects.
make_shim mipsel-linux-gnu-gcc mipsel-linux-gnu-gcc-14

echo "Smoke test: gcc version + freestanding compile/assemble ..."
version="$("$PREFIX/bin/mipsel-linux-gnu-gcc" --version | head -1)"
case "$version" in
    *14.2.0*) echo "OK  $version" ;;
    *) echo "ERROR: unexpected compiler version: $version" >&2; exit 1 ;;
esac

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
printf 'int f(void){return 0x7F7F7F;}\n' >"$tmp/x.c"
"$PREFIX/bin/mipsel-linux-gnu-gcc" -EL -mips1 -mfp32 -mabi=32 -G0 -fno-pic \
    -mno-abicalls -ffreestanding -fno-builtin -O1 -c -o "$tmp/x.o" "$tmp/x.c"
printf 'nop\n' >"$tmp/x.s"
"$PREFIX/bin/mipsel-linux-gnu-as" -EL -mips1 -mabi=32 -o "$tmp/x2.o" "$tmp/x.s"
[[ -s "$tmp/x.o" && -s "$tmp/x2.o" ]] || { echo "ERROR: smoke test produced no object" >&2; exit 1; }
echo "OK  as/ld/objcopy/readelf + cc1 resolve"

printf '%s' "$want" >"$STAMP"
echo "mipsel-host toolchain ready: $PREFIX/bin (prepend to PATH)"
