#!/usr/bin/env python3
"""Unit tests for gen_overlay_ports.py (overlay-port mechanism, step 1).

Run: python3 tools/analysis/test_gen_overlay_ports.py
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_overlay_ports as o  # noqa: E402

OVL = {"id": "ovl_0700", "vram": 0x8018EFF0, "end": 0x8019BFC4, "leaves": {}}
WINDOWS = [("ovl_0700", 0x8018EFF0, 0x8019BFC4), ("ovl_03C5", 0x80120D00, 0x80122400)]

TU = '''/*
 * decomp-source: func_80190D08
 * evidence: docs/evidence/func_80190D08/REPORT.md
 * GENERATED by tools/analysis/gen_decomp_ports.py from src/func_80190D08.c
 */
#include "pe_guest_decomp.h"
/* boundary: func_80191000 has no pc_port implementation yet */
#define func_80191000(...) PE_D_COMP_BOUNDARY1("func_80191000", 0x80191000u, __VA_ARGS__)
/* boundary: func_80121C04 has no pc_port implementation yet */
#define func_80121C04(...) PE_D_COMP_BOUNDARY1("func_80121C04", 0x80121C04u, __VA_ARGS__)
extern int func_80190AEC(int);
int func_80190D08(int kind) {
    func_80191000(kind);
    func_80121C04(kind);
    func_80073C94();
    return func_80190AEC(kind);
}
'''


class OverlayPostProcessTests(unittest.TestCase):
    def out(self, emitted=frozenset({"func_80190AEC"})):
        return o.post_process(OVL, "func_80190D08", TU, set(emitted), WINDOWS)

    def test_banner_names_the_overlay(self):
        out = self.out()
        self.assertIn("decomp-source-overlay: ovl_0700/func_80190D08", out)
        self.assertNotIn("decomp-source: func_80190D08", out)
        self.assertIn("src/overlays/ovl_0700/func_80190D08.c", out)
        self.assertIn("docs/evidence/ovl_0700-func_80190D08/REPORT.md", out)

    def test_leaf_and_emitted_local_callee_are_renamed(self):
        out = self.out()
        self.assertIn("#define func_80190D08 ovl_0700__func_80190D08", out)
        self.assertIn("#define func_80190AEC ovl_0700__func_80190AEC", out)
        # the rename block follows the shim include
        self.assertLess(out.index('#include "pe_guest_decomp.h"'),
                        out.index("#define func_80190D08 ovl_0700__"))

    def test_unemitted_local_callee_is_a_labelled_boundary(self):
        out = self.out()
        self.assertIn('("ovl_0700:func_80191000"', out)
        self.assertNotIn("#define func_80191000 ovl_0700__", out)

    def test_cross_overlay_callee_is_a_labelled_boundary(self):
        out = self.out()
        self.assertIn('("overlay:func_80121C04"', out)

    def test_exe_callee_keeps_its_plain_name(self):
        out = self.out()
        self.assertIn("func_80073C94();", out)
        self.assertNotIn("__func_80073C94", out)

    def test_non_emitted_local_is_not_renamed(self):
        out = self.out(emitted=frozenset())
        self.assertNotIn("#define func_80190AEC", out)

    def test_symbols_differ_per_overlay(self):
        self.assertNotEqual(o.symbol("ovl_0700", "func_8018F1E4"),
                            o.symbol("room_m0014i", "func_8018F1E4"))


class OverlayConfigTests(unittest.TestCase):
    def test_parse_real_overlay_config(self):
        ovl = o.parse_overlay("ovl_03C9")
        self.assertEqual(ovl["vram"], 0x801ED7F8)
        self.assertIn("func_801F1B00", ovl["leaves"])
        leaf = ovl["leaves"]["func_801F1B00"]
        self.assertEqual(leaf["vram"], 0x801F1B00)
        self.assertEqual(leaf["file_size"], 0x10)
        self.assertTrue(o.in_window(ovl, "func_801F1B00"))
        self.assertFalse(o.in_window(ovl, "func_80073C94"))


class RoomDedupeTests(unittest.TestCase):
    """Step 4: rooms are grouped by body + same-room callee identity."""

    def setUp(self):
        import tempfile
        self.tmp = tempfile.TemporaryDirectory()
        self.old_src = o.OVL_SRC_DIR
        o.OVL_SRC_DIR = Path(self.tmp.name)
        body_leaf = "int func_8018F100(int a) { return func_8018F200(a) + 1; }\n"
        callee_a = "int func_8018F200(int a) { return a * 2; }\n"
        callee_b = "int func_8018F200(int a) { return a * 3; }\n"
        for room, callee in (("room_a", callee_a), ("room_b", callee_a),
                             ("room_c", callee_b), ("room_d", None)):
            d = o.OVL_SRC_DIR / room
            d.mkdir()
            (d / "func_8018F100.c").write_text(body_leaf)
            if callee:
                (d / "func_8018F200.c").write_text(callee)

    def tearDown(self):
        o.OVL_SRC_DIR = self.old_src
        self.tmp.cleanup()

    def rooms(self):
        def mk(r, names):
            return {"id": r, "vram": 0x8018EFE8, "end": 0x801B0000,
                    "leaves": {n: {} for n in names}}
        return [mk("room_a", ["func_8018F100", "func_8018F200"]),
                mk("room_b", ["func_8018F100", "func_8018F200"]),
                mk("room_c", ["func_8018F100", "func_8018F200"]),
                mk("room_d", ["func_8018F100"])]    # callee is unmatched asm here

    def test_identical_body_and_callee_merge(self):
        k = o.room_groups(self.rooms())
        self.assertEqual(k[("room_a", "func_8018F100")], k[("room_b", "func_8018F100")])

    def test_same_body_different_callee_code_does_not_merge(self):
        k = o.room_groups(self.rooms())
        self.assertNotEqual(k[("room_a", "func_8018F100")], k[("room_c", "func_8018F100")])

    def test_unmatched_same_room_callee_is_room_specific(self):
        k = o.room_groups(self.rooms())
        self.assertNotEqual(k[("room_a", "func_8018F100")], k[("room_d", "func_8018F100")])

    def test_group_symbol(self):
        self.assertEqual(o.group_symbol("fcb523b2deadbeef", "func_8018F1CC"),
                         "room_fcb523b2__func_8018F1CC")


def _tmpdir() -> Path:
    """Scratch dir under $TMPDIR (callers keep it off the /tmp tmpfs)."""
    return Path(tempfile.mkdtemp(prefix="gen_ovl_test_"))


class BlobResolutionTests(unittest.TestCase):
    """A git worktree has no extracted blobs (build/ is git-ignored); the
    registry must still fingerprint every overlay, from the main checkout."""

    def setUp(self):
        self.tmp = _tmpdir()
        self.addCleanup(shutil.rmtree, self.tmp, True)
        self.cfg = self.tmp / "cfg"
        self.cfg.mkdir()
        (self.cfg / "room_x.yaml").write_text(
            "options:\n  target_path: build/extracted/disc1/peimg/room_x_c2.bin\n",
            encoding="utf-8")
        self.old_cfg = o.OVL_CONFIG_DIR
        o.OVL_CONFIG_DIR = self.cfg
        self.addCleanup(setattr, o, "OVL_CONFIG_DIR", self.old_cfg)
        self.wt, self.main = self.tmp / "wt", self.tmp / "main"
        for r in (self.wt, self.main):
            r.mkdir()

    def put(self, root: Path) -> Path:
        p = root / "build/extracted/disc1/peimg/room_x_c2.bin"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(b"\x08\x00\xe0\x03\x21\x10\x00\x00")
        return p

    def test_worktree_without_blobs_falls_back_to_main_checkout(self):
        want = self.put(self.main)
        self.assertEqual(o.blob_path("room_x", [self.wt, self.main]), want.resolve())

    def test_own_checkout_wins(self):
        self.put(self.main)
        want = self.put(self.wt)
        self.assertEqual(o.blob_path("room_x", [self.wt, self.main]), want.resolve())

    def test_missing_everywhere_is_none(self):
        self.assertIsNone(o.blob_path("room_x", [self.wt, self.main]))

    def test_config_without_target_path_is_none(self):
        (self.cfg / "room_y.yaml").write_text("options: {}\n", encoding="utf-8")
        self.assertIsNone(o.blob_path("room_y", [self.wt, self.main]))


@unittest.skipUnless(shutil.which("git"), "git not installed")
class MainCheckoutTests(unittest.TestCase):
    def setUp(self):
        self.tmp = _tmpdir()
        self.addCleanup(shutil.rmtree, self.tmp, True)
        env = dict(os.environ, GIT_CONFIG_GLOBAL=os.devnull, GIT_CONFIG_SYSTEM=os.devnull)
        self.main = self.tmp / "main"
        self.main.mkdir()

        def git(*a, cwd=self.main):
            subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t",
                            "-c", "commit.gpgsign=false", *a], cwd=cwd, env=env,
                           check=True, capture_output=True)
        git("init", "-q")
        (self.main / "f").write_text("x", encoding="utf-8")
        git("add", "f")
        git("commit", "-q", "-m", "init")
        self.wt = self.tmp / "wt"
        git("worktree", "add", "-q", "--detach", str(self.wt))

    def test_worktree_resolves_to_main_checkout(self):
        self.assertEqual(o.main_checkout(self.wt), self.main.resolve())

    def test_main_checkout_resolves_to_itself(self):
        self.assertEqual(o.main_checkout(self.main), self.main.resolve())

    def test_outside_a_repository_is_none(self):
        outside = self.tmp / "plain"
        outside.mkdir()
        env_ceiling = os.environ.get("GIT_CEILING_DIRECTORIES")
        os.environ["GIT_CEILING_DIRECTORIES"] = str(self.tmp)
        try:
            self.assertIsNone(o.main_checkout(outside))
        finally:
            if env_ceiling is None:
                del os.environ["GIT_CEILING_DIRECTORIES"]
            else:
                os.environ["GIT_CEILING_DIRECTORIES"] = env_ceiling


class RequireBlobsTests(unittest.TestCase):
    def test_nothing_missing_passes(self):
        o.require_blobs({}, [Path("/r")])

    def test_missing_blob_fails_loudly_non_zero(self):
        with self.assertRaises(SystemExit) as cm:
            o.require_blobs({"room_m0348i": 27, "room_m0023i": 1}, [Path("/wt"), Path("/main")])
        msg = str(cm.exception.code)
        self.assertIsInstance(cm.exception, o.MissingBlobError)
        self.assertIn("refusing to write fingerprint 0", msg)
        self.assertIn("room_m0348i: 27 registry entries", msg)
        self.assertIn("room_m0023i: 1 registry entry", msg)
        self.assertIn("/wt, /main", msg)
        # SystemExit with a message exits the process with status 1.
        self.assertNotIn(cm.exception.code, (0, None))


if __name__ == "__main__":
    unittest.main()
